### ISSUE TITLE
Zend\Http\Client does not support input streams

### ISSUE THREAD

**Issue by adamlundrigan** [zendframework/zf2#2645]
In ZF1, `Zend_Http_Client` supported input streams for `PUT`

```
$fp = file_open("mybigfile.zip", 'r');
$client->setRawData($fp, 'application/zip')->request('PUT');
```

This functionality no longer exists in ZF2 `Zend\Http\Client`, as `::setRawBody` just proxies to `Zend\Stdlib\Message::setContent`, which only supports string-able input (scalars or objects with a `__toString`)

**Comment by weierophinney** [comment]
@adamlundrigan From what I can see, if your HTTP client adapter implements `Zend\Http\Client\Adapter\StreamInterface`, this *will* work; we only raise an exception if the body is a stream, but the adapter doesn't support streaming.
