### ISSUE TITLE
Zend\Http\Client does not support HTTP Digest Authentication

### ISSUE THREAD

**Issue by adamlundrigan** [zendframework/zf2#2646]
`Zend\Http\Client::calcAuthDigest`` appears to have the workings for Digest Authentication (https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client.php#L674), but it is not integrated into the request flow.

**Comment by weierophinney** [comment]
Closing; if you're interested in re-opening, create a pull request with an implementation.
