### ISSUE TITLE
In a console controller response->setErrorCode is replace by ConsoleModel

### ISSUE THREAD

**Issue by bouchery** [zendframework/zf2#2722]
When using $this->response->setErrorCode(..) in a console controller, after returning a string for output or a ConsoleModel, errorCode is set to "null" in meta response message.

Property $response is not really usable.

**Comment by weierophinney** [comment]
I've figured out why. At some point, we introduced `Zend\Mvc\ResponseSender\ConsoleResponseSender`, and, at that time, deprecated the usage of `Zend\Console\Response::send()` — as in, we no longer call it. That method had an `exit($errorLevel)` call in it which was responsible for setting the exit status code; the "new" response sender does not call exit.

To get the behavior you want, you need to use `Zend\View\Model\ConsoleModel`:

```php
// Inside your console action method; make sure you import the class!
$output = new ConsoleModel();
$output->setErrorLevel(-15);
$output->setResult("done!");
return $output;
```

This works correctly. One note: most shells will not deal with negative numbers for statuses, and will instead subtract that number for the maximum status; -15 becomes 241.
