### ISSUE TITLE
Zend\View\Helper\Navigation should allow for more acl checks than Zend\Permissions\Acl\

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf2#2923]
**This is an issue from version 1.**

## Jira Information

<table>
<tr><th>Original Issue</th><td><a href="http://framework.zend.com/issues/browse/ZF-10377">ZF-10377</a></td></tr>
<tr><th>Issue Type</th><td>Improvement</td></tr>
<tr><th>Reporter</th><td>Dolf Schimmel (Freeaqingme) 
 </td></tr>
<tr><th>Created</th><td>08/24/10</td></tr>
<tr><th>Assignee</th><td>Frank Brückner (froschdesign)</td></tr>
<tr><th>Components</th><td>Zend\Navigation, Zend\View</td></tr>
</table>

## Description

Currently the interface `Zend\View\Helper\Navigation\HelperInterface` defines the method `setAcl` as follows: public function `setAcl(Zend\Permissions\Acl\Acl $acl = null);`

Imho that should be changed to a generic callback, in order to allow people to specify alternate sources of authorization like their own service layer.

*__Notice:__ Classnames in description updated*

**Comment by weierophinney** [comment]
Implemented in #3693
