### ISSUE TITLE
Zend\Db\Sql\Select doesn't support forUpdate()

### ISSUE THREAD

**Issue by bartko-s** [zendframework/zf2#3012]
Zend\Db\Sql\Select doesn't support forUpdate().
This feature is available in ZF1 Zend_Db_Select class $select->forUpdate();

**Comment by weierophinney** [comment]
`Zend\Db` is an abstraction layer. Any methods we add for one platform must necessarily be in the interface for all platforms, which means:

- concrete implementation for the target platform
- emulation implementations for any other platforms that do not support the feature

Considering this feature would require a large number of emulation implementations, which are always *very* prone to maintenance issues, the solution is to drop to manual sql using the adapter. Sorry, but that's the only sane path forward.

**Comment by Pittiplatsch** [comment]
Agreeing with `Zend\Db` beinig an abstraction layer, which must not implement platform-specific features, it's not necessarily `Zend\Db\Sql\Select` itself who needs to implement this.

Switching to manual sql creation isn't an option in my concrete situation, as sql statements are built highly dynamically based on configuration, with "for update" just being a rather normal option.

Actually, for my project I have implemented a really dirty solution on top of the original `Zend\Db\Sql\Platform\Mysql\SelectDecorator` which checks for an additional public (*urgh!*) flag `forUpdate` set on `Zend\Db\Sql\Select` instance. This flag must be set manually via `$select->forUpdate = true` (*urgh!*) - I couldn't find a way to do this via a real setter without replacing `Zend\Db\Sql\Select` completely, which definitely is a no-go...

`Zend\Db` already provides platform specific implementations via platform decorators. However, IMO this architecture is still too static. It can be used to *change* behaviour implemented `Zend\Db\Sql\Select` for a specific platform, but I couldn't find a way of implementing *new* platform specific behaviour.

If I am missing a possibility - possibliy even an already existing example in ZF code - please shed some light ;-)

**Comment by Pittiplatsch** [comment]
Although this issue is closed, I'd appreciate some feedback.
Therefore ping @weierophinney, @Ocramius, @ralphschindler.

IMO this issue should be re-opened. Technically the title might not be 1000% correct, but the requested feature (even being special platform depending) is a valid one as I stated in my last comment.
As a parallel nobody would decline `auto_increment` being a valid feature for a db abstraction layer although this is highly platform dependent.

**Comment by nadalizadeh** [comment]
Dirty hack for adding "FOR UPDATE" using a decorator:
https://gist.github.com/nadalizadeh/99e37432daa2579e8ce43de5113dac76

**Comment by dfelton** [comment]
+1
