### ISSUE TITLE
Use Zend\Paginator with DbSelect adapter and Zend\Cache

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zf2#3190]
I am just trying to use the `DbSelect` adapter with `Zend\Paginator` which works as expected. But when I want to add `Zend\Cache` to the mix, I get some problems.

When I add the serializer plugin I get this error:

    "You cannot serialize or unserialize PDOStatement instances"

When I remove the serializer plugin I get this error:

    "Error writing file"

The cache dir is writable but since it is tried to write a PDOStatement to the cache this seems to be impossible.

I get the following exception.

```
Fatal error: Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDOStatement instances' in /home/devhost/zf2-buch-listings/zf2-buch-chapter11/vendor/zendframework/zendframework/library/Zend/Serializer/Adapter/PhpSerialize.php:54

Stack trace:

#0 [internal function]: PDOStatement->__sleep()

#1 /home/devhost/zf2-buch-listings/zf2-buch-chapter11/vendor/zendframework/zendframework/library/Zend/Serializer/Adapter/PhpSerialize.php(54): serialize(Object(Zend\Db\ResultSet\ResultSet))

#2 /home/devhost/zf2-buch-listings/zf2-buch-chapter11/vendor/zendframework/zendframework/library/Zend/Cache/Storage/Plugin/Serializer.php(156): Zend\Serializer\Adapter\PhpSerialize->serialize(Object(Zend\Db\ResultSet\ResultSet))

#3 [internal function]: Zend\Cache\Storage\Plugin\Serializer->onWriteItemPre(Object(Zend\Cache\Storage\Event))

#4 /home/devhost/zf2-buch-listings/zf2-buch-chapter11/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(464): call_user_func(Array, Object(Zend\Cache\Storag in /home/devhost/zf2-buch-listings/zf2-buch-chapter11/vendor/zendframework/zendframework/library/Zend/Serializer/Adapter/PhpSerialize.php on line 54
```

The problem lies in the `Zend\Paginator\Paginator::getItemsByPage()` method. The `DbSelect` Adapter returns a `Zend\Db\ResultSet\ResultSet` from its `getItems()` method. This `ResultSet` has the `PDOStatement` object in itself.

**Comment by weierophinney** [comment]
Closing; it looks like a paginator refactor for ZF3 will likely address the issues, but we cannot address it in the current component architecture.
