### ISSUE TITLE
MultiCheckbox set attributes only on options label

### ISSUE THREAD

**Issue by workoutweb** [zendframework/zf2#3407]
Is there a method to specific attributes only on options label in MultiCheckbox element?

if i do `$element->setLabelAttributes(array('class'=>'checkbox'));` each label will have  `class="checkbox"`

````
<div class="control-group ">
    <label for="mySelection" class="checkbox">   <---- here i don't want class="checkbox"
        Selection:
    </label>
    <label class="checkbox">
        <input type="checkbox" checked="checked" value="1" name="mySelection[]">
         First Option
    </label>		
</div>
````
but i want the class only on options value. This is a very common case, because twitter bootstrap require this to work http://twitter.github.com/bootstrap/base-css.html#forms

**Comment by weierophinney** [comment]
There's "I don't like it," and then there's "broken." Based on the reports in this issue, I'd argue we're in the first camp, and thus I'm closing.
