### ISSUE TITLE
Zend\Form\View\Helper\FormCollection#rende rely on that a elementHelper is invokable, but its implementation is not certain

### ISSUE THREAD

**Issue by akomm** [zendframework/zf2#3428]
"Zend\Form\View\Helper\FormCollection#getElementHelper" 
returns "an" instance of "\Zend\Form\View\Helper\AbstractHelper".

Its used here:
```php
// Zend\Form\View\Helper\FormCollection#render:65
$elementHelper = $this->getElementHelper();
```
The retrieved helper is used in the same method/script:
```php
// Zend\Form\View\Helper\FormCollection#render:73
$templateMarkup .= $elementHelper($elementOrFieldset);
// Zend\Form\View\Helper\FormCollection#render:81
$markup .= $elementHelper($elementOrFieldset);
```
We can only be certain, that $elementHelper is "an" instance of "\Zend\Form\View\Helper\AbstractHelper "

But neither the \Zend\Form\View\Helper\AbstractHelper class nor its implemented interface enforce the implementation of the __invoke method. 

Since "#getElementHelper" (see above) does not return a closure or FQCN as string, we only have the choice to enforce the implementation of __invoke in "Zend\View\Helper\HelperInterface" or as abstract in "Zend\View\Helper\AbstractHelper".

**Comment by weierophinney** [comment]
The solution to this would be to add `__invoke()` as a method to `AbstractHelper` and/or `HelperInterface`. The latter would be a BC break, and the former would introduce issues once implementations add any required arguments. This is, in fact, why it's not in the interface or abstract; it was a conscious decision, with known issues, but one that simplifies implementation. Knowing the tradeoffs, I'm not sure there's any other path we can take at this time.
