### ISSUE TITLE
global exception handler

### ISSUE THREAD

**Issue by MatthiasWiesner** [zendframework/zf2#3551]
It would be usefull to be able to define an exception handler, that would be always called when an exception occures, regardless of the origin.

It shouldn't be possible for the application to crash without first calling this handler. Currently the handler that is defined via the \Zend\Log\Logger::registerExceptionHandler does not work properly.
For example I have in module/Application/Module.php:
~~~
class Module
{
    public function onBootstrap(MvcEvent $e)
    {
    ...
    // logger
    $logger = new \Zend\Log\Logger();
    $writer = new \Zend\Log\Writer\Syslog();
    $logger->addWriter($writer, 0);
    \Zend\Log\Logger::registerErrorHandler($logger);
    \Zend\Log\Logger::registerExceptionHandler($logger);
    ...
~~~
but this registered handler is not used for all occuring exceptions. For example, if an exception is thrown in a controller, than the exception is not logged to syslog.

**Comment by weierophinney** [comment]
Not everybody has a use case for this, and there are known issues with what you're attempting.

As you note, exceptions thrown in controllers... are actually caught. This is done so we can present 500, 404, and other HTTP error statuses. You can always add listeners to the dispatch.error event if you also want to log that information. (This is true of the render event as well.)

For exceptions thrown elsewhere — bootstrap, sending the response — you *will* need to register your own exception handler. But that's a detail for your own application, not for the framework.
