### ISSUE TITLE
Imap storage connects protocol in constructor

### ISSUE THREAD

**Issue by jonathaningram** [zendframework/zf2#3697]
This means that if you inject a `Zend\Mail\Storage\Imap` object into the constructor of another dependency, the storage will connect even if it is not yet required.

Is there any way we can change this so that 1) the connection is only done when required or 2) a param can be set to delay connecting until required?

Note: This also applies to some other mail storage classes (e.g. POP3).

**Comment by weierophinney** [comment]
There's another solution, as of ZF 2.3: [lazy services/delegator proxies](http://framework.zend.com/manual/current/en/modules/zend.service-manager.lazy-services.html). Using this pattern, you can inject an automatically generated proxy into an object, but delay actual instantiation until you call a method on the proxy. This solves the problem nicely, as it requires no changes to the class.
