### ISSUE TITLE
Fault in Date Validator

### ISSUE THREAD

**Issue by IgorDePaula** [zendframework/zf2#3720]
I set my format in date validator in annotation form, but on valid the form, the validator dont work, he doesnot accept my format, i debug the classes, and my format is setted, but not accept for tha validator. no in validator, no in annotation options.

**Comment by weierophinney** [comment]
#4162 was closed, and documentation merged that details how to use the format aspects correctly. For anything else, I minimally need a pull request with a test case demonstrating the issue, as I'm not understanding the combination of expected versus actual behavior, particularly with regards to how the objects will be consumed.
