### ISSUE TITLE
Zend\View\Helper\Partial setObjectKey doesn't work with native arrays

### ISSUE THREAD

**Issue by ghost** [zendframework/zf2#3781]
This is true since `objectKey` is only binded when the value passed is an object. As with the code in `__invoke` method:

```php
if (is_scalar($values)) {
    $values = array();
} elseif ($values instanceof ModelInterface) {
    $values = $values->getVariables();
} elseif (is_object($values)) {
    if (null !== ($objectKey = $this->getObjectKey())) {
        $values = array($objectKey => $values);
    } elseif (method_exists($values, 'toArray')) {
        $values = $values->toArray();
    } else {
        $values = get_object_vars($values);
    }
}
```

If I have passed an array like this in the `partialLoop`

```php
$values = array(
    array(
        1 => 'one',
        2 => 'two'
    ),
    array(
        1 => 'one',
        2 => 'two'
    ),
);

$this->partialLoop('template', $values);
```

The value on each iteration will be:

```php
array(
    1 => 'one',
    2 => 'two',
)
```

The problem is it is you cannot access the array value since it's numerical index is binded now within the view.

So to access each element of the value. You have to do this.

```php
$prop = '1';
echo $this->$prop; //will output one
```

Another issue of being unable to work with `setObjectKey` is that you cannot loop again through the array elements.

-----
This is I want to achive.

```php
$this->partialLoop()->setObjectKey('arrayValues');
$this->partialLoop('template', $values);
```

and inside the 'template'

I wanna call `$this->partialLoop('template2', $this->arrayValues);`

**Comment by weierophinney** [comment]
We're passing by reference, and the model is used to create named properties and/or variables inside the template being rendered. Names MUST follow the same conventions as PHP allows. If you're passing a collection of items, then pass a named collection.

Alternately, you can also use the `vars` method to retrieve by key:

```php
echo $this->vars(1);
```
