### ISSUE TITLE
Problem with translator when I use InputFilter factory

### ISSUE THREAD

**Issue by guilherme-santos** [zendframework/zf2#3810]
Hello,
When I use InputFilter factory like that in my Form:

```php
public function getInputFilterSpecification()
{
   return array('id' => array('required' => true))
}
```

OR only the name of validator like that

```php
public function getInputFilterSpecification()
{
   return array('id' => array('validators' => array('name' => 'NotEmpty')))
}
```

The translator doesn't work, but I found something..
In the method `getPluginManager` of `Zend\Validator\ValidatorChain` you create directly `ValidatorPluginManager`... but if create the plugin manager using the Factory `ValidatorManagerFactory` or using the `ServiceLocator`, the translator works fine..

This happen because in the method `injectTranslator` of `Zend\Validator\ValidatorPluginManager` needs a service locator to get translator object..

**Comment by weierophinney** [comment]
All of this was definitely addressed in 2.3; we added factories for validator plugins and filter plugins; the input filter factory now uses these when creating inputs; and the form element factory uses the input filter factory. Essentially, if you're using the SM to manage your input filters and forms, this should all now work seamlessly. If you're not, your options are:

- Modify your code to use them.
- Modify or create factories for your input filters that will pull the ValidatorPluginManager and FilterPluginManager from the service manager and then inject them into your input filter before creating any inputs.
