### ISSUE TITLE
Zend\Session\Container returns by reference

### ISSUE THREAD

**Issue by Mezzle** [zendframework/zf2#3961]
```php
$old_csrf = $session['csrf']; // $session is an instace of Zend\Session\Container
$incoming = $_POST['csrf_token'];
$new_csrf = $generator->generateCSRFToken();
$session['csrf'] = $new_csrf;

if ($old_csrf == $incoming) {
    echo "things are good";
} else {
   echo "things are bad";
}
```

The above is a brief case - but in it, we set the new CSRF token, which, as it is returned by reference, manipulates the $old_csrf variable - therefore making CSRF not work at all. It can theoretically work the other way too - with the variable outside of the container being changed and manipulating inner variable.  

This would be fine if we were expecting it, but this has the potential to cause some rather strange (and barely traceable) errors.

**Comment by adamlundrigan** [comment]
Did this get resolved or is it a won't/cant-fix for ZF2?

**Comment by adamlundrigan** [comment]
@Maks3w this can be closed

**Comment by mwillbanks** [comment]
Yes, this has actually been resolved since the polyfill support has been removed.
