### ISSUE TITLE
Shared flag in AbstractPluginManager does not get passed through ServiceManager

### ISSUE THREAD

**Issue by juriansluiman** [zendframework/zf2#4008]
The `AbstractPluginManager` does have a method `setService($name, $service, $shared = true)`. Current version of master is shown [here](https://github.com/zendframework/zf2/blob/master/library/Zend/ServiceManager/AbstractPluginManager.php#L121). On the other hand, the `ServiceManager` signature is `setService($name, $service)` without the shared flag, shown [here](https://github.com/zendframework/zf2/blob/master/library/Zend/ServiceManager/ServiceManager.php#L357). The plugin does not pass on the shared flag to the service manager.

Example:
 * `$myPluginManager->setService('foo', $bar, false);`

Expected:
 * 'foo' is not shared

Actual:
 * 'foo' is shared

**Comment by adamlundrigan** [comment]
As SM has been split from this repo and will see a 3.x release soon that negates this I'll close this issue here.  If you'd like to see it fixed in 2.x please open a PR on [zendframework/zend-servicemanager](https://github.com/zendframework/zend-servicemanager)
