### ISSUE TITLE
Having an input filter that does not match a form element fails silently

### ISSUE THREAD

**Issue by codemagician** [zendframework/zf2#4017]
Imagine I create a form with elements shoesize, colour and style and then I have a separate input filter class,

class MyInputFilter extends Zend\InputFilter\InputFilter
{
}

in which i add 4 elements shoesize, colour, style and leather.

I attach the input filter inside the form

class MyForm extends Zend\Form\Form
{
    public function __construct(InputFilter $reservationInputFilter) {
        $this->setInputFilter($reservationInputFilter);
    }
}

When $form->isValid() is called the result is false and the form fails to valid.  There is nothing in the getMessages() method, just an empty array.

Now, its very difficult to debug this and find the problem, particularly if you have a large form with many elements.

**Comment by adamlundrigan** [comment]
This isn't so much a "bug" as a side-effect of having a separation of form structure (Zend\Form) and validation (Zend\InputFilter).  Form completely delegates validation to InputFilter; if you don't specify your own InputFilter then Form will build one to match the structure of the form.  By necessity the structure of the InputFilter needs to match the Form structure field-for-field, as they are intended to describe the same model.  It's the developer's responsibility to keep the two representations in sync if you choose to override the autogenerated InputFilter. 

That said, you *can* use an InputFilter with extra elements not found in the form, but you will have to [provide a validation group](http://framework.zend.com/manual/current/en/modules/zend.form.quick-start.html#validation-groups) to the Form; it will pass the validation group along to the InputFilter it composes and the input filter will ignore the fields not in the validation group.   

@Maks3w this can be closed
