### ISSUE TITLE
I wand to add new methods to Rand class

### ISSUE THREAD

**Issue by feridmovsumov** [zendframework/zf2#4023]
**Class:** https://github.com/zendframework/zf2/blob/master/library/Zend/Math/Rand.php

Hi, I want to add some methods to Rand class

These methods are:

**getData()** This method will return any type of data randomly

**getNotInt()** This method will return any type of data except int

**getNotString()**  This method will return any type of data except string

**getNotBool()**  This method will return any type of data except bool

**getNotFloat()**  This method will return any type of data except float

I need these methods in my tests. I never contribute to such a big project like zendframework so I need to know are these methods will accepted by comunity?

**Comment by adamlundrigan** [comment]
Best left to userland implementation.  @Maks3w I would close this.
