### ISSUE TITLE
Input getValue() returns null for Zend\Form\Element\Select types inside Callback validator

### ISSUE THREAD

**Issue by codemagician** [zendframework/zf2#4041]
In my code example below, I am attempting to attach a Callback validator to particular Input's on the InputFilter.

My ultimate purpose is to disable some Input validators dynamically based on the value of another form item.

When reservationType is set to 'daycare' I'd like validation to happen for 'checkInDaycare' but not for 'checkIn' or 'checkOut'.

When reservationType is set to 'standard' I'd like validation to happen for 'checkIn' and 'checkOut' and not for 'checkInDaycare'.

My plan was to inspect the value of $reservationType->getValue() and compare to 'standard' or 'daycare'.  The corresponding Form has an element called 'reservationType' which is of 'type' => 'select' which defines these values:

// snipet from the corresponding Form
        $this->add(array(
            'name' => 'reservationType',
            'type' => 'select',
            'options' => array(
                'label' => 'Type of reservation',
                'value_options' => array(
                    'standard' => 'Standard Reservation',
                    'daycare' => 'Daycare'
                )
            )
        ));

Inside the checkInDaycare Callback closure function (2nd in the example code below). the var_dump($reservationType->getValue()) displays null.

If I alter the Form's element type from 'type' => 'select' to 'type' => 'text' then value entered in the box appears in the var_dump($reservationType->getValue()) output, so there appears to be an issue with getting values from Select Inputs.

I'm not even sure if the code below is acceptable, since the Callback's might be firing in a unpredictable order- this might be why getValue() returns expected values for Text elements but not for Select elements?  Perhaps the $reservationType Input hasn't yet been evaluated when the Callback triggers?

class ReservationInputFilter extends InputFilter
{
    public function __construct()
    {
        $reservationType = new Input('reservationType');
        $checkIn         = new Input('checkIn');
        $checkOut        = new Input('checkOut');
        $checkInDaycare  = new Input('checkInDaycare');
 
        $reservationType->setRequired(true);
        $reservationType->getValidatorChain()->attach(new NotEmpty(array(
            'messages' => array('isEmpty' => 'Please select a reservation type')
        )))->attach(new Callback(function ($value) use ($reservationType) {
            var_dump($reservationType);
            var_dump($value);
        }));
        $this->add($reservationType);
 
        // checkInDaycare
        $checkInDaycare->setRequired(true);
        $checkInDaycare->getFilterChain()
                       ->attach(new StringTrim());
        $checkInDaycare->getValidatorChain()
                       ->attach(new NotEmpty(NotEmpty::NULL))
                       ->attach(new Callback(function ($value) use ($reservationType) {
                            var_dump($reservationType->getValue());
                            var_dump($value);
                            return $value;
                       }));
        $this->add($checkInDaycare);

**Comment by adamlundrigan** [comment]
The Callback validator has an additional parameter `$context` that will pass the validation context containing field values. 

@Maks3w this can be closed
