### ISSUE TITLE
Allowing the translation of the legend of the fieldset in the render function in the FormCollection Helper.

### ISSUE THREAD

**Issue by sarahman** [zendframework/zf2#4071]
In the render function of the Zend/Form/View/Helper/FormCollection, the legend of the fieldset is not being translating.

I think, the code snippet should be like this---

// Every collection is wrapped by a fieldset if needed
if ($this->shouldWrap) {
    $label = $element->getLabel();

    if (!empty($label)) {
        $label = $escapeHtmlHelper($label);
        if (($translator = $this->getTranslator()) !== null) {
            $label = $translator->translate(
                $label, $this->getTranslatorTextDomain()
            );
        }

        $markup = sprintf(
            '<fieldset><legend>%s</legend>%s</fieldset>',
            $label,
            $markup
        );
    }
}

No what do you think? I have faced this problem while working with the translation. Please suggest me if you have any.

Thank You.

**Comment by adamlundrigan** [comment]
This was added in #3532
