### ISSUE TITLE
InjectTemplateListener::injectTemplate() ignored 'multi-depth' in controller namespace

### ISSUE THREAD

**Issue by Freeaqingme** [zendframework/zf2#4080]
In Zend\Mvc\View\Http\InjectTemplateListener::injectTempate() the view script that needs to be used is tried to deduce. The problem I have is that my Controller is named MyApp\Something\Controller\IndexController.

The template I would expect the indexAction() method to be resolved to is myapp/something/index/index. However, the result I'm currently getting is: myapp/index/index. This is particularly frustrating because I also have a MyApp\Controller\IndexController ;)

I think the actual fix could potentially be applied in either the injectTemplate() method, or the inflectName() method (if it can be fixed at all...)

**Comment by adamlundrigan** [comment]
Can this be closed now given that #5670 has been merged and documented?
