### ISSUE TITLE
Zend\Mvc\Controller\Plugin\Forward::reattachProblemListeners

### ISSUE THREAD

**Issue by turrsis** [zendframework/zf2#4130]
When controller->dispatch throw Exception Forward::reattachProblemListeners will never executed.
And SharedEventManager will never restore self state

**Comment by adamlundrigan** [comment]
This issue does still exist in the ZF2 codebase.  What's the practical consequence of it?  If I've grokked this part of the MVC stack properly it means that if the controller making the forward call swallows the exception and returns an array from the action it won't be converted to a ViewModel automatically (https://github.com/zendframework/zend-mvc/blob/master/src/Controller/Plugin/Forward.php#L85).  I don't see a way for userland applications to inject their own listeners into the problem list, and that's the only listener on the list.  That said, it is wrong and should be fixed if it's not considered a BC break (which it doesn't to me)

**Comment by turrsis** [comment]
this is very old issue, not actual
