### ISSUE TITLE
[Form] annotation conflict with doctrine

### ISSUE THREAD

**Issue by cemborek** [zendframework/zf2#4197]
/**
     * @Annotation\Type("Zend\Form\Element\Select")
     * @Annotation\Options({"label":"Carc"})
     * @Annotation\Attributes({"type":"select","options":{"1":"Visa","2":"Maestro"}})
     * @ORM\Column(name="card" type="text", length=1, nullable=false, options={"default" = 0})
     */

Withouth ORM annotation element that is created is Zend\Form\Element\Select
after adding last one for type="text" is created Zend\Form\Element, for type="boolean" is created Zend\Form\Element\Checkbox.

@Annotation\Type is ingnored

**Comment by adamlundrigan** [comment]
@Maks3w this has been fixed in the referenced issue and can be closed
