### ISSUE TITLE
Feedback about EventManager integration in Zend\Form

### ISSUE THREAD

**Issue by iquabius** [zendframework/zf2#4228]
I'm trying to implement an `EventManager` integration in `Zend\Form`, and I have some questions regarding this:

#### 1. Composing the `EventManager`

I don't know which is the best class to compose the `EventManager`. I was thinking about creating a `Zend\Form\FormManager` class that would compose the `EventManager`, `FormElementManager`, `FormObjectManager` (if introduced by this PR), `FormFactory`, etc. This class could be something like [`Zend\Mvc\View\Http\ViewManager`](https://github.com/zendframework/zf2/blob/develop/library/Zend/Mvc/View/Http/ViewManager.php). IMO this makes more sense than composing the `EventManager` in `Zend\Form\Factory` or `FormElementManager`, and it would manage anything related to `Zend\Form`. With this approach some things could be done:
   * Deprecate `Zend\Mvc\Service\FormElementManagerFactory` and implement `Zend\Mvc\Service\FormManagerFactory` - `FormElementManager` should be accessed via `FormManager`.
   * Deprecate `FormFactoryAwareInterface` implementation in `Zend\Form\Fieldset` and implement a `FormManagerAwareInterface` (IMO it should be implemented in `Zend\Form\Element` so the elements can have access to `FormManager` as well).

#### 2. About `EventManager` Integration

The idea came from the need to execute some things before *validating* a form or *preparing* it for rendering.

##### Use case:

```PHP
// In a 'product' fieldset
$this->add(array(
    'name' => 'isSale',
    'type' => 'Checkbox',
));

$this->add(array(
    'name' => 'salePrice',
    'events' => array( // array of events to be attached to the EventManager
        array(
            'event'    => 'validate', // Would be triggered when isValid() gets called
            'callback' => function ($e) {
                $form = $e->getForm();

                // If 'isSale' is NOT checked 'salePrice' should not be requiered
                if (!$form->get('product')->get('isSale')->isChecked()) {
                    $form->getInputFilter()->get('product')->get('salePrice')->setRequired(false);
                }
            },
            'priority' => 25,
        ),
        array(
            'event'    => 'prepare', // Would be triggered when prepare() gets called
            'callback' => function ($e) {
                $form = $e->getForm();

                if (!$form->get('product')->get('isSale')->isChecked()) {
                    // This could be done in the 'validate' event, but it's here just for demonstration
                    $form->get('product')->get('salePrice')->setAttribute('disabled', 'disabled');
                }
            },
            'priority' => 25,
        ),
    ),
));
```

#### 3. Deprecating `form_elements` and `getFormElementConfig()`

see #3932 and #4100

Would it be too harsh to deprecate `form_elements` key and `getFormElementConfig()` method?

Adding a `ModuleManager` listener is a good idea, it could accomplish something like this:

```PHP
/* in a config file */
return array(
    /* I think this array structure is better than the one introduced by #3932 */
    'form_manager' => array(
        /* Different from @stephanoff example in #4100 */
        'forms'                 => array(),
        'element_manager'       => array(),
        'object_manager'        => array(),
        'event_manager_enabled' => true, // This would be needed if the integration should be optional

        /* If we add some new feature that needs configuration, we'd reserve a key for it here */
    ),
    /* ... */
);
```
Or in the `Module` class:

```PHP
public function getFormConfig()
{
    return array(
        'forms'           => array(),
        'element_manager' => array(),
        'object_manager'  => array(),
        /* ... */
    );
}
```

#### So...

Give me some feedback about this idea, is it good? is it crazy?

I can send a PR when I solve the composing issue - In the case of implementing `FormManager` I would do this first in a separeted PR.

@weierophinney, @bakura10 ping

**Comment by adamlundrigan** [comment]
Integrating the event manager into the next version of Zend\Form is covered in #5443 so I'll close this issue.
