### ISSUE TITLE
Zend\View\Renderer\PhpRenderer properties unaccessable

### ISSUE THREAD

**Issue by h3lpd3sk** [zendframework/zf2#4385]
For a recursive render I'd ideally need the current template from the PhpRenderer.
However there's no method for accessing the __template property. 
Since it's private even there's no point in extending the PhpRenderer either.

Think this and perhaps other properties should be accessible through methods or overloading.

Not sure what the philosophy behind this is, sure there's one I might be overlooking?

Work around with ReflectionObject isn't really a good solution but possible...

```php
//.phtml
$reflection = new ReflectionObject($this);
$property = $reflection->getProperty('__template');
$property->setAccessible(true);
$template = $property->getValue($this);
```

**Comment by adamlundrigan** [comment]
It's not exactly succinct but this will allow you to retrieve the name of the template being rendered: 

```php
$this->viewModel()->getCurrent()->getTemplate()
```

If you use it a lot you could add a custom view helper to wrap this under a shorter name (eg: `currentTemplateName`)
