### ISSUE TITLE
Form\Collection: allow remove all objects

### ISSUE THREAD

**Issue by thestanislav** [zendframework/zf2#4492]
There is no way to remove all objects from collection at this time. According to the logic I need to pass an empty array to Zend\Form\Element\Collection::populateValues. But empty arrays are ignored https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Element/Collection.php#L185

The next possible upcoming issue is that there is not way to create the html element in view script that would generate an empty array. May be some type conversion should be implemented to handle this.

**Comment by svycka** [comment]
fixed with https://github.com/zendframework/zend-form/pull/14
