### ISSUE TITLE
Zend\Validator\File\Upload

### ISSUE THREAD

**Issue by isimonov** [zendframework/zf2#4554]
For any reason in attempt to load the file through <inpyt type="file" name="files"> Zend\Validator\File\Upload issues the message that the file isn't found (fileUploadErrorFileNotFound) if to rename attribute name="files" into anything another (for example name="file") everything perfectly works, validator doesn't return mistakes. I couldn't understand where exactly a mistake, but it takes place to be.

**Comment by adamlundrigan** [comment]
@Maks3w looks like this can be closed
