### ISSUE TITLE
[3.0] Consistency in the naming of service managers

### ISSUE THREAD

**Issue by macnibblet** [zendframework/zf2#4565]
Current we have the ```service_manager``` but if we look at all the other services in the file below we will notice it does not follow the same principle as the rest of them. It's logical name would be ```services```
https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Service/ModuleManagerFactory.php#L48

And the same goes for the ```ControllerLoader``` which should be named ```ControllerManager```
https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Service/ModuleManagerFactory.php#L53

**Comment by samsonasik** [comment]
I created PR https://github.com/zendframework/zend-mvc/pull/6 for changing ControllerLoader to ControllerManager.
