### ISSUE TITLE
Zend\Mvc\Service\FilterManagerFactory: Add peering service manager to the plugins

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zf2#4573]
https://github.com/zendframework/zf2/blob/develop/library/Zend/Mvc/Service/FilterManagerFactory.php#L27-L28

I think there should be
`$plugins->addPeeringServiceManager($serviceLocator);`
so the FilterManager service can get the filter via DI.

**Comment by adamlundrigan** [comment]
Is this still relevant?  The manager factories have been significantly refactored since this ticket was created.

**Comment by bacinsky** [comment]
This isn't important for me anymore. Thank you.
