### ISSUE TITLE
Not expected ZF2 session locking during AJAX calls

### ISSUE THREAD

**Issue by gecata83** [zendframework/zf2#4585]
The problem is that I'm making multiple ajax calls to a specific action on my system, these calls are making outer calls to a distant system and are waiting significant amount of time to complete and return results. On my system I am using ZF2 AuthenticationService for user authentication (saving the identity to the session). I browse trough the code and found out the different approach that ZF2 use to work with the session data,  I so how the SessionManager each time write into the $_SESSION without caring does this session data is changed or not. This writing into the session global makes the session locks. In my ajax requests I need to read the data from the session but when I try to getIdentity (access the session data) the Session locks and other ajax request that needs to run asynchronously stops to wait until the Seesion unlocks. Does ZF2 has a capability to workarround this issue? How? Thank's a lot

**Comment by adamlundrigan** [comment]
Is this still an issue?
