### ISSUE TITLE
FormSelect does not show label 

### ISSUE THREAD

**Issue by sandersjj** [zendframework/zf2#4827]
Hello,

I have created an element with the folowing annotations:

    /**
     * productGroupId -> Vis / Groente / Vlees enz.
     * @ORM\ManyToMany(targetEntity="productGroup")
     * @Annotation\Type("Zend\Form\Element\Select")
     * @Annotation\Options({"label":"Productgroup"})
     */
    protected $productGroup;

Then I show it in my form like:

`echo $this->formSelect('productGroup');`

The output is:

```
<select name="productGroup[]" multiple="multiple">
<option value="1">value1</option>
<option value="2">value2</option>
</select>
```

But the label is not rendered. I think this is a bug in the view renderer from fromSelect

--Update ---

`echo $this->formRow('productGroup', 'prepend'); `
Does show the label. Why should't it work by formSelect and formRadio?

**Comment by adamlundrigan** [comment]
As @grizzm0 said, ZF2 split the three concerns (element, label and errors) into separate helpers and provided formRow as a shortcut to render all three together.  So, formSelect will only render the select element; you'd need to call formLabel separately to render it's label:

```php
$element = $form->get('my_element');
echo $this->formLabel($element);
echo $this->formSelect($element);
echo $this->formErrors($element);
```

If you want to wrap the label around the element you can call `openTag` and `closeTag` on the formLabel helper separately to render the open/close separately. 

@Maks3w this can be closed
