### ISSUE TITLE
controllermap_generator.php

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zf2#4867]
Hello together,

there is a classmap, templatemap and pluginmap generator.

Wouldn't that also be cool for the controllers/invokables?
Just defining the default path (as fallback) like for views and then load the generated map.

It would lower again the boilerplate code and wouldn't impact performance very much.

I found out, you could "fake" something similar in Module.php::getControllerConfig(), but i think it's wrong to do it so.

More native is the view/autoload way with a map and a fallback...

```php
    'view_manager' => array(
         'template_map' => array(
            'template_map' => include __DIR__ . '/../template_map.php'
        ),
        
        'template_path_stack' => array(
            'LispSearch' => __DIR__ . '/../view'
        )
    )
```

**Comment by adamlundrigan** [comment]
What's the gain in adding this?  Unlike templates and plugins the controller mappings should always be explicit already -- it's a Service Manager configuration array (http://framework.zend.com/manual/current/en/modules/zend.mvc.services.html#default-configuration-options) that maps controller keys to an invokable or factory.  You can do that via configuration files (module config or config/autoload) or via Module#getControllerConfig.

**Comment by ThaDafinser** [comment]
For me it's solved with: https://github.com/Ocramius/OcraCachedViewResolver
