### ISSUE TITLE
Zend\Mvc\Router\Http\Chain::assemble calls key on PriorityList

### ISSUE THREAD

**Issue by abstractionnl** [zendframework/zf2#4936]
On line 159 of Zend/Mvc/Router/Http/Chain.php:
```php
$lastRouteKey = key($this->routes);
```

This returns something like: "\u0000*\u0000sorted" on my system (PHP 5.4)

This fails the test on line 168:

```php
$chainOptions['has_child'] = ($hasChild || $key !== $lastRouteKey);
```

As key is a numeral value.

A fix would be to replace it with:

```php
$routes = ArrayUtils::iteratorToArray($this->routes);
end($routes);
$lastRouteKey = key($routes);
```

**Comment by kusmierz** [comment]
@weierophinney Could you look at this?

**Comment by kusmierz** [comment]
@DASPRiD What's more - it has been never worked:

http://3v4l.org/ITfVZ
