### ISSUE TITLE
SessionContainer not working as expected in 5.3.3

### ISSUE THREAD

**Issue by intellix** [zendframework/zf2#4945]
Had a piece of code, that worked on 5.3.25 but when I uploaded it to somewhere with 5.3.3 I had unexpected results. I see that SessionContainer has a 5.3.4+ wrapper to fix an issue with references. Tried using it for 5.3.3 as well but an error was thrown.

Code, inside public/test.php

```php
chdir(dirname(__DIR__));
include 'init_autoloader.php';

$session  = new Zend\Session\Container;

if (!isset($session->storage->test)) {
    $session->storage = new stdClass;
    $session->storage->test = 'test';
}

var_dump($session->storage);
```

5.3.25: 
```php
object(stdClass)[7]
  public 'test' => string 'test' (length=4)
```

5.3.3: 
```php
object(stdClass)#11 (0) { }
```

5.4.16: 
```php
object(stdClass)[7]
  public 'test' => string 'test' (length=4)
```

**Comment by adamlundrigan** [comment]
@mwillbanks this one can be closed
