### ISSUE TITLE
PartialLoop, Entities and HydratingResultSet

### ISSUE THREAD

**Issue by aaronweatherall** [zendframework/zf2#4958]
Hey Team,

I'm having an issue and I'm not sure if it's a bug or a feature (which is rather annoying). Essentially I'm using HydratingResultSet to iterate through some database output and returning this to my view to be iterated through.

Generally, I'd foreach over this and be able to call the entity methods such as $this->getFirstName() to get the users name.

However, I thought to save some code I'd use a partialLoop.

Essentially partialLoop converts the output to an array using iterator_to_array (that's fine) but then flattens by entity object which changes my key cases.

Here's the iterator_to_array item as I'd expect it. (shortened for example)

```
[0]=>
  object(Users\Entity\Users)#295 (17) {
    ["firstName":protected]=>
    "Aaron"
    ["lastName":protected]=>
    "Test"
  }
```

Now, after passing $users to partialLoop

```
<?= $this->partialLoop ('partial\user-row', $users) ?>
```

We get the following in the loop
```
object(Zend\View\Variables)#301 (2) {
  ["strictVars":protected]=>
  bool(false)
  ["storage":"ArrayObject":private]=>
  array(17) {
    ["first_name"]=>
    "Aaron"
    ["last_name"]=>
    "Test"
  }
}
```

**Comment by adamlundrigan** [comment]
It sounds like you were using ClassMethods hydrator with HydratingResultSet; the default behaviour of that hydrator is to convert camel-case to underscore-separated (https://github.com/zendframework/zend-hydrator/blob/master/src/ClassMethods.php#L49).

@Maks3w this can be closed
