### ISSUE TITLE
DateTime form element weird DateInterval step!?

### ISSUE THREAD

**Issue by TonyBogdanov** [zendframework/zf2#4960]
Can someone explain what is the reason behind setting the DateInterval step to a minute instead of a second or even a millisecond in https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Element/DateTime.php#L172 ?

Better, can someone explain why the DateTime element should have a DateStep validator at all?

My problem here, is that with minimal setup, one can never submit a datetime value with seconds != 0, because the step is set to a minute. It just goes into an infinite validation loop.

**Comment by kamioftea** [comment]
The problem with the validation is not infinite, but the validator starts at the base date (which is 1/1/1970 if no min attribute is set) and increments by the step until it reaches or passes the submitted datetime which takes enough time that the script times out. I've created a pull request to help improve this here: [https://github.com/zendframework/zf2/pull/7110]

To get round the step validation entirely you can set a step attribute of 'any' to prevent the DateStep validator being added.

The default step is 60 seconds for a datetime element [WHATWG Spec](https://html.spec.whatwg.org/multipage/forms.html#date-and-time-state-%28type=datetime%29) (There is no datetime element in the W3C spec anymore but time also matches this [W3C Time Spec](http://www.w3.org/TR/html5/forms.html#time-state-%28type=time%29). This suggests that the default should really by a DateStep with a `DateInterval('PT60S')`.

There is an unfortunate side affect of changing the default date interval in that it will no longer be caught by the quicker check that only applies when there is a single interval unit with value 1, so will start to use the longer validation.

**Comment by Ocramius** [comment]
Handled in #7110
