### ISSUE TITLE
Template Not found didn't trigger MvcEvent::EVENT_RENDER_ERROR

### ISSUE THREAD

**Issue by sachitsac** [zendframework/zf2#4986]
Zend Framework Version: 2.2.2
PHP Version:

PHP 5.4.9-4ubuntu2.2 (cli) (built: Jul 15 2013 18:23:35) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies

Issue:
    I created an Index controller for Application Module. Didn't create an application/index/index.phtml file. I expected it to throw MvcEvent::EVENT_RENDER_ERROR event. I attached a listener to that event in anticipation of catching it and doing something useful for development. It produces a warning in php error logs but did not trigger the MvcEvent::EVENT_RENDER_ERROR. I looked at Zend\View\Renderer\PhpRenderer.php line 507 where the warning was being produced, include $this->__file; so its for some reason passing all other validations (even thought the file does not exist). I added this before line 507:

```php    
    echo "File {$this->__file}" . (!is_file($this->__file) ? ' does not exist' : ' exists') . "<br>";    
    result: 
        File /home/sachitsac/app/module/Application/config/../view/application/index/index.phtml does not exist
        File /home/sachitsac/app/module/Application/config/../view/layout/layout.phtml exists
```
And then i tried the following to throw the exception:
```php
    if (!is_file($this->__file)) {
        throw new Exception\RuntimeException(sprintf(
            '%s: Unable to render template "%s"; file not found on disk',
            __METHOD__,
            $this->__template
        ));
    }
```                
and this seems to produce the exception. I know its probably not the right place but i was just trying to trigger the MvcEvent::EVENT_RENDER_ERROR. Am i missing something or is this an issue with the Resolver ??

Thanks for your help.

**Comment by adamlundrigan** [comment]
I believe this has been resolved at some past point in time ([possibly here](https://github.com/zendframework/zend-view/commit/091bc1defbbc6c78c03dd5ef72b4fa782d96e258)).  PhpRenderer throws an exception [if the file isn't found](https://github.com/zendframework/zend-view/blob/67c6ed99b9e6f78102a2220c7134cb0e3968f6b1/src/Renderer/PhpRenderer.php#L493-L497) or [if including it fails](https://github.com/zendframework/zend-view/blob/67c6ed99b9e6f78102a2220c7134cb0e3968f6b1/src/Renderer/PhpRenderer.php#L508-L512), and [DefaultRenderingStrategy catches that exception and emits an EVENT_RENDERER_ERROR event](https://github.com/zendframework/zend-mvc/blob/ef56cf348a277a05b95e56d0bedf4d350028a29c/src/View/Http/DefaultRenderingStrategy.php#L113)
