### ISSUE TITLE
[WIP][ ZF3 ] duplicate EVM in Zephir

### ISSUE THREAD

**Issue by macnibblet** [zendframework/zf2#5036]
So first of i want to say dam you @bakura10 for creating so many awesome PR i feel i need to do something...

So the idea grew a bit in the #zfalk.dev channel today about the performance of various components e.g ServiceManger, EventManager and Stdlib. And how we could increase the performance of these components. Something we realised is that many of the components are rather stable/mature. So maintaining the code **shouldn't** be too much of a hasel to maintain either (Famous last words). 

So my idea is to start writing the EventManager in Zephir first to see how much of a performance boost we get and see what issues are with using it.

**Comment by Maks3w** [comment]
EVM v3 is merged on component branch. If you want open a discussion about apply Zephir please reopen on the component issue tracker.
