### ISSUE TITLE
when use form inputFilter getMessages return empty

### ISSUE THREAD

**Issue by wohugb** [zendframework/zf2#5164]
If there have not riquried elments,when required elements are ok, $form->isValid() return false,but $form->getMessages() return empty!

**Comment by adamlundrigan** [comment]
Duplicate of #4017.  See [this comment](https://github.com/zendframework/zf2/issues/4017#issuecomment-149965663) over there for rationale of why it's closed as not an issue. 

@Maks3w this can be closed
