### ISSUE TITLE
[ZF3] [Debate] Remove ServiceLocatorAwareInterface from AbstractController

### ISSUE THREAD

**Issue by macnibblet** [zendframework/zf2#5168]
Heya people

After a rather interesting discussion in #5156 many people tend to agree that having the ```AbstractController``` implement the ```ServiceLocatorAwareInterface``` is a bad idea since it allows for poor practise. 

Yes, it can be convenient at times but it's used far too carelessly. Removing the ```ServiceLocatorAwareInterface``` we can "enforce" better practise among our users ?

**Comment by Maks3w** [comment]
Those interfaces not longer exists on SM v3
