### ISSUE TITLE
Zend\ServiceManager\ServiceManager::canCreateFromAbstractFactory shoud be protected

### ISSUE THREAD

**Issue by turrsis** [zendframework/zf2#5294]
ServiceManager::canCreateFromAbstractFactory shoud be protected, because we must use ServiceManager::has method and ServiceManager::createFromAbstractFactory is protected

**Comment by adamlundrigan** [comment]
Service Manager is being heavily refactored for ZF3 so I suspect this may no longer be relevant /cc @bakura10

**Comment by Maks3w** [comment]
Only desired API is public on SM v3
