### ISSUE TITLE
Zend/InputFilter/Input.php merge function overrides settings for allow_empty

### ISSUE THREAD

**Issue by fimbulvetr** [zendframework/zf2#5315]
Using a form that leverages attachInputFilterDefaults (Zend\Form\Form.php), with a nested fieldset, attachInputFilterDefaults will iterate through each fieldsets elements and   grab each element's getInputSpecification, if available.

If the fieldset had a filter specification available via getInputFilterSpecification, the field already has an InputFilter\Input specified, so ZF will have already added the field via the getInputFilterSpecification method.

The problem lies in that the fieldset getInputFilterSpecification has specified, say allow_empty => true and required => true, and then element itself provides the same (allow_empty => true and required => true), then during attachInputFilterDefaults the call is made to get the element's specification, and add it to the inputfilter.

The inputfilter sees that the field already exisits, BaseInputFilter.php:75, so it instead merges the input with the already exisiting specification.

InputFilter/Input.php:278, merge(), will take the incoming allowEmpty and set it to true (line 280), then a bit later set the required to true (line 285), which paradoxically sets allowEmpty to the opposite of required (false).

To fix, either the assumption "allow empty is the inverse of required" has to be removed, or perhaps the merge function should set allow_empty AFTER it has set the required.

See https://github.com/zendframework/zf2/commit/f61d3dc5fe088abc7a877b8f449a6c4b73fcb628 for the history.

**Comment by Maks3w** [comment]
This was already fixed on #7448
