### ISSUE TITLE
Bad validation in Zend\InputFilter\InputFilter when allowEmpty is set to false and using Boolean Filter.

### ISSUE THREAD

**Issue by edsonhoraciojunior** [zendframework/zf2#5473]
The situation below make isValid return false:

$input = new Input('testInput');
$input->setRequired(false);
$input->setAllowEmpty(false);

$input->getFilterChain()->attach(new Filter\Boolean());

$inputFilter = new InputFilter();
$inputFilter->add($input);

$inputFilter->setData(array('testInput' => false));

$isValid = $inputFilter->isValid();           // false
$values = $inputFilter->getValues();      // testInput is false
$error    = $inputFilter->getMessages(); // prints isEmpty error message

The same thing happens if i send 0 instead of false.

This should validate to true as the input is not empty.

**Comment by Maks3w** [comment]
Duplicate https://github.com/zendframework/zend-validator/issues/37
