### ISSUE TITLE
bindValues in Element\Collection with unknown element

### ISSUE THREAD

**Issue by guilherme-santos** [zendframework/zf2#5492]
Hi,
In Element\Collection if my form has some fields that don't have matching element give an error in line 273.
I suggest add protection like Zend\Form\Fieldset line 527-529
To avoid an exception.

Thanks!

**Comment by adamlundrigan** [comment]
If this is still an issue please open a new ticket on the [zend-form repository](https://github.com/zendframework/zend-form) with more detail on how to reproduce the issue.
