### ISSUE TITLE
ViewHelper "MvcTranslator" translator

### ISSUE THREAD

**Issue by Mech7** [zendframework/zf2#5501]
It seems now in my plugin there is: $helper->setTranslator($locator->get('MvcTranslator'));  injected instead
$helper->setTranslator($locator->get('translator'));

I cannot see it being setup in my config, i see in the changelog the preference has been changed: https://github.com/zendframework/zf2/issues/4870 but now i get a different translator object in my view plugins where it previously used: $helper->setTranslator($locator->get('translator'));

If I comment out: Zend\Mvc\Service\ServiceListenerFactory
```php
//'MvcTranslator'                  => 'Zend\Mvc\Service\TranslatorServiceFactory',
```
It works again normally, I don't see MvcTranslator defined anywhere in my module config, it seems the serviceLocator always has the mvctranslator without my locale set on 'translator' in the serviceLocator.

What is also strange that i see in ValidatorPluginManager only MvcTranslator is checked.

```php
if ($locator && $locator->has('MvcTranslator')) {
    $validator->setTranslator($locator->get('MvcTranslator'));
}
```
Should this not provide a fallback also?

edit-----
I now see that there already is an alias, I tried to solve it by:
```php
'aliases' => array(
    'translator' => 'MvcTranslator',
),
```
But then it throws an exceptions: "'An alias by the name "translator" or "translator" already exists'"
If I remove the factory:
"//'translator' => 'Zend\I18n\Translator\TranslatorServiceFactory',"
It seems to work.

**Comment by samsonasik** [comment]
@Mech7 @Ocramius @DASPRiD I think it can be closed now as now handled by 'MvcTranslator' handled by  'Zend\Mvc\Service\TranslatorServiceFactory' for skeleton app usage.
