### ISSUE TITLE
[ZF3] Standardize the exception thrown by plugin manager though out the project

### ISSUE THREAD

**Issue by macnibblet** [zendframework/zf2#5541]
Different plugin managers throw different exceptions on the same kind of fault. Should this not be standardised ?

I would either suggest ```Exception\InvalidPluginException``` or ```Exception\InvalidArgumentException``` Preferably the last since it does not matter what you are referring to (Writer, View Helper, Contorller Plugin, Adapter)

**Comment by Maks3w** [comment]
ServiceManager v3 standarize the allowed exceptions for each method on the interface docblock.
