### ISSUE TITLE
Zend\Mail\Header\ContentType generates notice if "Content-Type" has a trailing semicolon

### ISSUE THREAD

**Issue by flamegod** [zendframework/zf2#5734]
Some messages do have a trailing semicolon in the Content-Type header. The trailing semicolon shouldn't be there but Zend\Mail\Header\ContentType should be more tolerant to malformed headers. I haven't found any possible workaround. 

Examples:

Content-Type: text/plain; charset=UTF-8;
Content-Type: message/delivery-status; charset=UTF-8;

It generates: 

Notice: Undefined offset: 1 in ...\Zend\Mail\Header\ContentType.php on line 45

**Comment by adamlundrigan** [comment]
This was fixed in #6491.  /cc @Maks3w
