### ISSUE TITLE
URIEncoded / interpreted as /

### ISSUE THREAD

**Issue by lasimon** [zendframework/zf2#5760]
Version 2.2.5

Browser sends request URL: http://wgc.local/public/dbsepisodes/n%2Fa
Zend2 responds with: "The requested URL /public/dbsepisodes/n/a was not found on this server." rather than passing "n/a" to the (AbstractRestful) Controller as $id.

**Comment by samsonasik** [comment]
@Ocramius @lasimon I think it can be closed in favor of #5790 discussion
