### ISSUE TITLE
Question: ZendTest remove @group or complete it?

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zf2#6040]
Some test do have a `@group` docblock for running test only for one component and some doesnt

Either
- Complete it?
- Remove it?

Examples:
https://github.com/zendframework/zf2/blob/master/tests/ZendTest/Http/CookiesTest.php
https://github.com/zendframework/zf2/blob/master/tests/ZendTest/Authentication/AuthenticationServiceTest.php#L15-L17

i'm `+1 for complete it`

**Comment by Maks3w** [comment]
In resume:

- `@group` optional used for track the original issue number
- `@covers` is currently be added at class level for prevent those fake coverages.
