### ISSUE TITLE
MutableCreationOptionsAwareTrait for convenient usage of MutableCreationOptionsInterface

### ISSUE THREAD

**Issue by demichl68** [zendframework/zf2#6174]
As we have the MutableCreationOptionsInterface, IMO we should also have a 
MutableCreationOptionsAwareTrait.

I see myself and other developers in my team constantly writing the same kind of "boilerplate" code over and over again. A trait would come in quite handy

**Comment by samsonasik** [comment]
@Ocramius @demichl68 I think it can be closed in favor of #6175

**Comment by Ocramius** [comment]
@samsonasik closed, thanks!
