### ISSUE TITLE
PHPUnit Exceptions are catched from ZF2

### ISSUE THREAD

**Issue by andreashager** [zendframework/zf2#6206]
I use Zend Framework 2.3.1 and Unit-Tests from the Commandline. If I now run my Unit-Tests and an Exception is thrown the `\Zend\Mvc\DispatchListener` catches the exception and translates it to a application error.

Line 113-15
```
try {
    $return = $controller->dispatch($request, $response);
} catch (\Exception $ex) {
```

The problem is the output in the command line is shown:
```
1) PersonnelTest\Controller\TimeTrackingControllerTest::testIndexActionCanSubmitFormWithValidData
Failed asserting response code "302", actual status code is "500"

.../src/vendor/zendframework/zendframework/library/Zend/Test/PHPUnit/Controller/AbstractControllerTestCase.php:415
.../src/module/Personnel/tests/PersonnelTest/Controller/TimeTrackingControllerTest.php:280
```

If I want to know which error exactly occoured I have to do `var_dump($this->getResponse()->getContent());` and see which exception was thrown. Since the last update this behaviour was not there and the exception was caught by PHPUnit and something similar was shown in the command line.

```
1) PersonnelTest\Controller\TimeTrackingControllerTest::testIndexActionCanSubmitFormWithValidData Expectation failed for method name is equal to <string:mc_issue_get> when invoked 1 time(s)
Parameter 2 for invocation Zend\Soap\Client::mc_issue_get('1024') does not match expected value.
Failed asserting that '1024' matches expected 1234.
```
Maybe it is good to catch PHPUnit Exceptions before and rethrow them?

**Comment by ARoddis** [comment]
Still happening because PHPUNIT only throws Exceptions of tearDownMethods, if an execption in the testMethod is thrown. But thats not the case because the framework (zf2) catches it and puts it into the mvcEvent and returns 500.

```php

        // Tear down the fixture. An exception raised in tearDown() will be
        // caught and passed on when no exception was raised before.
        try {
            if ($hasMetRequirements) {
                foreach ($hookMethods['after'] as $method) {
                    $this->$method();
                }

                if ($this->inIsolation) {
                    foreach ($hookMethods['afterClass'] as $method) {
                        $this->$method();
                    }
                }
            }
        } catch (Throwable $_e) {
            if (!isset($e)) {
                $e = $_e;
            }
        } catch (Exception $_e) {
            if (!isset($e)) {
                $e = $_e;
            }
        }

```

**Comment by SilverioMiranda** [comment]
@Ocramius Hi, i have the same problem presented in this thread

Example: 

 ```
public function exampleAction()
    {
        throw new \Exception('x');
...
}
```


```
 public function testAdicionarAguaJaAdicionadaError()
    {
      
        $this->expectExceptionMessage('x');

        $this->dispatch("/example", 'GET');
        
      //  $this->assertApplicationException(\Exception::class,'x');
        
```

If i use expectExceptionMessage the test will fail, saying that no exception is thrown.
Otherwise if i use assertApplicationException the test will success

Any idea? Thx

**Comment by Ocramius** [comment]
@SilverioMiranda please open a new issue with a test case
