### ISSUE TITLE
[Zend\I18n] php.ini setting "intl.use_exceptions" on true

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zf2#6312]
When using `intl.use_exceptions` as `true` following validator will fail hard with the exception from the intl component:
* DateTime
* Float
* Int

Possible solutions:
* let it be like it is today (maybe this setting nobody used expect me?)
* try/catch block in addition to the `intl_is_failure()` check
* change php.ini setting always to false during validation and change it back after the check

Note: This feature was introduced with PHP 5.5
http://www.php.net/manual/en/class.intlexception.php

**Comment by Ocramius** [comment]
Handled in #6598
