### ISSUE TITLE
Can't inherit abstract function Zend\Validator\Translator\TranslatorInterface::translate()

### ISSUE THREAD

**Issue by sumityadav** [zendframework/zf2#6345]
I found this issue when I was working on http://zf2.readthedocs.org/en/latest/tutorials/unittesting.html 
```
PHP Fatal error:  Can't inherit abstract function Zend\Validator\Translator\TranslatorInterface::translate() (previously declared abstract in Zend\I18n\Translator\TranslatorInterface) in zendframework\library\Zend\Mvc\I18n\Translator.php on line 19
```

OS: Windows 7
PHP: PHP 5.4.12 (cli) (built: Feb 25 2013 00:29:22)
ZF2 Version: 2.3.1

This seem to have happened before in #5354 but it doesn't seem to have fixed or may have come again?

**Comment by Maks3w** [comment]
Component now requires PHP >= 5.5 so this should be fixed
