### ISSUE TITLE
No way to log parse errors using Logger

### ISSUE THREAD

**Issue by roelvanduijnhoven** [zendframework/zf2#6346]
I want to catch all errors that are generated by PHP when running my ZF2 app. Therefore I instantiate a stream in `public/index.php` and register it using both the `registerErrorHandler` and `registerFatalErrorShutdownFunction` methods. 

However parse errors seem to slip through as they are not caught by `registerErrorHandler`. 

To reproduce:

```php
$stream = @fopen('data/log/errors.log', 'a', false);
if (!$stream) {
    throw new Exception('Failed to open stream');
}

$logger = new Zend\Log\Logger;
$writer = new Zend\Log\Writer\Stream($stream);

$logger->addWriter($writer);

Zend\Log\Logger::registerErrorHandler($logger);
Zend\Log\Logger::registerFatalErrorShutdownFunction($logger);
```

An trigger a parse error somewhere. For example in a view file:
```php
Test <?ph echo 'Note the missing p in <?php'?>
```

**Comment by adamlundrigan** [comment]
This has since been implemented ([here](https://github.com/zendframework/zend-log/blob/83e73fe8e24f4f57a8a7c340f3ab199a51362c4f/src/Logger.php#L620-L632))
