### ISSUE TITLE
Session validators does not work

### ISSUE THREAD

**Issue by YDyachenko** [zendframework/zf2#6366]
Session validators attaching to ValidatorChain before session start. On attaching validator write metadata to session storage:
```php
    public function attach($event, $callback = null, $priority = 1)
    {
        $context = null;
        if ($callback instanceof Validator) {
            $context = $callback;
        } elseif (is_array($callback)) {
            $test = array_shift($callback);
            if ($test instanceof Validator) {
                $context = $test;
            }
            array_unshift($callback, $test);
        }
        if ($context instanceof Validator) {
            $data = $context->getData();
            $name = $context->getName();
            $this->getStorage()->setMetadata('_VALID', array($name => $data));
        }

        $listener = parent::attach($event, $callback, $priority);
        return $listener;
    }
```

After, when you call SessionManager::start(), session_start() override storage ($_SESSION) and validator's metadata become lost.

At first I thought that I improperly use validators. And i should attach validator after calling SessionManager::start(). But in documentation (http://framework.zend.com/manual/2.3/en/modules/zend.session.manager.html), code of SessionManagerFactory class (https://github.com/zendframework/zf2/blob/master/library/Zend/Session/Service/SessionManagerFactory.php#L117) and test file (https://github.com/zendframework/zf2/blob/master/tests/ZendTest/Session/SessionManagerTest.php#L510)  authors use this order.

**Comment by Martin-P** [comment]
@YDyachenko I created PR #7094 for this issue. Can you please check if it fixes the issue for you?

**Comment by YDyachenko** [comment]
@Martin-P your PR looks good for this issue. thnx

**Comment by weierophinney** [comment]
Fixed with ddbf43a (patch by @Ocramius used as it is backwards compatible with current versions).

**Comment by Martin-P** [comment]
Please reopen this: https://github.com/zendframework/zf2/pull/7094#issuecomment-69960592

**Comment by Martin-P** [comment]
@YDyachenko Another patch has been used to fix the issue. Can you please check if ZF 2.3.4 fixes the issue for you? I would like to know your opinion, because I am not sure it fixes the issue.

**Comment by YDyachenko** [comment]
@Martin-P yeah, i seen new patch. And yes, this patch fixes the issue. But it looks like temporary solution. I think what usage of session container before starting session (and after merging with session data) is a bad practice.
