### ISSUE TITLE
Error in Zend\Form\Element\Collection

### ISSUE THREAD

**Issue by googlle** [zendframework/zf2#6376]
When sending the form to the server with an expired time csrf 
Error occurs (1 or 2) 

1) If the data sent is less than 2 ("count" in Zend\Form\Element\Collection) 
There is an error "No element by the name of [1] found in form" 

2) If more than two ("count" in Zend\Form\Element\Collection) 
Data truncated to 2 

In the form I use Zend \ Form \ Element \ Collection 

And I set the default "count = 2"

**Comment by adamlundrigan** [comment]
@Ocramius I think it's safe to close this now
