### ISSUE TITLE
Zend\Form\Element\Collection not rendering with Doctrine OneToMany unid. with JoinTable

### ISSUE THREAD

**Issue by acaciovilela** [zendframework/zf2#6405]
I have an OneToMany unidirectional with Join Table relationship between Employee and EmployeeCommission, using a Zend\Form\Element\Collection but when I set "$commissions = new ArrayCollection();"  into "__construct()" of the Employee entity, the $form, lose the Collection fieldset, and it breaks to render. I already changed the relationship to OneToMany Bidirectional but happens the same. I'm not sure if it's an doctrine's issue, but i've tried it with other versions of ZF2 and doctrine and it keeps. I'm using ZF 2.3.1, doctrine-module and doctrine-orm-module 0.8.0. 

code following:

Employee entity:
```php
<?php

namespace Employee\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;


/**
 * @ORM\Entity(repositoryClass="Employee\Entity\Repository\Employee")
 * @ORM\Table(name="employee")
 */
class Employee {

    /**
     * @ORM\Id
     * @ORM\Column(name="employee_id", type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $employeeId;

    /**
     * @ORM\ManyToMany(targetEntity="Employee\Entity\EmployeeCommission", mappedBy="employee", cascade="all")
     * @ORM\JoinTable(name="employee_employee_commission",
     *      joinColumns={@ORM\JoinColumn(name="employee_id", referencedColumnName="employee_id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="employee_commission_id", referencedColumnName="employee_commission_id", unique=true)}
     * )
     */
    protected $commissions;

    public function __construct() {
        $this->commissions              = new ArrayCollection();
    }
    ... setter

    ... getter
}
```
EmployeeCommission entity:

```php
<?php

namespace Employee\Entity;

use Employee\Entity\Employee;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="employee_commission")
 */
class EmployeeCommission {

    /**
     * @ORM\Id
     * @ORM\Column(name="employee_commission_id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $employeeCommissionId;

    /**
     * @ORM\Column(name="employee_commission_fixed", type="decimal", precision=2)
     */
    protected $employeeCommissionFixed;

    /**
     * @ORM\Column(name="employee_commission_variant", type="decimal", precision=2)
     */
    protected $employeeCommissionVariant;
    
    /**
     * @ORM\OneToOne(targetEntity="Product\Entity\Product", cascade={"persist"})
     * @ORM\JoinColumn(name="product_id", referencedColumnName="product_id")
     */
    protected $product;
    
    public function __construct() {
        $this->employeeCommissionFixed = 0.00;
        $this->employeeCommissionVariant = 0.00;
    }
    
    ... setter
    ... getter
}
```

links for fieldsets and controller following:

Employee fieldset: http://pastebin.com/NbTZJLGK

EmployeeCommission fieldset: http://pastebin.com/VpDa0ziD

EmployeeController: http://pastebin.com/8P9GUyM8

**Comment by adamlundrigan** [comment]
Many-to-many with join table is poorly supported.  Doctrine ORM's manual suggests using a 3-class  one-to-many/many-to-one instead:

> Why are many-to-many associations less common? Because frequently you want to associate additional attributes with an association, in which case you introduce an association class. Consequently, the direct many-to-many association disappears and is replaced by one-to-many/many-to-one associations between the 3 participating classes.
