### ISSUE TITLE
Add option to Zend\Form\Element\Select to avoid explicit value attributes

### ISSUE THREAD

**Issue by hschletz** [zendframework/zf2#6453]
Sometimes it would come in handy to create simple select elements without explicit value attributes:

```
<select name="foo">
<option>bar</option>
<option>baz</option>
</select>
```

This is currently not supported by Zend\Form\Element\Select. The keys passed to setValueOptions() are always evaluated and used as the "value" attribute for each option.

If the form handler requires the real value instead of the artificial key, this can only be achieved by building a value options array with keys identical to the values. This is typically an extra step in the form generation process, and the HTML output gets needlessly messy.

It would be nice to have an option to ignore the keys and generate code in the short form.

**Comment by adamlundrigan** [comment]
Looks like there is no interest.  I'll close this; please re-open on the [zend-form](https://github.com/zendframework/zend-form) repository if you'd like to submit a PR.
