### ISSUE TITLE
zf2 paginator with join

### ISSUE THREAD

**Issue by matatla** [zendframework/zf2#6457]
I have a problem when I use pagination with join. I've this function:

		if ($paginated) {       
			$select = new \Zend\Db\Sql\Select ();
			$select->from ( 'cliente' );
			$select->columns ( array ('*'), false );
			$select->join ( 'privato', "cliente.idCliente = privato.idCliente", array ('*'), 'left' );
			$select->join ( 'azienda', "cliente.idCliente = azienda.idCliente", array ('*'), 'left' );

			$resultSetPrototype = new ResultSet ();
			$resultSetPrototype->setArrayObjectPrototype ( new Cliente () );
			$paginatorAdapter = new DbSelect ( 
			$select, 
			$this->tableGateway->getAdapter ()); 
			$resultSetPrototype );
			//$paginatorAdapter = $this->tableGateway->selectWith ( $select );
			$paginator = new Paginator ( $paginatorAdapter );
			return $paginator;
		}

		$select = new \Zend\Db\Sql\Select ();
		$select->from ( 'cliente' );
		$select->columns ( array ('*') );
		$select->join ( 'privato', "cliente.idCliente = privato.idCliente", array ('*'), 'left' );
		$select->join ( 'azienda', "cliente.idCliente = azienda.idCliente", array ('*'), 'left' );

		$resultSet = $this->tableGateway->selectWith ( $select );
		return $resultSet;

the code outside the if statement works correctly, the internal code no. Gives me this message:

            Statement could not be executed (42S21 - 1060 - Duplicate column name 'idClient

What's the problem?

**Comment by adamlundrigan** [comment]
I think it's this:

```php
$select->columns ( array ('*'), false );
```

Which results in a SQL query like this:

```sql
SELECT *, "privato".*, "azienda".* FROM "cliente" LEFT JOIN "privato" ON "cliente"."idCliente" = "privato"."idCliente" LEFT JOIN "azienda" ON "cliente"."idCliente" = "azienda"."idCliente"
```

So every column is being selected twice, once by the `*` and once by the `<table>.*`
