### ISSUE TITLE
FormSelect not rendering properly Doctrine's Collections

### ISSUE THREAD

**Issue by mikemix** [zendframework/zf2#6463]
I am binding a Doctrine's user entity to a form, having a manyToMany field called groups. Everything works fine except for displaying currently selected entities.

Method validateMultiValue in FormSelect class does as follows:
```php
        if (!is_array($value)) {
            return (array) $value;
        }
```
Since the value is not an array, but a PersistentCollection, method converts the object to array and ultimately, following code in the renderOptions method:
```php
                if (ArrayUtils::inArray($value, $selectedOptions)) {
                    $selected = true;
                }
```

results in every record selected. Any thoughts how to bypass this?

**Comment by adamlundrigan** [comment]
Many-to-many is poorly supported. Doctrine ORM's manual suggests using a 3-class one-to-many/many-to-one instead:

> Why are many-to-many associations less common? Because frequently you want to associate additional attributes with an association, in which case you introduce an association class. Consequently, the direct many-to-many association disappears and is replaced by one-to-many/many-to-one associations between the 3 participating classes.
