### ISSUE TITLE
zendframework/zend-resources is missing?

### ISSUE THREAD

**Issue by wuethrich44** [zendframework/zf2#6642]
I load zendframework 2 with seperate modules in composer.json. Now I want zendframework/zend-resources but I don't find this package in https://packagist.org. 

Is this package moved to another place?

**Comment by marc-mabe** [comment]
@Ocramius ping

**Comment by Ocramius** [comment]
@marc-mabe only @weierophinney has control over the zendframework organization on packagist.

**Comment by weierophinney** [comment]
We've never actually split the resources out like we did with components -- which is why we don't have packages up on Packagist or packages.zendframework.com. I'll work on it, but likely not before the 2.4.0 release.

**Comment by marc-mabe** [comment]
@weierophinney `zend-resources` is already referenced as own composer package for a long time but the package was never generated. So packages should be created since there is a composer.json.

see #4692
see zendframework/ZF2Package#19
see https://github.com/zendframework/zf2/search?q=zend-resources&type=Code

**Comment by sasezaki** [comment]
ping @weierophinney.

**Comment by Maks3w** [comment]
Resources has been published with the name `zendframework/zend-i18n-resources`

**Comment by weierophinney** [comment]
Packages are named `zendframework/zend-i18n-resources`, and are on both packagist and packages.zendframework.com.

**Comment by samsonasik** [comment]
thank you

**Comment by marc-mabe** [comment]
Thanks for this!

Is there a reason why this isn't moved directly into zend-validator and zend-captcha?
