### ISSUE TITLE
isValid sets up old values?

### ISSUE THREAD

**Issue by alexd5** [zendframework/zf2#6645]
Hello!

Strange work of isValid method in ZF 2.3.2. I have added comments.

         $form  = new AlbumForm();
         $form->bind($album); // $album with old values
         $form->get('submit')->setAttribute('value', 'Edit');

         $request = $this->getRequest();
         if ($request->isPost()) {
             $form->setInputFilter($album->getInputFilter());
             $form->setData($request->getPost());

             // form elements ($form->get('element')) get new values from $request->getPost().

             if ($form->isValid()) {
                 $this->getAlbumTable()->saveAlbum($album);

                 // form elements ($form->get('element')) get old values !

                 return $this->redirect()->toRoute('album');
             }
         }

**Comment by Martin-P** [comment]
@Ocramius This issue is fixed in #6614 and can be closed.

**Comment by Ocramius** [comment]
@Martin-P thanks, closing.
