### ISSUE TITLE
Translator cache does not handle memcached correctly

### ISSUE THREAD

**Issue by dennis-hh** [zendframework/zf2#6677]
Heyho,
I just stumbled upon this issue. When I set a memcached adapter (with disabled exception throwing) as a translation cache, I only get translation keys instead of the correct translations if the server is not reachable (e.g. wrong IP or no memcache server present at the given IP).
The root of this issue seems to be located in Zend\I18n\Translator\Translator::loadMessages (line 560). It only checks for null, but if the memcache adapter could not fetch a cache entry, it returns false instead of null, resulting in the described issue.

Dennis

**Comment by marc-mabe** [comment]
@dennis-hh @DASPRiD @Ocramius ping

**Comment by dennis-hh** [comment]
Sorry for the long silence. I just checked ZF 2.4.0 (which received the bugfix from #6560) and it works as expected now.
