### ISSUE TITLE
Bad param passed into EventManager::attachAggregate

### ISSUE THREAD

**Issue by kusmierz** [zendframework/zf2#6721]
We have in `\Zend\EventManager\EventManager::attach`:

```php
        // Proxy ListenerAggregateInterface arguments to attachAggregate()
        if ($event instanceof ListenerAggregateInterface) {
            return $this->attachAggregate($event, $callback);
        }
```
https://github.com/zendframework/zf2/blob/master/library/Zend/EventManager/EventManager.php#L279

but the `\Zend\EventManager\EventManager::attachAggregate` looks like:

```php
    public function attachAggregate(ListenerAggregateInterface $aggregate, $priority = 1)
    {
        return $aggregate->attach($this, $priority);
    }
```

shouldn't be there:

```php
$this->attachAggregate($event, $priority);
```

?

But it's still probably wrong, as long as `\Zend\EventManager\ListenerAggregateInterface::attach` has only one param...

**Comment by Maks3w** [comment]
This won't fix because on v3 Aggregate listeners not exists and this is not enough important for to be applied on 2.4 LTS
