### ISSUE TITLE
[Form] input type='Date' doesn't validate format='d/m/Y' 

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zf2#6727]
If I use : 
```php
$this->add(array(
     'type' => 'Date',
     'name' => 'start_date',
         'options' => array(
            'format' => 'd/m/Y'
    ),
));
```
It doesn't work for format 'd/m/Y'.
![dmy](https://cloud.githubusercontent.com/assets/459648/4492032/ee28bbc4-4a3d-11e4-92cb-74ba34dc0700.png)

but it works for type='Text' and add validators 'date' .
```php
$this->add(array(
     'type' => 'Text',
     'name' => 'start_date',
));
```
and register validator : 
```php
array(
    'name' => 'start_date',
    'required' => true,
    'validators' => array(
          array(
              'name' => 'date',
               'options' => array(
                     'format' => 'd/m/Y',
                ),
            ),
      ),
),
```

**Comment by adamlundrigan** [comment]
Can this issue be closed?   From what I've read above it seems that the date form element has a prescribed format that cannot be changed, so this is not actually a bug.
