### ISSUE TITLE
BC break: Unit testing not possible anymore under Windows

### ISSUE THREAD

**Issue by Martin-P** [zendframework/zf2#6737]
PR #6205 introduced a break for unit testing under Windows. The change makes unit tests fail because test assets can not be found anymore.

```
D:\zf2-bugs\vendor\zf2\tests>phpunit
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from D:\zf2-bugs\vendor\zf2\tests\phpunit.xml

....
Fatal error: Class 'ZendTest\Form\TestAsset\InputFilterProvider' not found in D:\zf2-bugs\vendor\zf2\tests\ZendTest\Form\FormTest.php on line 187
```

When I place the original code back into `_autoload.php` all works fine again:
```php
<?php
/**
 * Setup autoloading
 */

include_once __DIR__ . '/../vendor/autoload.php';

$loader = new Zend\Loader\StandardAutoloader(
    array(
        Zend\Loader\StandardAutoloader::LOAD_NS => array(
            'ZendTest' => __DIR__ . '/ZendTest',
        ),
    )
);
$loader->register();
```
I tried to bring it up in the PR itself, but unfortunately get no response there.

**Comment by Maks3w** [comment]
IIRC this don't happen any more. After 2.5 split lots of test suites has been fixed.

**Comment by Martin-P** [comment]
@Maks3w Can you provide the link to the PR that fixes this documentation issue?

**Comment by Maks3w** [comment]
What documentation?

**Comment by Martin-P** [comment]
The documentation I mentioned earlier in this issue.
