### ISSUE TITLE
Allow autocomplete and maxlength attributes for more elements

### ISSUE THREAD

**Issue by bogdanghervan** [zendframework/zf2#6739]
The following attributes are being ignored by these element view helpers and they should be allowed by adding them to <code>$validTagAttributes</code>:
* <code>autocomplete</code>
  * <code>Zend\Form\View\Helper\FormTextarea</code>
  * <code>Zend\Form\View\Helper\FormSelect</code>
* <code>maxlength</code>
  * <code>Zend\Form\Element\Number</code>

Firefox pre-fills textarea and select elements too and we need a way to turn that off.

We may need to start this issue together with issue #6464 which is also related to the <code>autocomplete</code> attribute.

**Comment by MadCat34** [comment]
@Ocramius this issue can be closed ? #6854 was merged and closed :-)
