### ISSUE TITLE
Zend framework session

### ISSUE THREAD

**Issue by kalyantmk** [zendframework/zf2#6780]
Hi friends, i am using zend framework 1.10 and php 5.3.5 .Here in my project user login with his credentials, after validating user , i am storing user-id in session, this session will used in other pages to get the user related data in project.  

here i am getting a problem. After login visiting of pages some time the session changing and get getting of other user data in my page its getting some times only.

what i suppose to do, how would i fix this error, friends kindly help me..

**Comment by jaapio** [comment]
ping @Ocramius looks like this one can be closed

**Comment by Ocramius** [comment]
Thanks for pinging. Closing.
