### ISSUE TITLE
Zend\Db\Sql\Predicate\Predicate: $nextPredicateCombineOperator + addPredicate() not working

### ISSUE THREAD

**Issue by Pittiplatsch** [zendframework/zf2#6800]
`Zend\Db\Sql\Predicate\PredicateSet::addPredicate()` doesn't consider `$this->nextPredicateCombineOrder`, and it actually can't do so because `$this->nextPredicateCombineOrder` is defined in `Zend\Db\Sql\Predicate\Predicate` which derives from `Zend\Db\Sql\Predicate\PredicateSet`.

I created two test cases: https://github.com/zendframework/zf2/pull/6799
Test case 50 succeeds implicitly because the default combine order which is used by `Zend\Db\Sql\Predicate\PredicateSet::addPredicate()` instead of intended `Zend\Db\Sql\Predicate\Predicate::nextPredicateCombineOrder` is AND.
Test case 51 however fails, unveiling the observed (mis-) behaviour.

**Comment by weierophinney** [comment]
Fixed with #6799
