### ISSUE TITLE
Zend\InputFilter\Input\Input->merge error

### ISSUE THREAD

**Issue by mezor** [zendframework/zf2#6819]
If you merge two Zend\InputFilter\Input\Input Instances (with the same property name) into each other, the merge could be wrong. Unittest:

<?php

use Zend\InputFilter\Input;

class MergeTest extends \PHPUnit_Framework_TestCase
{
    public function testMergeOnSameName()
    {
        $input = new Input('foo');
        $input->setRequired(true);
        $input->setAllowEmpty(true);

        $input2 = new Input('foo');
        $input2->setRequired(true);
        $input2->setAllowEmpty(true);
        $input2->merge($input);

        $this->assertTrue($input2->isRequired());
        $this->assertTrue($input2->allowEmpty());
    }
}

**Comment by Maks3w** [comment]
Close. 2.4 and 2.5 has been released.
