### ISSUE TITLE
Problem iterating buffered ResultSet

### ISSUE THREAD

**Issue by ChrisSchreiber** [zendframework/zf2#6845]
If you iterate over a buffered result set but stop before reaching the end then try to iterate over it again the data past where the initial iteration stoped is not returned correctly.

The problem is Zend\Db\ResultSet\AbstractResultSet::rewind() does not reset the data source's position, but Zend\Db\ResultSet\AbstractResultSet::valid() and Zend\Db\ResultSet\AbstractResultSet::current() use it once you iterate past where the buffer has been filled.

**Comment by Ocramius** [comment]
Handled in #6847
