### ISSUE TITLE
Mail\Transport\FileOptions::getCallback() zend mail filename

### ISSUE THREAD

**Issue by bacinsky** [zendframework/zf2#6883]
https://github.com/zendframework/zf2/blob/develop/library/Zend/Mail/Transport/FileOptions.php#L91

It would be better to use: `return 'ZendMail_' . microtime(true) . '.eml';` so mails could be read in order they were created.

**Comment by adamlundrigan** [comment]
This has been implemented ([source](https://github.com/zendframework/zend-mail/blob/7a75bb0464da0a40ed3de5aa6dc9ec8f59828662/src/Transport/FileOptions.php#L91))

**Comment by bacinsky** [comment]
I can't agree, maybe you have to read my issue again carefully. I require that emails could be read in order they were created, but it does not seem to be like in the source code.

**Comment by adamlundrigan** [comment]
The default output filename format is:

```php
return 'ZendMail_' . time() . '_' . mt_rand() . '.eml';
```

Which is *nearly* the same as what you've proposed.  It isn't foolproof, as two emails created in the same second may appear out of order depending on the value generated by `mt_rand`.  In your suggestion there is an (admittedly low) probability of conflict: if two emails are created in the same ms they will be saved to the same file.

**Comment by bacinsky** [comment]
The default implementation was there before I reported this issue, so it is clear to me how it works, but is useless for my use cases so I proposed a solution and you close this issue like it is no issue at all. I have this overridden in my "ZF2 adapter" package, so if this is not important to you I can live with that.

**Comment by Maks3w** [comment]
I agree this is not an issue. Current implementation try to resolve the most common case. Since is not the best option for everyone this can be customized.

Also change it means a BC Break with not real wins for the most common scenarios.

**Comment by adamlundrigan** [comment]
@bacinsky this is the reason it's configurable.  The current filename generator is "good enough" for the vast majority of people who use this functionality.  If it doesn't fit your case you can override the filename generator:

```php
$transport = new Zend\Mail\Transport\File(
    new Zend\Mail\Transport\FileOptions([
        'callback' => function() {
            return 'ZendMail_' . microtime(true) . '.eml';
        }
    ])
);
```
