### ISSUE TITLE
Split Framework

### ISSUE THREAD

**Issue by gianarb** [zendframework/zf2#7072]
@ocramius and I talked about the future of this project and the split of framework is an idea to manage in the best way single component. In my opinion these are the hardest structural problems: 
* hard dependencies
* difficult to decouple single component
Considering that we think that the possibility to split the framework could help us to manage this criticality.

**Goal:** Split framework and its history in diferent indipendent repositories (component + your tests).

**Positive**
* Different maintainers for different components..
* ZF2 project is a simple list of dependencies and every components follow its time
* ...

**Negative**
* Difficulties in mantainance and orchestration
* History consistency
* ...

I'm working for this split but the way is long and I'm not a git ninja :) This is my [first tests](https://gist.github.com/gianarb/533083872154fa5c3557) but there are more problems
* Merge is not a good flow.. The history is incomplete.
* Rebase is not a good choose because the history is useless.
* Subsplit works with only one prefix path an this is not a good solution
* 
Maybe this script too easy.. What is your opinion about this proposal and is there a git ninja?! :)

**Comment by gianarb** [comment]
I created a [zf2-prototype](https://github.com/gianarb/zf2-prototype) repo for split tests..
In this moment I'm working to write a little script to split framework with [--filter-branch](http://git-scm.com/docs/git-filter-branch) strategy..
is this a good method? I don't know :)
If anyone have suggestions or ideas write me please :construction_worker:

**Comment by pauloelr** [comment]
@Ocramius, I and @danizord talked with @weierophinney at PHP Conference Brasil and he said he is in favor of keep the docs and code on the same repository after the split.

This way i think the maintainner could try to only merge PR with tests and docs representing the changes on code, this way all the things stay up-to-date, and is easy to keep track of changes.

**Comment by gianarb** [comment]
I'm trying this [script](https://gist.github.com/gianarb/da3291c8671529cca691), in my prototype of ZF2 repo work, there is only one problem for the root commit, it is unchanged.. This script run from seven hours in the official repository :8ball: . Maybe there are different strategies :)

**Comment by jaapio** [comment]
I think you already know but this project https://github.com/zendframework/ng-subsplit was used by weierophinney to create the first tags. 
I found some comment where he wrote that because of the size of this repo --filter-branch was a bad idea.

**Comment by Ocramius** [comment]
@jaapio the problem just affected him because he has to re-run the operations at every release. Once 2.5 is out, we won't need to do that again, as every component will be tagged independently and the subtree split will be ancient history

**Comment by gianarb** [comment]
@jaapio I don't know if this script manage split of ./tests directory

**Comment by jaapio** [comment]
No it won't, it will only split the library.

**Comment by gianarb** [comment]
This is the [first split](https://github.com/gianarb/Stdlib) there are more points of discussion for example:

* the tree of directories is correct? 
* README and CONTRIBUTING are the original of parent repository
* phpunit.xml.dist is in /tests or root of project?
* Move composer.json to root directory and fix missing node (autoload in first)
* ...

**Comment by Ocramius** [comment]
If a couple of folks could help @gianarb checking the history of his split (seeing if it reflects actual framework history for both sources and tests) that would speed up things a lot, thanks!

**Comment by bakura10** [comment]
Hi,

I have checked quickly, it looks good. As I said by email, I think README.md, CONTRIBUTING.md and composer.json should be moved to the top folder, as well as phpunit.xml.dist.

The structure should be flattened too, by renaming library\Zend\Stdlib to src\Zend\Stdlib (or src\ if we use PSR-4).

Regarding the history, when comparing the tests folder, I have commits in the split that are not present in the tests folder of zf2 repo. For instance, there are commits [here](https://github.com/gianarb/Stdlib/commits/master/tests) on 1st August, while they do not appear [there](https://github.com/zendframework/zf2/commits/master/tests/ZendTest/Stdlib).

**Comment by GeeH** [comment]
Can you repeat with more clarity what the intended goal of this split is please?

**Comment by bakura10** [comment]
The goal is to allow each component to evolve separately. We can therefore start working of ServiceManager 3.x for instance, without impacting the rest of the framework. This will allow people to "compose" the framework the way they want.

**Comment by GeeH** [comment]
I would suggest more though about how the "composing" will work is needed before we blindly start separating components. More clarity on how the eventual split framework will be composed into a working and cohesive unit is needed to avoid repetition of work further down the line.

**Comment by GeeH** [comment]
I'm not against this by the way, I'm very much in favour, I just believe that PPPPPP.

**Comment by gianarb** [comment]
@bakura10 thanks for your history check! :+1: I have not removed files into `tests/*` and the commits refer to this files.. I don't know if this stuff is correct or not :confused: But I think so because is part of history..

**Comment by jaapio** [comment]
The files that you exclude are mostly created for zf2 as complete framework. I think after the split we should create the new buildscripts. Some of there files could be extracted from the zf2 repository. But others need to be written. 

Moving the composer.json makes sense since it will have some history. And contains the actual requirements for each component.

**Comment by gianarb** [comment]
I agree with you @jaapio I move composer.json and not exlude .travis .cs... :+1:

**Comment by Pittiplatsch** [comment]
Ocramius wrote:
>The point is that every component maintainer (assuming he's aware of semver) would have a "main" or "LTS" version to maintain for compatibility with the framework, whereas master or subsequent versions could freely upgrade/break BC.
>
>It just assumes that the maintainers know semver very well, and the coordinator would just check breakages before upgrading the composer.json in the main framework.

What I don't see is:
On using LTS versions, when a new LTS of a central component (say ServiceManager 5.1 after previous LTS ServiceManager 4.2) is released, each depending component must be updated to use SM5.1 before the complete framework can be pushed up to SM5.1.
This leads to "badly" maintained components which aren't updated soon block the complete framework, as we cannot depend on two different versions of a single component.
On the other hand, this fact could turn out as advantage when there is an agreement that such "mucky pups" are locked until they support the new SM5.1

I think this needs considerable organisation and communication like:
> ZF3.5 is released on 15th July 2015 with the following dependencies:
> * SM5.1
> * other components current LTS versions
>
> Each component must be updated by that date to fulfill these dependencies; any components failing to fulfill these dependencies will be removed from ZF3.5, but may come back later as soon as they have upgraded theire dependencies.

However, we are chasing our own tail here, when (mentioned dependencies are exemplary!) component Locale must be updated to SM5.1, however compenents Form, Text, Paginator, and Navigation for their parts depend on Locale...
Should become quite difficult to get LTS versions for each component synchronously...

**Comment by Ocramius** [comment]
> Should become quite difficult to get LTS versions for each component synchronously...

An LTS would only bump minor/patch versions of dependencies, so anything should still be compatible.

Major versions will be free to bump wildly as long as the minor versions used in LTS releases are still maintained.

**Comment by Pittiplatsch** [comment]
>An LTS would only bump minor/patch versions of dependencies, so anything should still be compatible.

That's what I first thought as well - no problem here, I thought.
As I stated (a little bit lenghty), the problem comes in with components being dependent from each other, where different components rely on some common component, but in different *LTS* versions.

**Comment by Ocramius** [comment]
> but in different LTS versions

That is purely a component maintenance issue, not really a problem for the LTS "main" package: since components will be handled separately, then the feedback loop in case of incompatibilities will be much shorter, allowing for making stricter or more relaxed dependency constraints.

**Comment by Pittiplatsch** [comment]
It's an organisational problem of the "main" package to have components keeping their dependencies synchronously, as it's simply not possible to release ZF3.7 with SM5.1 if any of ZF's "functional" components doesn't have its dependencies updated to SM5.1 but still relies on SM4.2. This one "trailing" component thus prevents "main" package's complete process. Am I wrong here?

*Disclaimer all component names and version numbers are fictive*

**Comment by Ocramius** [comment]
> Am I wrong here?

No, you are correct, and that's not a problem.

The main point is to stop focusing this much on the main package: main package is an LTS-ish, and therefore people shouldn't bother having the latest and greatest of everything, just a "stable" version is fine ;-)

**Comment by fabiocarneiro** [comment]
Hey guys, git has a subtree comand you can set all commits to a specific branch a pull the created branch from another repo. Is this script really necessary?

    http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475

**Comment by gianarb** [comment]
Hi! The problem of this solution is a tests dir, git subtree supporto only
directory :(

2015-02-04 18:40 GMT+01:00 Fábio Carneiro <notifications@github.com>:

> Hey guys, git has a subtree comand you can set all commits to a specific
> branch a pull the created branch from another repo. Is this script really
> necessary?
>
> http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendframework/zf2/issues/7072#issuecomment-72900943>.
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Comment by fabiocarneiro** [comment]
@gianarb https://github.com/fabiocarneiro/zend-form

```
subtree with source to a branch
move files to src folder, commit
subtree with tests to a branch
move tests to test folder, commit
```
add other settings

**Comment by gianarb** [comment]
I have tried this solution but I have spoke of it with @ocramius, maybe the
[merge between](
https://github.com/fabiocarneiro/zend-form/commit/31b618a9af4669a87e7f1d44355d3efe767fcd68)
two diffirent branch, code_branch and test_branch is not a good solution
for the history

2015-02-04 21:56 GMT+01:00 Fábio Carneiro <notifications@github.com>:

> @gianarb <https://github.com/gianarb>
> https://github.com/fabiocarneiro/zend-form
>
> subtree with source to a branch
> move files to src folder, commit
> subtree with tests to a branch
> move tests to test folder, commit
>
> add other settings
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendframework/zf2/issues/7072#issuecomment-72937102>.
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Comment by gianarb** [comment]
I have tried this solution but I have spoke of it with @ocramius, maybe the merge between two different branch, code_branch and test_branch is not a good solution
for the history..

@fabiocarneiro no problem for me :D Your solution is more easier and faster :) If it resolve the problem **perfect"**

**Comment by fabiocarneiro** [comment]
@gianarb https://github.com/fabiocarneiro/zend-form

I updated it with the filter-branch. It also took a lot of time to move, but i'm not sure for how long it was running since i was sleeping. Zend\Form is one if not the one with most commits, so maybe the other ones take less time.

The subtree approach might be helpful since it can split all commits that modify that files instead of dealing with the full zf2 history, then when running the filter-branch we have less commits to rewrite.

Maybe i can put all together and create a sh script
zf2-split.sh component-src-dir component-test-dir dest
(then you need only to create the remote, add it, and push)

**Comment by gianarb** [comment]
@fabiocarneiro have you see this script? https://gist.github.com/126971cba1ccc5500818 
:+1: thanks for your works

**Comment by fabiocarneiro** [comment]
@gianarb yes i saw it. To be honest i didn't understand what you're exactly doing there (how you move the code to a new repo part). The approach is different anyway, you are erasing files from the history and i'm moving them. If my history is ok, maybe we could merge both works to make it better?

**Comment by gianarb** [comment]
Oh yes, this is the objective! :+1: I know by @ocramius that @EvanDotPro and other CR contributors are seeing this works :) We can only wait theirs opinion

**Comment by weierophinney** [comment]
@gianarb regarding this:

> Speed is a problem :) in my old macbook pro are ~10h for component

now you see the motivation for subsplit-ng. :) This stuff is immensely time-consuming due to the imperative to keep history (which, for some components, goes back almost 10 years now!).

I'll be looking at your gist, and a few others that others have been pointing out to me in the past few weeks since the ZF3 announcement. I am under no illusions that this will be an easy or quick task; however, once done, we'll have a far easier story going forward with maintaining the individual components.

**Comment by gianarb** [comment]
@weierophinney the time is frightening :ghost: but this split work only one time this stuff resize the problem :) But every others best proposal is good! :+1: 
I'm here for every tests or upgrades, for example I don't know if the history result is good or not :)

**Comment by carnage** [comment]
Speed is not really an issue. The split only has to happen once. There will be ways to improve speed anyway. eg: http://willi.am/blog/2014/10/14/unpacking-a-git-database/ and putting the repo on a ram disk to speed up I/O

**Comment by gianarb** [comment]
@carnage yes thanks.. This night I'm trying to split a component in digitalocean, this is another life :P

**Comment by jaapio** [comment]
Not sure if this is still applicable. And some other git guru's could probably the same job. But I found this scrip https://github.com/simpliwp/git-splits/blob/master/git-splits which does its job quite good.

**Comment by gianarb** [comment]
Hi @jaapio impossibile?! None!
We are using this script to split framework [here](https://github.com/zendframework/component-split)

**Comment by jaapio** [comment]
What I meant was that I wasn't sure if you were still looking for a solution. I see there is one, so my comment was not applicable. :-)

**Comment by weierophinney** [comment]
Accomplished with #7542
