### ISSUE TITLE
Content-Type header parameters not parsed correctly

### ISSUE THREAD

**Issue by h3d0n15m** [zendframework/zf2#7076]
Hi there,

I noticed that there is a bug in the Content type header parsing when there is quotes in the boundary.

Here is the example:

Request 1:

    PUT /api/document/1 HTTP/1.1
    Host: some.dev.host
    Cache-Control: no-cache
    Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

Result 1:

    object(Zend\Http\Header\ContentType)[1284]
                  protected 'mediaType' => string 'multipart/form-data' (length=19)
                  protected 'parameters' => 
                    array (size=1)
                      'boundary' => string '----WebKitFormBoundarynh89YYmAdszVorA8' (length=38)
                  protected 'value' => null

So far everything is OK. Notice the following example:

Request 2:

    PUT http://some.dev.host/api/document/1 HTTP/1.1
    Connection: close
    Accept-Encoding: gzip,deflate
    User-Agent: Soap UI
    Content-Type: multipart/form-data; boundary="----=_Part_7_8683553.1419605792463"
    MIME-Version: 1.0
    Accept: */*
    Content-Length: 31668
    Host: some.dev.host

Result 2:

    object(Zend\Http\Header\ContentType)[1284]
                  protected 'mediaType' => string 'multipart/form-data' (length=19)
                  protected 'parameters' => 
                    array (size=0)
                      empty
                  protected 'value' => null

So when boundary value is surrounded by quotes then there is parsing error.

**Comment by karuna-kgx** [comment]
Removing the quotes creates problems with SOAP when using Http\Client to make SOAP requests. 

For example, it will remove quotes from the following header:
Content-Type: application/soap+xml;charset=UTF-8;action="http://tempuri.org/SomeRequest"

This results in a 400 error from the SOAP service.
