### ISSUE TITLE
[Zend\ServiceManager] New sub key to configure factories via constructor from config file

### ISSUE THREAD

**Issue by sandrokeil** [zendframework/zf2#7077]
This idea comes from issue #6717 to configure a factory via constructor. I heavily use configurable factories and wrote a [zf2 module](https://github.com/sandrokeil/EasyConfig) to make this easier. 

However, the question is: How to configure a factory only with scalar values from configuration files to avoid "useless" factories?

In this example we only need a config name which is injected via constructor argument to create a navigation instance only with special sites:

```php
// service manager config e.g. in module.config.php
return array(
    'service_manager' => array(
        'factories' => array(
            'mymodule.navigation.special' => new \Zend\Navigation\Service\NameNavigationFactory('special'),
        ),
    ),
);
```

With a new config key e.g. `configurable` we can avoid the instantiation above so it works with XML/YAML or other configuration files and with caching.

```php
// service manager config e.g. in module.config.php
return array(
    'service_manager' => array(
        // new service manager key
        'configurable' => array(
            'mymodule.navigation.special' => array( 
                'class' => ' \Zend\Navigation\Service\NameNavigationFactory',
                'params' => array('special'),
            ),
        ),
    ),
);
```
Parameters are injected in constructor via Reflection class. [See here for an example](https://github.com/sandrokeil/EasyConfig/blob/master/src/Service/AbstractConstructorOptionConfigFactory.php).

Is this useful for ZF2 or not? Note that you should only use scalar values in your configuration files e.g. for caching.

**Comment by carnage** [comment]
You could (kinda messy) add a parameter order option as well which defines the order that the named parameters should be passed to the constructor

**Comment by weierophinney** [comment]
Clearing milestone. Please re-submit the issue against [zendframework/zend-servicemanager](https://github.com/zendframework/zend-servicemanager).

**Comment by sandrokeil** [comment]
This is also discussed in [zendframework/zend-servicemanager/pull/2](https://github.com/zendframework/zend-servicemanager/pull/2).
