### ISSUE TITLE
Annotation\Flags priority doesnt seems to work

### ISSUE THREAD

**Issue by cbichis** [zendframework/zf2#7099]
Hello,

I havent used Annotation\Flags before so I hope I am not wrong. Because of lacking documentation I am not sure if the purpose of this is what I expect: to have the elements ordered in a different way than the order within entity. Including for rendering form.

For an entity if I include the priority flag it doesnt seems to order the elements based on priority.
```
    /** 
     * @var string
     * @Annotation\Flags({"priority": 100})
     * @Annotation\AllowEmpty(true)
     * @Annotation\Type("Zend\Form\Element\File")
     * @Annotation\Options({"label":"Image"})
     * @ORM\Column(type="string", nullable=false)
     */
    protected $image;

    /**
     * @var string
     * @Annotation\Flags({"priority": 1})
     * @Annotation\Type("Zend\Form\Element\Text")
     * @ORM\Column(type="string", length=32, nullable=true)
     */
    protected $name;
```
At rendering part the image element is ordered firstly, not the name element as expected.

**Comment by mpalourdio** [comment]
Can you try @Annotation\Flags({"priority": "100"})  ?-> note the quotes around '100'

**Comment by mpalourdio** [comment]
It works in the opposite way you think it works IIRC. High values appear first. Try inverting the values between image and name

**Comment by cbichis** [comment]
It seems to work if I apply both of your suggestion: use "100" and high values first.

I think this issue should be changed to a doc-related issue as the doc is without " and there is no mention related to ordering:

Flags: flags to pass to the fieldset or form composing an element or fieldset; these are usually used to specify the name or priority. The annotation expects an associative array: @Flags({"priority": 100})


Thank you mpalourdio !

**Comment by mpalourdio** [comment]
Sorry, i had edited my message, in fact, there's no need for quotes, please read my edit.

**Comment by cbichis** [comment]
Hmmm, I cant reproduce again the issue.

I was wrong on the Lower values first that's sure...
