### ISSUE TITLE
Sources for Tutorial "Album" application

### ISSUE THREAD

**Issue by cjm51213** [zendframework/zf2#7111]
Hi Folks,

I am following the tutorial, and I find it a bit confusing, but after a few IRC sessions, I understand very much more. However, there is a problem. The architecture of the "Albums" application has two modules -- "Application" and "Album". The tutorial instructs me to complete the module/Album/config/module.config.php and explains that there is need for module/Application/config/module.config.php but I find no instructions or explanation for this file.

It would be helpful if the correct and verified source were available so progress with the tutorial can be compared with the actual end result.

**Comment by Ocramius** [comment]
The tutorial is speaking of the `Application` module in the standard ZF2 skeleton application: https://github.com/zendframework/ZendSkeletonApplication

**Comment by Ocramius** [comment]
Closing as it is not an issue
