### ISSUE TITLE
Broken navigation menu after 2.3.4

### ISSUE THREAD

**Issue by Lansoweb** [zendframework/zf2#7126]
Hi!
I've updated my project today to 2.3.4 and some of my submenus gone missing. It's related to https://github.com/zendframework/zf2/issues/4517. 

I usually have a "top menu" in my application's module.config.php:
```php
'navigation' => array(
        'default' => array(
            'home' => array(
                'label' => 'Home',
                'route' => 'home'
            ),
            'reports' => array(
                'label' => 'Reports',
                'route' => 'reports'
            ),
        ),
    ),
```

And each module contribute for the menu with it's own submenu, like module User:
```php
'navigation' => array(
        'default' => array(
            'reports' => array(
                'pages' => array(
                    'reports/user' => array(
                        'label' => 'User Reports',
                        'route' => '/user/report',
                     ),
                 ),   
             ),
         ),
     ),
```

It's been working for more than a year that way, but after https://github.com/zendframework/zf2/issues/4517 it's not working anymore, so i reverted all my projects to 2.3.3.

Any "correct" way to have each module "contribute" to a menu with it's one pages (submenus)?

Best Regards,
Leandro Silva

**Comment by Moring** [comment]
AbstractContainer:487 call to current() is not required, as the current page is the proper context for the hasPages() call for the recursive iterator.

**Comment by Lansoweb** [comment]
Actually, just removing the current() does not solve my problem, because the $this->valid() returns false in:
```php
public function hasChildren()
{
    return $this->valid() && $this->current()->hasPages();
}
```

So if my config is invalid for the component, maybe there is another way to have the same menu structure, preferably separated by modules. If i have all navigation in the same config file it works ok. But i reuse most of modules in different projects, so the navigation is copied that way.

**Comment by Lansoweb** [comment]
@Ocramius: Today i had more time to investigate and the problem is not the component, but i use a library that styles the UI for bootstrap3 and the menu helper called $page->hasChildren() during its render to add a dropdown. I changed it to $page->hasPages() and it's working fine. Sorry for the inconvenience.

**Comment by Ocramius** [comment]
@Lansoweb please open an issue in the related library, and reference this one then ;-)

**Comment by Lansoweb** [comment]
Already fixed, it's my own library :-)

**Comment by Moring** [comment]
@Lansoweb: resolved my issue as well, exact same use case.
@Ocramius: My issue arose from programming against the RecursiveIterator interface.  I am often wrong in my decades of programming, and readily admit studying your code to improve--but does this seem to be different than expected behavior of an RecursiveIterator implementation?  Perhaps call this out in the documentation somewhere?

**Comment by Ocramius** [comment]
> but does this seem to be different than expected behavior of an RecursiveIterator implementation

I'd rather ask that in the original issue (#4517)
