### ISSUE TITLE
classmap_generator Deprecated: preg_replace():

### ISSUE THREAD

**Issue by googlle** [zendframework/zf2#7134]
Creating class file map for library in 'C:/xampp/htdocs/application/module/Appli
cation'...

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_call
back instead in C:\xampp\htdocs\application\vendor\zendframework\zendframework\b
in\classmap_generator.php on line 231

**Comment by Lansoweb** [comment]
Hi @googlle. I made a PR for this early today:
https://github.com/zendframework/zf2/pull/7135
Will be fixed in the next version (i hope).

**Comment by Ocramius** [comment]
Handled in #7135
