### ISSUE TITLE
[ZF3][kind-of RFC] Event Manager, attempt n°4

### ISSUE THREAD

**Issue by bakura10** [zendframework/zf2#7143]
# Event Manager

Hi everyone,

This is a new thread that superseeds #5693. A lot of things will be duplicate, but I want to give a few more options and bring more experience based on my last project that heavily relied on event manager.

## The shared event manager

Zend Framework 2 is the only framework that contains a shared event manager, and what makes it so powerful. However, it comes with a few caveats:

* People don't understand why there are two ways to attach listeners (to the shared event manager and the normal event manager).
* It comes with a heavy overhead in performance.
* The shared event manager uses a concept of identifiers, that is both obscure and can lead to hard-to debug bugs (more on that later).
* It forces to instantiate all the listeners on each requests, which introduce a large overhead if you have listeners with a lot of dependencies.

Basically, the shared event manager as it acts as a kind of "singleton", and we wanted to avoid the `StaticEventManager` that is still present in ZF2.

But I realized two things:

* I always use the shared event manager. I've take a look at my code, and all the listeners I attach are attached to the shared event manager.
* I nearly never use the concept of identifiers, but I am forced to indicate one (or using a wildcard).

In this app, I came accross a subtle bug that took me hours to find, and that was made possible only because of the fundamental concept of shared event managers. Basically, I had a service, that I call "Service1", that triggered an event:

```php
class Service1 implements EventManagerAwareInterface
{
	use EventManagerAwareTrait;
	
	public function doSomething()
	{
		// ...
		$this->getEventManager()->trigger('foo', $event);
	}
}
```

Then, I have a listener aggregate that attaches a callable to this event:

```php
class MyListener extends AbstractListenerAggregate
{
	public function attach(EventManagerInterface $evm)
	{
		$sem = $evm->getSharedManager();
		$sem->attach(Service1::class, 'foo', [$this, 'doSomething']);
	}
}
```

However, my Service1 became too complex, so I decided to split it into two services, and the event manager got triggered in the new "Service2". Consequence: because the listener was attached to the identifier "Service1", it was no longer executed. No error, nearly impossible to test in unit test (you need complex functional tests), and can be even completely silent for ages if what the listener do is sending an email, for instance.

To my opinion, identifiers are introducing a complexity that is often not needed, and that is better solved by using namespacing in event names (instead of triggering a "created" event in a User service, trigger a "user.created" event instead). I see very few use cases for having to filter a specific event by an identifier (I have never used this feature), and it would be actually simpler to add a specific status property right in the event name, that could be used to accept/reject the event in a given listener.

In the context of the MVC, for instance we have two "MVC_DISPATCH": one that is triggered by the Application, and another one that is triggered by the controller, but using a specific identifier to "scope" the listeners. Once again, this event should be split into two events: "application.dispatch" and "controller.dispatch". This completely removes the need of having identifiers and remove a pain point ("why did I attach to MVC_DISPATCH but I do not receive the event?").

Of course, I could have used the wildcard identifier, but this introduces even more complexity, even more performance overhead during merging...

## The two EVM approach

Previous section outlined the issue of the shared event manager, and now the issue of performance.

In one of my (numerous) attempts to refactor the EVM, I tried one approach with two different event manager implementations: a so called "SimpleEventManager" without SharedEventManager, and a "EventManager" that can have a SharedEventManager.

The SimpleEventManager was therefore very fast because it removed the need of merging listeners coming from the shared event manager.

However, after some thoughts, I think this is a wrong approach: it introduces even more complexity. Now the EVM component will not contain two EVM, but three: the SimpleEventManager, the EventManager and the SharedEventManager.

Moreover, as I said, we nearly always need to use shared event manager, that finally make the SimpleEventManager of very limited use.

### Avoid instantiate useless listeners

Actually, the SimpleEventManager can be used to avoid the problem of instantiating listeners that would never be executed. For instance, let's say that you have a listeners that should listen to an event that is ONLY triggered when a specific controller is created.

You can, of course, attach your listener to the shared event manager, directly in your Module.php class (common practice), but it will be instantiated at each request.

The other solution is to override the factory (or add a delegator), to attach it in the factory of the controller: if the controller's factory is called, this means that the request will be routed to this controller, and hence we will need the listener.

While this works, this has the problem of scatter the attach process in two different places: in Module.php and in factories.

Ultimately, we want to have something predictable and simple to understand.

## The single EVM approach

Having said all this, I came to those conclusions:

* Common use case is to only use the SEM.
* We want a way to solve the problem of instantiating useless listeners.
* We want to keep all the functionality of being able to attach to wildcard.
* We want to remove the complexity introduced by identifiers.

What I suggest is completely removing the concept of the SharedEventManager, of Simple/FastEventManager and so on. ZF3 would ship with only ONE EventManager: EventManager. Its interface would be greatly simplified:

```php
interface EventManagerInterface
{
	public function attach($eventName, callable $listener);
	
	public function attachSpecification(array $specification);
	
	public function trigger($eventName, EventInterface $event);
	
	public function triggerUntil($eventName, EventInterface $event, callable $callback);
}
```

The main instance of EventManager would be registered inside the Service manager using its FQCN (`EventManager::class`). Nothing would prevent you to create a different instance, but because what you want is mostly replicating the SharedEventManager, typical use case will be to retrieve the main EventManager.

This event manager of course supports wildcard, so you can attach a listener to the "*" event.

Here is how you can attach a listener in your Module.php:

```php
$eventManager = $serviceManager->get(EventManager::class);
$eventManager->attach('foo', [$this, 'doSomething']);
```

Now, you can see a new method in the interface called `attachSpecification`. This method is what allows to enable a simple lazy-load mechanism in a simple way.

A specification is a specific array format that map one event name to one or multiple event:

```php
return [
	// Attach one event to a given listener with a default priority
	'user.created' => MyListener::class,
	
	// Attach one event to a given listener with a given priority
	'user.deleted' => [MyListener::class, 15]
];
```

In practice, each class in a specification should implement the `ListenerAggregateInterface`, where the interface would be as follow:

```php
interface ListenerAggregateInterface
{
	public static function getSpecification();
	
	public function dispatchEvent($eventName, EventInterface $event);
}
```

To attach an event, you would do like this, in your Module.php class:

```php
$eventManager = $serviceManager->get(EventManager::class);
$eventManager->attachSpecification(MyListener::getSpecification());
```

Notice how no shared event manager complexity is introduced, and no useless instantiation is needed (only calling a static method).

Internally, the EventManager would have a ListenerPluginManager:

```php
class EventManager implements EventManagerInterface
{
	private $listenerPluginManager;
	
	public function __construct(ListenerPluginManager $listenerPluginManager = null)
	{
		$this->listenerPluginManager = $listenerPluginManager ?: new ListenerPluginManager();
	}
}
```

When triggering an event, the event manager could look like this:

```php
public function trigger($eventName, EventInterface $event)
{
	$mergedListeners = $this->getMergedListeners($eventName);
	
	foreach ($mergedListeners as $listener) {
		if (is_string($listener)) {
			$listener = $this->listenerPluginManager->get($listener);
			$listener->dispatch($eventName, $event);
			continue;
		}
		
		$listener($event);
	}
}
```

With the implementation of a dispatch method inside the listener aggregate:

```php
class MyListenerAggregate implements ListenerAggregateInterface
{
	public static function getSpecifications()
	{
		return [
			'user.created' => $this::class,
			'user.deleted' => [$this::class, 15]
		]
	}
	
	public function dispatch($eventName, EventInterface $event)
	{
		switch ($eventName) {
			case 'user.deleted':
				$this->userDeleted($event);
				break;
				
			case 'user.created':
				$this->userCreated($event);
				break;
		}
	}
}
```

Boom, everything's solved. I'm not entirely satisfied by the "getSpecifications" and "dispatch", but that's the idea.

**Comment by acelaya** [comment]
I really like this approach

**Comment by sandrokeil** [comment]
That sounds good. Do you have plans do detach listeners? I used this e.g. to disable ZendDeveloperTools on a specific action. The static specification approach is really useful if the listener aggregate has "heavy" constructor dependencies.

**Comment by texdc** [comment]
Generally good idea.  One should only use the application's `EventManager` if an application event is needed, though.  Most of the time, like 'user.registered', it's just a domain event to be handled internally by the `User` context.

An `$eventName` should not be necessary.  `EventInterface::getName()` or `ListenerAggregate::handles(EventInterface $anEvent)` should suffice.

One last note:  there is no `$this` in a `static` method.  Use `static::class` instead.

**Comment by jbenoit2011** [comment]
Your approach makes things simpler. But I have a question, why it wasn't did as you propose the first time ? Your solution seems so obvious.
BTW, the unique Event Manager is what [Symfony 2 already does](http://symfony.com/doc/current/components/event_dispatcher/introduction.html#the-dispatcher).

**Comment by bakura10** [comment]
@sandrokeil : I don't know yet about detach, but I suppose this is just an implementation detail.

@texdc : no, this is not possible to remove the $eventName. I often have an Event object, that is used for multiple events (instead of duplicating the event), where I set different constants for each event:

```php
class UserEvent extends Event
{
    const USER_CREATED = 'user.created';
    const USER_DELETED = 'user.deleted';

    private $user;
}

// ...
$evm->trigger(UserEvent::USER_CREATED, $event);
```

@jbenoit2011 : I don't know. At the beginning, we had a StaticEventManager which, I suppose, was used like this. Because we wanted to avoid having so much staticness, we introduced a SharedEventManager, but after using it extensively, I realized that if I am using 100% of the time the SharedEventManager, then it would mean than simply injecting the same event manager, and encouraging namespacing event names is a much better solution.

The SharedEventManager offers much more, actually. You can scope very precisely an event using identifiers, and even combining a wildcard event with a specific identifier and vice-versa. But it introduces so much complexity and performance overhead, for use cases that are so specific, that I'm not sure this is worthwhile.

**Comment by bakura10** [comment]
Hi everyone,

I've written a prototype here: https://github.com/zendframework/zf2/pull/7145

I've renamed and simplifeid most of the interfaces and included the lazy listener idea. With generators, it was surprinsingly easy to do :D.

**Comment by texdc** [comment]
@bakura10 Yes, it is possible to remove the `$eventName`, even in your context:

```php

final class UserEvent extends Event
{
    const CREATED = 'user.created';
    const DELETED = 'user.deleted';
    
    private $user;

    public function __construct(User $aUser, $anEventId = self::CREATED)
    {
        parent::_construct($anEventId);
        $this->user = $aUser;
    }

    public static function created(User $aUser)
    {
        return new static($aUser, static::CREATED);
    }

    public static function deleted(User $aUser)
    {
        return new static($aUser, static::DELETED);
    }
}

// finally...
$this->evm->trigger(UserEvent::created($user));
```

**Comment by carnage** [comment]
Lazy listeners is something I think ZF2 is missing, I had it on my list of things to think about and bring up as an idea once I had an implementation plan.

Perhaps we could come up with a stronger way to namespace events, I wonder if something like auto prepending the FQCN to the name of the triggered event would work.

"""
$evm->trigger('my_event', new MyEvent('some param')); 
"""

could trigger listeners that are listening for \MyNamespace\MyEvent::my_event

**Comment by bakura10** [comment]
@carnage , I have made a PR that includes the lazy listener thing: https://github.com/zendframework/zf2/pull/7145

It's really nice, and I've been able to keep nearly the same terminology, and not  introduce any distinction between lazy and non lazy at usage (in my implementation, it's only an implementation detail, so if you pass a [$className, 'method'], it will fetch it lazily, or if you pass [$object, 'method'] it is smart enough to know it's an instance and do not fetch it lazily.

Regarding namespacing event, I do not want to make it too confusing. It's your responsibility to name the event the way you want. Typically, I use Event object that holds the name of the event: MyEvent::EVENT_DELETED, so it's up to your event class to define the name (and you can namespace it using the FQCN if you feel too).

**Comment by jaapio** [comment]
I don't like the idea of creating a magic method like you do:
```php
$this->evm->userCreated($user);
```
I think this one is better
```php
$this->evm->trigger(UserEvent::created($user));
```
But I like the idea of having attaching listeners without creating an instance. But it would also be nice if you could create a lazy listener with some kind of factory. In our applications we create listeners mostly via the servicemanager since the will need to call other services to do there job. 

Like you said when listeners are heavy to create or need services that are not available load of the module. We have use a delegator factory to attach them. But with this solution we still need to do it that way. Since the listener will be created by the EventManager?

**Comment by bakura10** [comment]
What do you mean @jaapio ? I never suggested using magic methods. The only method to trigger events is "trigger", as you suggested.

The factory is exactly what I did in the implementation ;). A plugin manager is injected into the event manager, and you can register your own listeners like any other plugin:

```php
return [
    'listeners' => [
        'factories' => [
            MyHeavyListener::class => MyHeavyListenerFactory::class
        ]
    ]
]
```

**Comment by jaapio** [comment]
@bakura10 I must have missed that part, sorry.
@texdc did a proposal to use $evm->userCreated(); in this commend https://github.com/zendframework/zf2/issues/7143#issuecomment-71037716
For me that's a kind of magic, since the evm will no have methods like that. only a __call.

**Comment by bakura10** [comment]
Please have a look at #7145 , you have a working implementation on it (well, nearly, it assumes you are using SM 3 :p)

**Comment by texdc** [comment]
@jaapio That's not a magic method.  It's actually a domain-specific `$evm` for the user context instead of a `global` evm.  Sorry for the lack of clarity.

**Comment by adamlundrigan** [comment]
I've read through the code and I don't have any suggestions to add.  My personal bias against static methods initially got in the way but I can see why you've chosen to do it that way.  It'll be a nice feature to be able to avoid instantiating an object when attaching a listener that doesn't have any dependencies. 

Like you I usually find myself hitting the shared event manager for attaching listeners and don't think I've ever needed to wildcard the identifier in any of my apps.  The current Event Manager was built to cover a broad range of use cases, but how many of those are regularly used by apps?  

I love that you've cut the code down by 80%...superb work!  :shipit:

**Comment by bakura10** [comment]
Thank you :).

**Comment by mikemix** [comment]
Why not simplify the interface. I still remember this mwop's blog post: "2011-10-06: Removed references to triggerUntil(), as that functionality is now incorporated into trigger(). Added section on Custom Event Objects."

**Comment by Maks3w** [comment]
EventManager v3 is already merged on zend-eventmanager develop branch

**Comment by easy-system** [comment]
imho, you do not need methods "attachSpecification()".  Your aggregates - is, in fact, Visitors (design pattern). If a visitor reads a specific configuration, and adds (attach) the desired listeners - in this unusual? Why do not you keep a common event manager in a service locator?
