### ISSUE TITLE
Zend\Db\Adapter\Driver\Pdo\Result Not using \PDO::FETCH_ASSOC in current() method

### ISSUE THREAD

**Issue by itrascastro** [zendframework/zf2#7154]
public function getById($id)
    {
        $stm = $this->db->createStatement('SELECT * FROM User WHERE id = ?');
        $rowset = $stm->execute(array($id));
        $row = $rowset->current();
    }

current() is using FETCH_ARRAY instead of FETCH_ASSOC as it is supposed to be

**Comment by Ocramius** [comment]
Did you check the test suite? Maybe that's the expected behavior...

**Comment by itrascastro** [comment]
Can I force it to be \PDO::FETCH_ASSOC in current() call or elsewhere?

**Comment by Ocramius** [comment]
Marking as `awaiting author updates`: please check the test suite first.

**Comment by Martin-P** [comment]
`\PDO::FETCH_ASSOC` is hardcoded in [`Zend\Db\Adapter\Driver\Pdo\Result` line 119](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/Db/Adapter/Driver/Pdo/Result.php#L119):
```php
$this->currentData = $this->resource->fetch(\PDO::FETCH_ASSOC);
```
It should be impossible not to use `\PDO::FETCH_ASSOC`.

@Ocramius:
The test suite only contains a single test for `current()`, that's all: [ZendTest\Db\Adapter\Driver\Pdo\ResultTest](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/tests/ZendTest/Db/Adapter/Driver/Pdo/ResultTest.php)

**Comment by itrascastro** [comment]
That is why I am surprised because it is hardcoded. But it happens to me with the code I posted, it seems that it is using \PDO::FETCH_ARRAY. I cannot find a reason for that. I have attached an screenshot:

![current-return-array](https://cloud.githubusercontent.com/assets/3638437/5905160/57eae9b4-a58e-11e4-8a0f-5e2675b79e84.png)

**Comment by Martin-P** [comment]
Your screenshot shows exactly what `\PDO::FETCH_ASSOC` should do. It shows an array with 5 named elements:
* `$row['id']` has value `5`
* `$row['email']` has value `user5@email.com`
* `$row['password']` has value `1234`
* etc.

What do you think `var_dump($row);` should display?

**Comment by itrascastro** [comment]
Yes. Sorry, I mean \PDO::FETCH_OBJ. I was confused because I was thinking on ASSOC as an object, but it clearly wasn't.

My confusion becomes because in a previous method current() returns to me an Object:

public function findAll()
    {
        $rowset = $this->db->query('SELECT * FROM User', Adapter::QUERY_MODE_EXECUTE);

        $users = new \ArrayObject();

        $count = $rowset->count();

        for ($i=0; $i < $count; $i++) {
            $row = $rowset->current();
            $user = new User($row->id, $row->email, $row->password, $row->role, $row->date);
            $users->append($user);
            $rowset->next();
        }

        return $users;
    }

In this case I take an object using current. But they are different classes:

- Zend\Db\Adapter\Driver\Pdo\Result
- Zend\Db\ResultSet\ResultSet

The second one is using FETCH_OBJ.

So nothing more to say here, only it will be good if we could also use FETCH_OBJ in Zend\Db\Adapter\Driver\Pdo\Result for current() method.

Thank you.
