### ISSUE TITLE
AbstractOptions no longer camel casing methods names.

### ISSUE THREAD

**Issue by iamtommetcalfe** [zendframework/zf2#7155]
When checking if methods exists from array in AbstractOptions.php, ucwords is no longer applied resulting in BadMethodCallException which does actually use ucwords.

e.g. https://github.com/zendframework/zf2/blob/b1e9f3bb3ce9cdc925139d98672af40f6b0f33d7/library/Zend/Stdlib/AbstractOptions.php#L101

This is what it used to be - $setter = 'set' . str_replace(' ', '', ucwords(str_replace('_', ' ', $key)));

**Comment by jaapio** [comment]
might be related to the changes in #7006.
But since the build for master is still passing on this point and methods are case insensitive it is probably an other issue.

Could you provide some more info? Like your OS and PHP version. And if possible your options class and the way you are calling it.

**Comment by Ocramius** [comment]
This is invalid: you most probably have a bug somewhere else: http://3v4l.org/94eT9


```php
<?php

class Foo { function BAR() {}}

var_dump(method_exists(new Foo, 'bar'));
var_dump(method_exists(new Foo, 'BAR'));
```

Please open a different issue once you figured out the exact problem.

**Comment by iamtommetcalfe** [comment]
I am passing an array of options to setFromArray -
e.g 
[
"name" => "Price Range",
"range" => "0.00-10.00"
];

Because __set no longer uses ucwords, it is looking for "getname" rather than "getName". As method_exists is case sensitive this now throws an exception.

**Comment by iamtommetcalfe** [comment]
Apologies for this.
Turns out the array I was passing through had a space in one of the array keys.

It would have been helpful if the exception uses the $setter variable defined previously instead of displaying a differently formatted setter. Because the exception indicated that it was looking for "getName" I went down a different route of debugging. 

Ideally it should be

throw new Exception\BadMethodCallException(sprintf(
                'The option "%s" does not have a matching "%s" setter method which must be defined',
                $key,
                $setter
            ));

**Comment by Martin-P** [comment]
It is indeed strange the exception uses a completely different setter which is not even used in the check in [`Zend\Stdlib\AbstractOptions` line 103](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/Stdlib/AbstractOptions.php#L103).
```php
$setter = 'set' . str_replace('_', '', $key);
```
versus
```php
'set' . str_replace(' ', '', ucwords(str_replace('_', ' ', $key)))
```

**Comment by Martin-P** [comment]
@iamtommetcalfe I created PR #7157 for a more accurate exception message.
