### ISSUE TITLE
ServiceManager does not resolve aliases when attempting to create objects via an abstract factory

### ISSUE THREAD

**Issue by ashireman** [zendframework/zf2#7165]
Example config should be as follows to reproduce:

```php
//module.config.php
    'abstract_factories' => array(
        'Custom\Factories\MyWidgetAbstractFactory',
    ),
    'aliases' => array(
        'widget-alias-string' => 'Somename\Type\MyWidgetName',
    )
```

```php
//SomeFactory.php
$myWidgetObject = $sm->get('widget-alias-string');
```

The class name 'Somename\Type\MyDesiredName' doesn't truly exist and may be overridden by later services using the same class name. So when the ServiceManager attempts to create the class it will not find any entries and will look to abstract factories to determine if any of them can create the object. However, only the alias name ('widget-alias-string') is passed to the abstract factory 'canCreateServiceWithName()' method even though we would desire that the full name ('Somename\Type\MyWidgetName') is what's really given to the AbstractFactory method.

I'm not certain of the best solution or the impacts of implementing such a check. If there was a check to see if the requested service has an alias I can see that if many objects hit this code that's a lot of checks to resolve an alias that may not be needed. But implementing such a check should be fairly easy.

Another option would be to attempt to resolve all aliases to an entry in factories or abstract factories when they are added by config so that the resolution has already happened. When the configuration is cached the performance hit should be minimal. But I see implementing this solution as more complex than the solution above. I also don't know what would happen if the alias resolved to a closure rather than a string pointing to a class.

Whether this is a bug and needs fixing, or, it's a wontfix that needs documenting I'll try to help with whatever direction is chosen.

**Comment by Ocramius** [comment]
@ashireman this is actually a wontfix that will only be fixed in 3.x. It's also a duplicate, but I can't find the related issue.

The fact is that we need to get rid of service normalization in 3.x.

**Comment by ashireman** [comment]
I kinda figured it would be something like this. 

I also couldn't find anything related, but if I come across it I'll reference this. Does this need a 'wontfix' label as well? Feel free to close.

**Comment by Ocramius** [comment]
I think I'll leave it open as a reminder of how much service normalization is being a pain :-)

I tagged it for `3.0.0` anyway.

**Comment by Maks3w** [comment]
Aliases are resolved at config time on SM v3
