### ISSUE TITLE
Cache in Paginator module supports only `Memory` and `Filesystem` adapters

### ISSUE THREAD

**Issue by hver** [zendframework/zf2#7174]
There are problems with cache in Paginator module `Zend/Paginator/Paginator.php`.
The `Paginator` class uses for caching an `Adapter` object, which implements `Zend\Cache\Storage\StorageInterface`. But this class uses methods from `Adapter` which are not declared by `StorageInterface`:
* Lines 372, 710: `Zend\Cache\Storage\IterableInterface::getIterator()`
* Lines 375, 713, `Zend\Cache\Storage\TaggableInterface::getTags()`
* Line 620, `Zend\Cache\Storage\TaggableInterface::setTags()`

This is a problem, because only `Memory` and `Filesystem` cache adapters implement `IterableInterface` and `TaggableInterface`. Other adapters will throw a runtime error i.e. `Apc`, `Dba`, `Memcached`, `Redis`, `Wincache`, `XCache`, `ZendServerDisk`, `ZendServerShm`.

I think, the only possibility is to rewrite the cache handling in `Paginator` module, so it doesn't require additional interfaces. Otherwise, we should explicitly mention that only an instance of `Memory` or `Filesystem` adapter is allowed to be used as cache in Paginator.

**Comment by Ocramius** [comment]
Absolute links to code references:

 - https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L372
 - https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L710
 - https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L375
 - https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L713
 - https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L620

**Comment by hver** [comment]
These additional interfaces are only used by two methods:
* `getPageItemCache()` https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L705
* `clearPageItemCache()` https://github.com/zendframework/zf2/blob/9ee2075758265876b294a14287c135c63ff241f7/library/Zend/Paginator/Paginator.php#L364
Iterator is used to get all elements from the cache, and tags are used to distinguish between paginator and other entries. But I don't really understand, why the complicated tags logic is needed here. Couldn't we just make it simpler and check that each cache element key starts with `self::CACHE_TAG_PREFIX` for namespacing? I'll make a small example today.

**Comment by Ocramius** [comment]
@hver beware that the entire caching mechanism is due to legacy bits since the port from zf1: the fact that the cache is static is already a big concern.

**Comment by hver** [comment]
@Ocramius I have removed the dependencies from `TaggableInterface`. But as you told, I'm not sure if the removed tags logic were there due to backwards compatibility.
I still have no idea how to get rid of `IterableInterface` dependency. `StorageInterface` provides no possibility to gel _all_ cache items.

**Comment by marc-mabe** [comment]
@hver The paginator component needs to be refactored to well handle caching:

* move caching support from `Zend\Paginator\Paginator` into specific adapters to solve auto generation of cache key currently based on `spl_object_hash` or `serialize`
* reduce caching mechanism to only use basic methods `getItem` / `setItem` / ...
  * cleaning cache items is up to the configured cache adapter and/or to the user
  * means the user can use cache storage specific features to remove more than one item

**Comment by marc-mabe** [comment]
@hver I would be happy to see a PR (marked for ZF3 as it's an BC break) addressing this but I don't have enough time

**Comment by hver** [comment]
@marc-mabe I'll try to refactor the `Zend\Paginator\Paginator`. (Because of my vacation, it will take some time)
