### ISSUE TITLE
Possible bug in Zend\Log\Writer\FirePhp::__construct

### ISSUE THREAD

**Issue by chadicus** [zendframework/zf2#7202]
It seems to me that [this](https://github.com/zendframework/zf2/blob/master/library/Zend/Log/Writer/FirePhp.php#L45) condition should be reversed?

**Comment by Martin-P** [comment]
If that is the case the following existing test should trigger that exception: [`ZendTest\Log\Writer\FirePhpTest`](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/tests/ZendTest/Log/Writer/FirePhpTest.php#L76-L91).

**Comment by chadicus** [comment]
Okay, i understand what is happening now. the use statement at line 17 is trying too load a class with a relative namespace path. this is invalid.  therefore the FirePhpInterface does not exist. and the check fails. If you use the full namespace path the tests will fail

**Comment by Martin-P** [comment]
Checking for a non existing interface, nice catch :+1:
