### ISSUE TITLE
[zf3] db

### ISSUE THREAD

**Issue by kittencup** [zendframework/zf2#7207]
ZF3 needs better db,beacuse doctrine does't work well

**Comment by grizzm0** [comment]
You might want to leave a bit more info than that if you want to be taken serious.

**Comment by Ocramius** [comment]
> doctrine does't work well

Please report issues with doctrine on http://www.doctrine-project.org/jira/

**Comment by harikt** [comment]
@Ocramius this is not really with doctrine :) . Basically he was looking for some improvements for Zend Db. I wonder whether zend db is removed in version 3 to close the same :) .
