### ISSUE TITLE
Missing link between array configured elements, and Factories

### ISSUE THREAD

**Issue by Saeven** [zendframework/zf2#7212]
I'm trying to create a custom form element, fundamentally everything works -- but I'd like to intake 'name' properly.  Let me explain:

```php
    use Application\Form\Element\Custom;
    
    class CustomForm extends Form
    {
         public function init(){
             $this->add([
                'name' => 'themagicname', 
                'type' => Custom::class,
             ]);
         }
    }
```

I have a form that instantiates a Custom element, the custom element is mapped in my `module.config.php` as:

```php
    use Application\Form\Element\Custom;
    use Application\Factory\Form\Element\CustomFactory;

    return [
       //...
       'form_elements' => [
            'factories' => [
                Custom::class => CustomFactory::class,
            ],
        ],
       //...
    ];
```

The factory looks like this, and gets fired properly:

```php
    class CustomFactory implements Factory
    {
    
        public function createService( ServiceLocatorInterface $serviceLocator )
        {
            /**
             * @var \Doctrine\Common\Persistence\ObjectRepository $userRepository
             * @var \Zend\InputFilter\InputFilterPluginManager $serviceLocator
             */


            // bunch of factory-ish things here

            return new Custom( 'helpppp', ... );
        }
    }
```

Now the conundrum:  Where I wrote 'helpppp', one would ideally transport 'themagicname' that was passed during creation at the Form level.  How does that config array, get ferried over to the factory? I've tried `MutableCreationOptionsInterface` but it doesn't seem to apply here.

It'd be ideal to give Factories access to options, since the wiring is possible?

**Comment by monkeyphp** [comment]
In a FactoryInterface class - I managed to pull what I believe are the required values `creationOptions` using Reflection (I'm sorry). This property is protected and has no getter method.

```php
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $reflectionObject = new \ReflectionObject($serviceLocator);
        $creationProperty = $reflectionObject->getProperty('creationOptions');
        $creationProperty->setAccessible(true);
        $creationOptions = $creationProperty->getValue($serviceLocator);
        
        // ... do something with $creationOptions array
    }
```
Either this is a terrible terrible thing to do... or a public getter method would be useful

**Comment by grizzm0** [comment]
The name supplied in $this->add() already overrides the name given in the constructor. So there's really no need to pass it along.
