### ISSUE TITLE
[3.0] RFC: Split branches with 2.x and 3.x please

### ISSUE THREAD

**Issue by netroby** [zendframework/zf2#7218]
Split branches with 2.x and 3.x please.

I can see many issue opened for 3.0. the main zf2 branch only have two main branch, master and develop, 

Should we split 2.x and 3.x into two branches? that we can easily keep watching the 2.x stable branch and 3.x develop branch ?

**Comment by harikt** [comment]
@netroby http://framework.zend.com/blog/announcing-the-zend-framework-3-roadmap.html . If I understand correctly 2.4 needs to be released. Then it will be split into individual components, and there after 3.0 development starts. ( Was also reading something about 2.5 may or may not need. Things are still not so clear though )

**Comment by netroby** [comment]
master -> this branch will catch up the latest stable (3.0 stable ?)
develop -> this branch will match the 3.x develop 
2.x-stable -> this branch will match 2.x stable branch

split into different branch can be friendly to developers who want to track the product  (2.x was heavily using )

**Comment by gianarb** [comment]
In this moment we are discussing to find best approach.. But the next step is 2.4

**Comment by weierophinney** [comment]
@netroby It makes no sense at this time to split into separate branches. The repo will look quite different once we split out the components, and any on-going 2.X development after 2.4 will be security and critical bugfixes only — which we can apply to branches checked out from the latest release tags.
