### ISSUE TITLE
Db\Sql\Select.php processJoins quote identifier error

### ISSUE THREAD

**Issue by conyg** [zendframework/zf2#7222]
The **processJoins** method is calling **quoteIdentifierInFragment** with an array of **safeWords**.
In the list of safeWords the AND, OR and BETWEEN should be surrounded by spaces (or whitespaces).
Otherwise the return string may be compromised. Here is an example from [SpekCommerce](https://github.com/speckcommerce) :
input - **catalog_category_website.category_id = catalog_category.category_id**
output - **\`catalog_categ\`or\`y_website\`.\`categ\`or\`y_id\` = \`catalog_categ\`or\`y\`.\`categ\`or\`y_id`**

the line:
: $platform->quoteIdentifierInFragment($join['on'], array('=', 'AND', 'OR', '(', ')', 'BETWEEN', '<', '>'));
should be replaced by:
: $platform->quoteIdentifierInFragment($join['on'], array('=', ' AND ', ' OR ', '(', ')', ' BETWEEN ', '<', '>'));

**Comment by tdroenner** [comment]
I can confirm this bug.

**Comment by weierophinney** [comment]
Fixed with #7275
