### ISSUE TITLE
DateStepValidator has timing issue

### ISSUE THREAD

**Issue by pdobrigkeit** [zendframework/zf2#7229]
Our application has some long running imports which showed seemingly randomly errors with the `DateStepValidator`. I have been able to track them down and wanted to write a test for it, but not sure how. 

Let me explain what happens and my solution proposition:
I am using the `Zend\Form\Element\Date` object, which by default configures a step validator and returns it. It has a format of `Y-m-d`, so by default the validator will have a `baseValue` of `1970-01-01`

Now I submit a value like `2015-02-01`. In the `isValid` function (lines 201, 202) those strings are converted to a `DateTime` object. 

        $valueDate = $this->convertToDateTime($value, false); // avoid duplicate errors
        $baseDate  = $this->convertToDateTime($this->baseValue, false);

Now the seemingly random event can happen. Because of the format of `Y-m-d` the created `DateTime` object will carry the current time for `H:i:s` and if in between those two lines a second passes the validation will fail, because now there is a diff with `00:00:01` in the time part.

Now my solution is to change the `convertString` method of `DateStep` to use the `!` operator in front of the format which overwrites all nonset time parts with `0`.

**Comment by texdc** [comment]
I think you just need to modify your custom format that you're using to configure the validator.  `!Y-m-d` or `Y-m-d|` should give you the results you need.

**Comment by Martin-P** [comment]
@pdobrigkeit This looks like almost the same text as in your own PR #7199?

**Comment by pdobrigkeit** [comment]
I wasn't aware that my PR was still active and discussed :)
