### ISSUE TITLE
Please update Component_Zend* repositories

### ISSUE THREAD

**Issue by DavidPrevot** [zendframework/zf2#7243]
Please, synchronize the individual Component_Zend* repositories (with tags) so that individual components can be downloaded via GitHub and probably Packagist too.

Regards

David

**Comment by weierophinney** [comment]
They already are; I think they're just missing the latest tags from last week, in which case, they'll be updated soon. Synchronization takes many hours, and is often error-prone, which is why we do not coordinate the component releases with the framework release currently. After the 2.4 release, we will be moving component development to their own repositories, which will alleviate this problem entirely.

**Comment by DavidPrevot** [comment]
Hi,

Le 25/02/2015 16:11, weierophinney a écrit :
> They already are;

Unlikely: the last commit on Component_ZendDb is from January 14:

	https://github.com/zendframework/Component_ZendDb

> I think they're just missing the latest tags from last week, in which case, they'll be updated soon.

How soon? 2.3.5 and 2.2.10 have been released on Febrary 18, and fix a
security issue. It would be nice to see them available via Composer and
GitHub. Latest versions are still 2.3.4 and 2.2.9 (or -dev from January 14):

	https://packages.zendframework.com/
	https://packagist.org/packages/zendframework/zend-db
	https://github.com/zendframework/Component_ZendDb/releases

> Synchronization takes many hours, and is often error-prone, which is why we do not coordinate the component releases with the framework release currently.

It’s been 10 days since this issue was closed without a fix, and
18 days since the security issues has been disclosed, that’s a fair
number of hours already.

> After the 2.4 release, we will be moving component development to their own repositories

I’ve seen that in the ZF3 roadmap, that sounds appealing, thanks
(especially with my downstream hat: synchronizing several Zend
components in the Debian archive also is error-prone and takes a few
hours too).

Regards

David

**Comment by Ocramius** [comment]
I simply didn't get to run the synchronization (yet). Will try doing so
today, once I have a stable connection.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by dennisdegreef** [comment]
I don't want to push anyone, I think everyone contributing to anything open source is awesome.
But I am concerned about the fact that this regards a security issue in a widespread package, and this issue is opened 23 days ago.

Could somebody take a look? Thanks a lot!

**Comment by DavidPrevot** [comment]
Thanks for the fix!

**Comment by dennisdegreef** [comment]
Thanks!!
