### ISSUE TITLE
Zend\Mvc\Router\Http\TreeRouteStack::match does not inform request of baseUrl

### ISSUE THREAD

**Issue by steverhoades** [zendframework/zf2#7246]
When a baseUrl is defined on the router, the request object is never informed.  

For instance:
```
$router = $sm->get('Router');
$router->setBaseUrl('/base');
```
When making a request to:  http://www.somedomain.com/base/some_path/1
```
// onDispatch
$uri = $request->getUri();
$fullPath = $uri->getPath();
$path = substr($fullPath, strlen($request->getBasePath()) + 1);
echo $path;

Result:
base/some_path/1

Expected Result:
some_path/1
```

see: https://github.com/zendframework/zf2/blob/master/library/Zend/Mvc/Router/Http/TreeRouteStack.php#L256-L258

It appears to me that the solution is to have the Router set the baseUrl on the request object.  This has solved my specific issue.  Unfortunately, I don't fully understand the consequences of this yet, perhaps someone else can chime in here?  I can provide a PR if needed.
```
        if ($this->baseUrl === null && method_exists($request, 'getBaseUrl')) {
            $this->setBaseUrl($request->getBaseUrl());
        } else if(method_exists($request, 'setBaseUrl')) {
            $request->setBaseUrl($this->baseUrl);
        }
```

**Comment by DASPRiD** [comment]
The router should never alter the request object. You can manually set the base URL on the request object if you have to. Closing.

**Comment by steverhoades** [comment]
DASPRID thanks for the quick response.  

For anyone coming after me, if you are adding a base_url to your Router you will likely want to add it to the request as well.  Here is my onBoostrap method for my baseUrl module.  Otherwise some 3rd party module functionality (such as AssetManager) won't work properly.

```
public function onBootstrap(MvcEvent $e)
{
    $application     = $e->getApplication();
    $eventManager    = $application->getEventManager();
    $serviceManager  = $application->getServiceManager();

    /* Set basedir if it's set in module config */
    $config = $serviceManager->get('Config');    
    $router = $serviceManager->get('Router');
    if(!empty($config['base_url'])) {
        $router->setBaseUrl($config['base_url']);
    }

    $eventManager->attach(MvcEvent::EVENT_ROUTE, function($e) use ($config) {
        $request = $e->getRequest()->setBaseUrl();
        if(!empty($config['base_url'])) {
            $request->setBaseUrl($config['base_url']);
        }
    }, 1000);
}
```

**Comment by DASPRiD** [comment]
@steverhoades Just for your information: It should be enough for you to set the base URL on the request object, the router will automatically pick it up.

**Comment by steverhoades** [comment]
DASPRID, you are indeed correct.  Thanks again for the pointer.  I have updated my example to reflect the working code.
