### ISSUE TITLE
\Zend\I18n\Validator\PostCode GB regex fails to assert start of string

### ISSUE THREAD

**Issue by SorX14** [zendframework/zf2#7250]
The GB PostCode regex string fails to assert start and end position causing passes on incorrect post codes.

The code appears to add a `^` and `$` onto the regex string when comparing, but for the GB string, there are multiple regex strings `|`'d together. This means that the 'middle' expression fails to assert start of string.

`Highlighted` text below shows matched text with existing regex. As you can see, a few post codes are allowed even though there isn't a full match.

`CA3 5JQ`
`GL15 2GB`
`GL152GB`
E`CA32 6JQ`
se5 0eg
`SE5 0EG`
E`CA3 5JQ`
E`CA3 5JQ`
`WC2H 7LT`a

**Comment by weierophinney** [comment]
@SorX14 Any chance you'd be willing to provide a patch?

**Comment by SorX14** [comment]
Fairly confident I haven't followed the correct protocol, but I just created a pull request: https://github.com/zendframework/zf2/pull/7264

**Comment by weierophinney** [comment]
Fixed with #7264
