### ISSUE TITLE
Zend Framework in bower

### ISSUE THREAD

**Issue by danilolutz** [zendframework/zf2#7257]
Please, provide the Zend Framework in bower repository!

**Comment by Maks3w** [comment]
Why? Bower is a front-end package manager but ZF is for backend.

**Comment by FraGoTe** [comment]
Bower is for frontend frameworks, zend is backend framework. You should use composer.

**Comment by froschdesign** [comment]
> Bower is a package management system for client-side programming on the World Wide Web.

https://en.wikipedia.org/wiki/Bower_(software)

**Comment by danilolutz** [comment]
Oh! I see, i'm sorry! Thank you!
