### ISSUE TITLE
Date element does not validate in some timezones

### ISSUE THREAD

**Issue by Redigast13** [zendframework/zf2#7261]
I use a date element in my form. It doesn't validate because of DateStep validator. DateStep validator is a default validator in date element in ZF2. When I submit a form I have this validation error: "The input is not a valid step"
Here is a configuration of my Date element in form init() function:
$this->add([
    'name' => 'test',
    'type' => 'Date',
    'options' => [
        'label' => 'test',
    ],
]);
As you can see there is nothing special in this configuration.
Here is an example with incorrect work of DateStep validator:
date_default_timezone_set('Europe/Moscow');
$validator = new \Zend\Validator\DateStep(array(
    'format'    => 'd-m-Y',
    'baseValue' => date('d-m-Y', 0),
    'step'      => new \DateInterval("P1D"),
));
$result = $validator->isValid('12-08-2014'); // $result == false
This validation error is because DateStep validator use DateTime::diff() method. Here is an another example:
date_default_timezone_set('Europe/Moscow');
$datetime1 = new DateTime('2014-08-12');
$datetime2 = new DateTime('1970-01-01');
$interval = $datetime1->diff($datetime2);
In this example $interval has 44 years, 7 months, 10 days, 23 hours(!), 0 minutes, 0. 23 hours is the reason why DateInterval validator works incorrectly

**Comment by Victory** [comment]
I am working on this a bit. Here is a test to that brakes on my branch and an article about the "wintertime".

https://github.com/Victory/zf2/commit/6cfba15d496a87b1131ea6e50e92aa42dc33f17e

http://sputniknews.com/russia/20141026/194606015/Russia-Turns-Clocks-Back-to-Winter-Time.html
