### ISSUE TITLE
Multiple navigations with navigation view helper not working properly

### ISSUE THREAD

**Issue by benjaminhirsch** [zendframework/zf2#7272]
Hi there,

I’m currently working on a project, which need multiple navigations. To achieve this, I’m using a container (array), configured in the global.conf with multiple keys.

```php
'navigation' => array(
    'default' => array(
        array(
            'label' => _('Lorem ipsum'),
            'route' => 'exampleroutename/default',
            'controller' => examplecontroller,
            'class' => 'glyphicon-credit-card',
            'pages' => array(...)
    ),
    'leasecertificate' => array(
        array(
            'label' => _('Lorem ipsum'),
            'route' => 'exampleroutename/default',
            'controller' => examplecontroller,
            'action' => 'view',
            'class' => 'glyphicon-list'
        )
    ),
)
```

Then I’ve configured in the module.config.php under service_manager/factories both navigations, the default one, which is a bigger one with multiple pages and childrens and the second one, which is my own class that simply extends the DefaultNavigationFactory and return the key "leasecertificate".

```php
'service_manager' => array(
    'factories' => array(
        'navigation' => 'Zend\Navigation\Service\DefaultNavigationFactory',
        'leasecertificate' => 'Christoph\Navigation\Service\LeasecertificateNavigationFactory',
    )
)
```

Now in the view, I’m rendering 3 navigations, the first and second one are working fine, but when I try to render the third one, nothing happens. I’ve tried different options etc. nothing helped. Then I tried to clone the navigation viewhelper on top of the view before I start to render the rest of the navigations, now it works. I’m wonder if this behaviour is normal?

**First menu**
```php
<?php
echo $this->navigation('navigation')->menu()
    ->setMinDepth(1)
    ->setMaxDepth(1)
    ->setRenderParents(false)
    ->setUlClass('btn-red-list')
    ->render();
?>
```

**Second menu**
```php
<?php
$this->navigation('navigation')->menu()->setPartial(path/to/partial/subsubmenu');
echo $this->navigation('navigation')->menu()->render();
?>
```
**Third menu**
```php
echo $this->navigation('leasecertificate')->menu()->render()
```
In this case, the third menu is not being rendered and no error occours.

But when i clone the navigation view helper object on top of the view before I start to render the other menus, the third menu works.

**Example**
```php
<?php 
// Clone the navigation view helper on top of the view
$navclone = clone $this->navigation('leasecertificate'); 
?>

...render menu 1 and 2

// Then the third menu is being rendered
echo $navclone->menu()->render()

```
I'm just asking myself if this is a normal behavior, I'm doing something wrong  or is this a bug?

**Comment by froschdesign** [comment]
The `navigation` view helper is a proxy helper. During the first call, the proxy helper inject the given container into concrete helper. This container is used for every rendering.

If you want to use different containers, then set the container (name) to the concrete helper:
```php
// First container
echo $this->navigation('navigation')->menu();
echo $this->navigation()->menu();

// Second container
echo $this->navigation()->menu('leasecertificate');
```

**Comment by benjaminhirsch** [comment]
You're right, and I have already tried your example before your post, but forgot the set ->setMinDepth(0)  for the third menu. In the first menu I have set ->setMinDepth(1), this prevents the third menu from being rendered. So everything works as intended. Thank you. :)

**Comment by froschdesign** [comment]
You're welcome.

**Comment by sandrokeil** [comment]
@benjaminhirsch FYI with ZF 2.4 you can use the NavigationAbstractServiceFactory instead your LeasecertificateNavigationFactory. See #7245

**Comment by benjaminhirsch** [comment]
Good to know and thank you for the hint! :)
