### ISSUE TITLE
It is impossible to clear form collection data.

### ISSUE THREAD

**Issue by Redigast13** [zendframework/zf2#7278]
I have a ZF2 form with form collection element. The name of collection element is "roles". If I do:

`$form->setData(array('roles' => array('admin', 'moderator')));`

And then I do:

`$form->setData(array('roles' => array())); // it does not work`

Then if we do:

`$form->get('roles')->getCount(); // 2`

There will be still 2 elements. I need to clear elements from this collection.

It is very important for me because I use doctrine 2. So I should bind non-empty entity before I set data to the form. For instance:

```php
$form->bind($entity); // $entity->roles is not empty
$form->setData($someData); // $someData['roles'] is empty array
if ($form->isValid()) {
    $form->get('roles')->getCount(); // 2(!) it is not empty!
    saveToDb($entity);
}
return $form;
```

**Comment by adamlundrigan** [comment]
Fixed in https://github.com/zendframework/zend-form/pull/14
