### ISSUE TITLE
disabled checkbox

### ISSUE THREAD

**Issue by GhTigran** [zendframework/zf2#7286]
When adding 'disabled' => true to Form Checkbox element attributes, in view file disabled is added to input checkbox element only, but it's not added to the hidden element as well, which will cause unintentional submittion hidden value.

Solution: When both use_hidden_element and disabled are set to true on checkbox form element. Add disabled attribute to both input checkbox and associated hidden element while drawing the form.

**Comment by Martin-P** [comment]
> Solution: When both use_hidden_element and disabled are set to true on checkbox form element. Add disabled attribute to both input checkbox and associated hidden element while drawing the form.

Although I understand what you are saying, adding a attribute `disabled` to the hidden input does fix anything. Anyone who knows how to change the value of a hidden input can also remove the `disabled` attribute. You should never trust user input if you want a safe application.

**Comment by froschdesign** [comment]
> Add disabled attribute to both input checkbox and associated hidden element while drawing the form.

Do not add the hidden element.

**Comment by Martin-P** [comment]
@froschdesign :+1: I did not even think of that :smile:

**Comment by Martin-P** [comment]
@froschdesign On second thought, that also does not fix the issue. The application itself should know when to ignore elements and not by (lack of) user input :wink: 

It seems this already covered in [`Zend\Form\Fieldset::bindValues()`](https://github.com/zendframework/zf2/blob/ff04baf16fdd958ff0eba26143de3ef014dc4488/library/Zend/Form/Fieldset.php#L588-L593).

@GhTigran Can you provide a unittest where data is *not* ignored when a checkbox is disabled?
