### ISSUE TITLE
Missing dependencies on Zend\View Standalone Component

### ISSUE THREAD

**Issue by manuakasam** [zendframework/zf2#7288]
Assuming the following - in my opinion bare-minimum - way to use the `Zend\View`-Component standalone, I think there are missing hard dependencies:

```php
$templateResolver = new TemplateMapResolver([
    'foo/bar' => __DIR__ . '/view/foo/bar.phtml'
]);

$viewRenderer = new PhpRenderer();
$viewRenderer->setResolver($templateResolver);

$vm = new ViewModel([
    'message' => 'Hello FooBar'
]);

echo $viewRenderer->render(
    $vm->setTemplate('foo/bar')
);
```

First off, the `PhpRenderer` requires a `HelperPluginManager`. As such, it needs to be extended from the `AbstractPluginManager` which is a dependency within `zendframework/zend-servicemanager`.

Adding `zendframework/zend-servicemanager` you're required to also include `zendframework/zend-filter` due to the requirement of the `FilterChain` within `PhpRenderer#424`.

Now I may be missing things to disable those features, but from the dummy point of view imo those components are hard dependencies and not just `require-dev`.

**Comment by gianarb** [comment]
In my opinion ZF have a big big big problems of dependencies in all your components :) In this moment we are in a loop because remove it require a BC break..  
@manuakasam yesterday I have wrote a [small article](http://gianarb.it/blog/the-price-of-modularity/) about this problem. If you have a minutes can you share your feedback? Thanks..

**Comment by weierophinney** [comment]
@manuakasam We've setup `zend-servicemanager` as a _suggested_ component. It's _required_ if you use the `PhpRenderer`, but if you don't (for instance, if you are implementing your own renderer, or using the `JsonRenderer`), it's not. We're trying to be quite conservative in terms of what we consider a hard requirement, as not every feature of a given component will be used by every user.

**Comment by gianarb** [comment]
@weierophinney I have a question, this approach is not very confusional?
Why zend-servicemanager is not a dependency of this component? 

Thanks! :+1:

**Comment by manuakasam** [comment]
Thanks for the explanation of why the SM isn't a hard dependency. I
neglected to check with the JsonRenderer.

In my opinion this kind of stuff absolutely requires documentation and at
least as far as \View is concerned im going to cover this.



Gianluca Arbezzano <notifications@github.com> schrieb am Mo., 23. März 2015
um 20:52 Uhr:
