### ISSUE TITLE
[ZF3/2.5] [RFC] Pull out all interfaces into separate namespace

### ISSUE THREAD

**Issue by carnage** [zendframework/zf2#7297]
An idea I had for when the framework gets split into components was to pull out all the interfaces into their own separate package(s) which can be depended upon by other components reducing the coupling between them. It would be then perfectly possible to write an adapter for a symphony component to make it conform with an ZF interfaces and use it in place of the ZF dependancy it would otherwise have.

Thoughts?

**Comment by weierophinney** [comment]
No, we won't do this. We decided a very long time ago that the interfaces for a component should be next to the component. This is even more important when we split the components into their own repositories: it reduces dependencies, keeps context where it will be examined, and defines the contracts for the component itself.
