### ISSUE TITLE
Update zend-db packagist to v2.3.5 for ZF2015-02

### ISSUE THREAD

**Issue by dennisdegreef** [zendframework/zf2#7304]
A security advisory has been put out for Zend\Db in combination with PostgreSQL.
http://framework.zend.com/security/advisory/ZF2015-02

It seems that the following package has not been updated yet.
https://packagist.org/packages/zendframework/zend-db

Could a maintainer press 'Force update' on the packagist package? Or maybe look at why this package didn't update?

Thanks in advanced!

**Comment by lku** [comment]
See #7243

**Comment by dennisdegreef** [comment]
Ah thanks, I've looked and searched around... I guess I've missed that one...

**Comment by lku** [comment]
As packages were updated a few days ago, this can be closed.
