### ISSUE TITLE
$HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by fsvxavier** [zendframework/zf2#7316]
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />

I using php 5.6, nginx and ZF2.3.5

**Comment by Bittarman** [comment]
This is not related to ZF, and is as documented in the error message related to your php.ini settings.

**Comment by fsvxavier** [comment]
But Zend\Feed\PubSubHubbub using

/**
     * Return the raw body of the request
     *
     * @return string|false Raw body, or false if not present
     */
    protected function _getRawBody()
    {
        $body = file_get_contents('php://input');
        if (strlen(trim($body)) == 0 && isset($GLOBALS['HTTP_RAW_POST_DATA'])) {
            $body = $GLOBALS['HTTP_RAW_POST_DATA'];
        }
        if (strlen(trim($body)) > 0) {
            return $body;
        }
        return false;
    }

 and generating error in Ajax request.
