### ISSUE TITLE
Make $data an optional parameter for deleteList

### ISSUE THREAD

**Issue by evsheffield** [zendframework/zf2#7321]
I updated the version of ZF2 my project uses to 2.3.6 today and noticed that my REST API had broken because `$data` was added as a required parameter to the `deleteList` function in `AbstractRestfulController.php`. (see [this commit](https://github.com/zendframework/zf2/commit/0a701dc423e5fa25736c5c946bf1e6a8fa4688a6))

This parameter should be made optional in order to maintain compatibility with applications updating from a previous version of the framework. If not, at the very least there should be a note in the changelogs about a breaking change.

**Comment by Martin-P** [comment]
It looks like something went wrong with the release of ZF 2.3.6 because the commit you are referring to is marked for ZF 2.4.0. Ping @weierophinney

**Comment by exptom** [comment]
This is reverted in 2.3.7 and working correctly again.
