### ISSUE TITLE
[Filter/OpenSSL] Multiple publickeys, only last is used.

### ISSUE THREAD

**Issue by barryvdh** [zendframework/zf2#7323]
From the docs:

> __Supported Options__: _public:_ Only OpenSSL. The public key of the user whom you want to provide the encrypted content. You can give multiple public keys by using an array. You can either provide the path and filename of the key file, or just the content of the key file itself.

    // of course you can also give the public keys at initiation
    $filter->setPublicKey(array(
       '/public/key/path/first.pem',
       '/public/key/path/second.pem'
    ));

But I can't seem to get this working correctly. I'm using the content of the key directly. 1 key works, but multiple don't.
 - As option, I directly get an error about `is_file` not expecting an array
 - setPublicKey(), only uses the last key because it overrides `$key['public']` in the foreach. (https://github.com/zendframework/Component_ZendFilter/blob/43206c8a7d847ebaff83c1c0b2f7dd8a318313eb/Encrypt/Openssl.php#L167-L187)

What does work:

    $filter = new Zend\Filter\Encrypt(array(
       'adapter' => 'openssl',
    ));
    foreach($keys as $key) {
        $filter->setPublicKey($key);
    }

So either I'm doing something wrong, or the docs or incorrect or the code isn't working as expected.

**Comment by ezimuel** [comment]
@barryvdh The docs is clearly wrong here. Is not possible to specify an array of public keys, even because it makes no sense, why you should set multiple keys? I'll fix the docs removing that sentence. Thanks for reporting!

**Comment by barryvdh** [comment]
Well you need to set multiple keys when you want to encrypt a file for multiple users, so imho setting multiple public keys makes perfect sense..
