### ISSUE TITLE
ServiceLocator in IdentityFactory returns null

### ISSUE THREAD

**Issue by YP28** [zendframework/zf2#7333]
I'm getting this error while trying to use the identity helper in a Controller:
```
Fatal error:  Call to a member function has() on null in /var/www/html/beste/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/Plugin/Service/IdentityFactory.php on line 27
```

I know it's not that the identity is not set, because in my views the identity helper just works as expected. 

Just to be sure, I have set the 'Zend\Authentication\AuthenticationService' in my module.config.php and it returns an instance of the Zend AuthenticationService injected with my own AuthenticationAdapter and the default Session Storage Adapter.

**Comment by Martin-P** [comment]
Where exactly in your controller do you use this controller plugin? I guess the servicelocator is not injected yet at the moment you try to instantiate the controller plugin. This can happen when for example you do this call in `__construct()` of your controller.

See this article for background info: https://juriansluiman.nl/article/139/zf2-why-a-service-is-not-available-in-your-constructor

**Comment by YP28** [comment]
Oh wow, I think that was it. I missed the note that it wasn't available in constructors.
