### ISSUE TITLE
Can i group caching in filesystem cache

### ISSUE THREAD

**Issue by navneetccna** [zendframework/zf2#7338]
My objective to group a cache page wise like 

project1_0
project1_1
project1_2

and than clear all project cache in one hit by project1

**Comment by liufang** [comment]
see https://github.com/zendframework/zf2/blob/master/library/Zend/Cache/Storage/Adapter/Filesystem.php clearByPrefix method

**Comment by navneetccna** [comment]
yes this will work but first i have to group a cache first how will i achieve that ?

**Comment by FabianKoestring** [comment]
Use Namespaces.

http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html

**Comment by navneetccna** [comment]
yes but file cache not provide namespace method setNamespace()

**Comment by Martin-P** [comment]
@navneetccna See [Basic Configuration Options](http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html#basic-configuration-options) on the same page @FabianKoestring is referring to.
