### ISSUE TITLE
Absolute URI doesn't work when link begin with //

### ISSUE THREAD

**Issue by Spawnrad** [zendframework/zf2#7356]
Hi,

The function absolutiseUri in the class Feedset ( Feed/Reader) doesn't work if the link begin with "//".

Example : 

//example.com/feed return http://example.com/example.com/feed

The error is locate here : 

$link = $uri->getScheme() . '://' . $uri->getHost() . '/' . $this->canonicalizePath($link);

Thanks for your help.

**Comment by samsonasik** [comment]
I've created PR #7410 for it

**Comment by samsonasik** [comment]
@Spawnrad btw, can you provide the code that produce the error ? so it can be passed to failing test

**Comment by Maks3w** [comment]
Fix https://github.com/zendframework/zend-feed/pull/2 and released on zend-feed: v2.5.2
