### ISSUE TITLE
Add init() method to all classes instantiated by an service manager

### ISSUE THREAD

**Issue by RalfEggert** [zendframework/zf2#7357]
Both `Zend\Form\Form` and `Zend\InputFilter\InputFilter` provide an `init()` method to customize a form or an input filter. These `init()` methods are called by the relevant service managers named `FormElementManager` and `InputFilterManager`. 

I would like to suggest to standardized this and add `init()` method to other classes which are instantiated by a service manager, e.g. filters, validators, view helpers, controller plugins, hydrators.

What do others think about this suggestion?

**Comment by Martin-P** [comment]
See this blog article: https://mwop.net/blog/2012-07-30-the-new-init.html

**Comment by weierophinney** [comment]
Also, it's really no longer relevant now that we have [delegator factories](http://framework.zend.com/manual/current/en/modules/zend.service-manager.delegator-factories.html), as you can then perform your post-instantiation-but-still-initialization operations on a per-instance basis without needing to change the default factories.

**Comment by RalfEggert** [comment]
Thanks for clarification. I wasn't aware of that. But for consistency wouldn't it be better for ZF3 to standardize this and remove the `init()` methods from both forms and input filters as well? 

I am asking this because many ZF2 beginners ask me why there is `init()` methods only in forms and input filters...
