### ISSUE TITLE
Zend_Validate.php doesn't translate some classes

### ISSUE THREAD

**Issue by dntmartins** [zendframework/zf2#7367]
The classes Size and Extension from Zend\Validator\File, doesn't seem to be translated by the Zend_Validate class in pt_BR.

In the class Extension for example we have:

 protected $messageTemplates = array(
        self::FALSE_EXTENSION => "File has an incorrect extension",
        self::NOT_FOUND       => "File is not readable or does not exist",
    );

but in Zend_Validade (pt_BR) it's just like this:

// Zend_Validator_File_ExcludeExtension
    "File '%value%' has a false extension" => "O arquivo '%value%' possui uma extensão incorreta",
    "File '%value%' is not readable or does not exist" => "O arquivo '%value%' não pode ser lido ou não existe",

It seems that the default template in the classes, like Size and Extension doens't have the "%value%".

I might be wrong

**Comment by weierophinney** [comment]
@dntmartins Would you be willing to attempt a fix?

The translation file is here:

- https://github.com/zendframework/zf2/blob/master/resources/languages/pt_BR/Zend_Validate.php

**Comment by dntmartins** [comment]
@weierophinney I sent a pull request that's waiting for a validation

**Comment by weierophinney** [comment]
Fixed with #7375.
