### ISSUE TITLE
Time formatter helper class

### ISSUE THREAD

**Issue by cHillb3rt** [zendframework/zf2#7371]
It could be useful to have a time formatter helper class for Zf2.

For example I have a seconds value which I want to display for my website.

The result of 62 seconds should be 01:02.
The result of 3602 seconds should be 01:00:02.

I think this could be useful for a time formatter helper class. What do you think?

**Comment by manuakasam** [comment]
Such a feature isn't required as it already ships with php itself

```php
echo gmdate('H:i:s', 7522);
// 02:05:22
```

**Comment by cHillb3rt** [comment]
Ok, that is right.

I close this issue.
