### ISSUE TITLE
[Feature] Allow zend-cache setters to optionally specify TTL

### ISSUE THREAD

**Issue by brettmc** [zendframework/zf2#7387]
I find I tend to create multiple cache instances, with TTL being the only appreciable difference in their configuration (eg a short, medium, and long-term cache).
If one of those doesn't quite fit my needs, I further end up doing things like:
```php
$originalTtl = $cache->getOptions()->getTtl();
$cache->getOptions()->setTtl($someOtherTtl);
$cache->setItem($key, $value);
$cache->getOptions()->setTtl($originalTtl);
```
I propose to be able to:
```php
$cache->setItem($key, $value, $someOtherTtl);
```
The change looks fairly trivial for storage adapters which natively support TTL (most of the "real" ones like memcache, xcache, redis), and maybe can be ignored for others?
I'd be happy to work on this and submit a pull request if there's interest.

**Comment by samsonasik** [comment]
linked with #5386 by @Thinkscape /cc @Ocramius

**Comment by brettmc** [comment]
ah, I didn't find #5386 when searching - given the original implementation there was quite similar to what I am proposing, and it's marked as 'wont fix', I'm probably wasting my time?

**Comment by Thinkscape** [comment]
`Zend\Cache` is opinionated on how you should structure your caches - follows the "container architecture" where you're supposed to have a lot of containers defined, each with pre-set, separate ttl. 

I've wasted time on #5386 trying to explain that there's different approaches to caching, then switched all my apps to faster and more flexible [cachet - https://github.com/shabbyrobe/cachet](https://github.com/shabbyrobe/cachet).
