### ISSUE TITLE
[zf3] Suggestion on wiki RFC split components

### ISSUE THREAD

**Issue by harikt** [zendframework/zf2#7399]
Hi @Maks3w ,

I was looking at your edit on https://github.com/zendframework/zf2/wiki/RFC-split-components

> Copy ZF2 tests/phpunit.xml.dist to {root}/test/phpunit.xml.dist

I feel its good to keep the phpunit.xml.dist on the {root}

and 

> Copy ZF2 tests/Bootstrap.php to {root}/Bootstrap.php

and if Bootstrap.php is for tests to move to 

Copy ZF2 tests/Bootstrap.php to {root}/test/Bootstrap.php

Didn't edited wiki for I don't think that will help anyone.

Thank you.

**Comment by harikt** [comment]
By the way sorry for creating an issue.

Is there any other place than github to discuss these sort of things ?

**Comment by Maks3w** [comment]
Thank you for your comments.

At this moment I don't try to do more than one thing at a time. There are enough complexity with just the split.

Later we may change the structure to other proposals.

Fixed the Bootstrap.php target directory.

**Comment by harikt** [comment]
Why I mentioned keeping phpunit.xml.dist on root is you can run phpunit
from the same place than passing path to phpunit or moving to the test
directory.

Yes, we can come later .

*Hari K T*

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt
