### ISSUE TITLE
[Split] PHP CS Fixer

### ISSUE THREAD

**Issue by gianarb** [zendframework/zf2#7402]
Hi!
In your opinion current flow of cs-fix's check  is good??
In my opinion this check is not on the same level of the tests failure.

I'm follow this project [StyleCI - code](https://github.com/StyleCI/StyleCI) || [StyleCI - service](https://styleci.io/) this is a good idea for a lot of reasons.

* Centralize configuration.. We can manage change of config for all components from single point.
* We can do a different signal if a build failure because a tests is broken or because there is a problem of code style..

In my opinion if I know which PRs don't follow a standard code I can merge them anyway and after a lot of merge I can run CS-fix

**Comment by samsonasik** [comment]
I'm :+1: for it. We can eliminate the .php_cs and php-cs-fixer call in .travis.yml then, right?

**Comment by samsonasik** [comment]
the drawback for it is we still can't exclude folder based on this discussion https://blog.styleci.io/redefining-configuration/#comment-1922515343

**Comment by gianarb** [comment]
Yes but in my opinion this proposal would become more specific, maybe we can extends this flow for other check.. Orchestration of components for the future is a very interesting argument

**Comment by gianarb** [comment]
StyleCI or other server-ci is a very big step maybe in this moment it's too demanding but we can starting from zendframework/coding-standard project to centralize configuration

[see doctrine](https://github.com/doctrine/coding-standard)

**Comment by Maks3w** [comment]
This issue was moved to zendframework/component-split#7
