### ISSUE TITLE
NEVER change a tag after release

### ISSUE THREAD

**Issue by GordonSchmidt** [zendframework/zf2#7404]
Hi,

the release-2.4.0 has been changed afterwards. At least the dependency to phpunit has been updated. Please do not ever change tags after they have been releases.

I quote from semver.org:
"3. Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version."

In this specific case, we already tested our software against the first release of zf2.4.0 with phpunit 3.7. The new release of zf2.4.0 now requires phpunit 4.0, so composer breakes for our software and our tests might not even work with phpunit 4.0.

Please do not change tags afterwards ever again. It is a very bad practice.

Yours sincerely,
Gordon Schmidt

**Comment by stefanotorresi** [comment]
the tag has never been changed, you tested against a release candidate, the phpunit minimum requirement has been bumped in [RC7](https://github.com/zendframework/zf2/commit/99f1561c8eb281556e998a8830b88abe6813c276).

**Comment by Maks3w** [comment]
Also it's weird you have a version conflict with PHPUnit since this component is a DEV dependency.

**Comment by GordonSchmidt** [comment]
Sorry, i'm in the wrong package - please move this issue to Component_ZendTest.

ZendTest has the require to phpunit and its releases was changed afterwards. The release 2.4.0 was on the commit 0d3128e yesterday and on commit 1be7f71 today. The commit 0d3128e is now released as 2.3.7.

**Comment by Maks3w** [comment]
Ok. Yesterday there was an issue with the tagging process on components. For a couple of hours 2.4.0 tag was the same of 2.3.7

**Comment by Ocramius** [comment]
Urgh... is that gone from packagist as well? :-\
