### ISSUE TITLE
Is it possible to add a helper type to the form view helpers through configuration?

### ISSUE THREAD

**Issue by Saeven** [zendframework/zf2#7427]
Hey guys.

Am trying to get a custom helper associated to a custom element.

I've created **Application\Form\Element\DivElement**

```php
namespace Application\Form\Element;

use Zend\Form\Element;

class DivElement extends Element {

    protected $attributes = array(
        'type' => 'div'
    );

}
```

To accompany it, I've created **Application\Form\View\Helper\DivElementHelper**

```php
namespace Application\Form\View\Helper;

use Zend\Form\ElementInterface;
use Zend\View\Helper\AbstractHelper;

class DivElementHelper extends AbstractHelper
{

    public function __invoke(ElementInterface $element = null)
    {
        if (!$element)
            return $this;

        return $this->render($element);
    }

    /**
     * @see \Zend\Form\View\Helper\AbstractHelper::render()
     * @param ElementInterface $oElement
     * @return string
     */
    public function render(ElementInterface $oElement)
    {
        return "<div class='" . $oElement->getAttribute('class')  . "'></div>";
    }
}
```

I've mapped "formdiv" to the helper:

```php
'view_helpers' => [
    'invokables' => [
        'formdiv' => DivElementHelper::class,
    ],
],
```

The last part of the puzzle, seems to be that of getting my formdiv helper into **Zend\Form\View\Helper\FormElement**'s protected $typeMap array. I can't seem to figure what config adds a mapping of:

**'div' => 'formdiv'**

There's a function that seems to be what I want at :
https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormElement.php#L143

Possible to wire into this function at a config level, or am I left to bootstrap method calls?  If impossible, I'd certainly tackle a PR to make this configurable if it's a valid approach overall.

Thanks for your guidance.

**Comment by DASPRiD** [comment]
This is an issue tracker, not a support forum. Please use either the mailing list or IRC (irc://chat.freenode.org/#zftalk).

**Comment by Saeven** [comment]
I realize it's not a support forum, but this seems like an orphaned functionality.  Was hopeful the big brains here would quickly know if it's a forlorn stub or no.

**Comment by DASPRiD** [comment]
There's no config-way right now to add types to the form element helper. If you want, you can make a PR for this.

**Comment by Saeven** [comment]
Thanks DASPRiD.  You are a gentleman.

**Comment by rkeet** [comment]
@Saeven In case this is still something on your wishlist, managed to figure out how to do it. 

I created something similar to yours in the first comment (Element + FormElement (ViewHelper)) and then got stuck. 

Only just now got this working (and still had this tab open ;-) ):

```php
// In Module.php
    public function onBootstrap(MvcEvent $event)
    {
        $serviceManager = $event->getApplication()->getServiceManager();

        /** @var FormElement $formElementViewHelper */
        $formElementViewHelper = $serviceManager->get('ViewHelperManager')->get(FormElement::class);

        $formElementViewHelper->addType('markdown', FormMarkdown::class);
    }
```

Doesn't seem to be a better way as this configuration is not retrieved from module-level configuration but hard-coded in class.
