### ISSUE TITLE
[PHP7] More reserved words

### ISSUE THREAD

**Issue by fabiang** [zendframework/zf2#7435]
There is another RFC which reserves more keywords for usage as class- and interface names and also namespaces. Target PHP version is 7.1.

https://wiki.php.net/rfc/reserve_even_more_types_in_php_7

The RFC is now partially accepted, which means ZF should rename such namespaces, classes and interfaces in the next major version.

**Comment by Maks3w** [comment]
@fabiang Could you elaborate your issue including the problematic classes?

Anyway thank you for your advice

**Comment by fabiang** [comment]
Yes, I'll add a list tomorrow.

**Comment by fabiang** [comment]
As of writing I could find the following classes, interfaces, traits and namespaces in branch "develop":

Class names:
- Zend\Form\Annotation\Object (already deprecated for PHP7)

Interface names:
none

Trait names:
none

Namespaces:
- Zend\Barcode\Object
- Zend\Db\Metadata\Object
- Zend\Permissions\Acl\Resource

Classes affected by namespace change:
- Zend\Barcode\Object\Exception\BarcodeValidationException.php
- Zend\Barcode\Object\Exception\ExceptionInterface.php
- Zend\Barcode\Object\Exception\ExtensionNotLoadedException.php
- Zend\Barcode\Object\Exception\InvalidArgumentException.php
- Zend\Barcode\Object\Exception\OutOfRangeException.php
- Zend\Barcode\Object\Exception\RuntimeException.php
- Zend\Barcode\Object\AbstractObject.php
- Zend\Barcode\Object\Codabar.php
- Zend\Barcode\Object\Code128.php
- Zend\Barcode\Object\Code25interleaved.php
- Zend\Barcode\Object\Code25.php
- Zend\Barcode\Object\Code39.php
- Zend\Barcode\Object\Ean13.php
- Zend\Barcode\Object\Ean2.php
- Zend\Barcode\Object\Ean5.php
- Zend\Barcode\Object\Ean8.php
- Zend\Barcode\Object\Error.php
- Zend\Barcode\Object\Exception
- Zend\Barcode\Object\Identcode.php
- Zend\Barcode\Object\Itf14.php
- Zend\Barcode\Object\Leitcode.php
- Zend\Barcode\Object\ObjectInterface.php
- Zend\Barcode\Object\Planet.php
- Zend\Barcode\Object\Postnet.php
- Zend\Barcode\Object\Royalmail.php
- Zend\Barcode\Object\Upca.php
- Zend\Barcode\Object\Upce.php
- Zend\Db\Metadata\Object\AbstractTableObject.php
- Zend\Db\Metadata\Object\ColumnObject.php
- Zend\Db\Metadata\Object\ConstraintKeyObject.php
- Zend\Db\Metadata\Object\ConstraintObject.php
- Zend\Db\Metadata\Object\TableObject.php
- Zend\Db\Metadata\Object\TriggerObject.php
- Zend\Db\Metadata\Object\ViewObject.php
- Zend\Permissions\Acl\Resource\GenericResource
- Zend\Permissions\Acl\Resource\ResourceInterface

Regex used for search
- `^(trait|class|interface)\s+(Resource|Object|Scalar|Mixed|Numeric)\s+`
- `^namespace\s+([\w\\]*\\(Resource|Object|Scalar|Mixed|Numeric)[\w\\]*)`

Not covered by my search:
- PHPDoc
- Examples
- Test-Files
- Mocked Objects

**Comment by Danack** [comment]
You might want to check the actual implementation before making the list. It is vaguely worded, but my understanding is that the text in the RFC:

> This RFC does not fully reserve them as keywords; it only prohibits their usage as class, interface and trait names. It also prevents them from being used in namespaces.

Means you cannot create a class, interface or trait called `\Object`, or `Zend\Foo\Object`, but Object is allowed to be part of a namespace, so `Zend\Barcode\Object\Codabar` should be fine. I think. Though I could be wrong. \o/

Similarly `Zend\Permissions\Acl\Resource\GenericResource` should be fine.

**Comment by fabiang** [comment]
Yes, you're right. Renaming of the reserved words and "even more" reserved words has already been done for ZF 2.4 for class names and so on. I'll try to figure out what "namespace" means according to the RFCs.

**Comment by fabiang** [comment]
I've verified through testing, that it's possible to use those words as part of the namespace.

**Comment by Maks3w** [comment]
@fabiang What version did you test? RFC still beeing pending of implementation

**Comment by fabiang** [comment]
Against current master, where those words are already reserved. I'll create a new issue if the behavior changes.
