### ISSUE TITLE
Bug on Zend Validator Date

### ISSUE THREAD

**Issue by IgorDePaula** [zendframework/zf2#7438]
I set the validator on form field, and i set the format too. But always show me errors, i dont understand, i seethe code and depuring, on line 172 and 172 has the code:
```php
$errors = DateTime::getLastErrors();
if ($errors['warning_count'] > 0) {
```

But my format is correct, and i put the code 

```php
$errors = DateTime::getLastErrors();
print_r($errors);
exit;
if ($errors['warning_count'] > 0) {
```

the result was

Array ( [warning_count] => 0 [warnings] => Array ( ) [error_count] => 0 [errors] => Array ( ) )

**Comment by Martin-P** [comment]
> I set the validator on form field, and i set the format too. But always show me errors

Please provide more details:
- what format do you use?
- what date do you type in the form?
- what is the error you get?

Perhaps you can post a failing unittest to clarify the issue?

**Comment by IgorDePaula** [comment]
I set format 'd/m/Y'
I type in form '30/04/2015' (brazilian format)
The error: O valor de entrada não parece ser uma data válida

I do a unit test with this validator, and I not received fail. But when I valid a form, eu received this error.

**Comment by IgorDePaula** [comment]
I removed now the validator from annotations entity and the form dont permit my submit. Ireceived the last error, and my annotations on entity are:

```php
/**
     * @var \DateTime
     * @Annotation\Type("Zend\Form\Element\Date")
     * @Annotation\AllowEmpty(true)
     * @Annotation\Filter({"name":"StripTags"})
     * @ORM\Column(name="data_liberacao", type="date", nullable=true)
     */
    public $dataLiberacao;
```

**Comment by IgorDePaula** [comment]
Someone?

**Comment by Martin-P** [comment]
The fact the unittest passes, shows there is no problem with the validator. If the problem is only present when you use a form, there must be something wrong with the code you are using. The only way to find this is to debug your code to see where exactly things go wrong.

Personally I would start at looking at your form and check if the data you pass to the form is what it should be.

**Comment by IgorDePaula** [comment]
Unfortunately, I haven't a form, I use Annotation form builder from zend 2.
Do you want the whole entity?

2015-04-13 10:41 GMT-03:00 Martin-P <notifications@github.com>:

**Comment by Martin-P** [comment]
> Do you want the whole entity?

My suggestion was for you to debug, not to let me do the debugging for you :wink: 

When using annotations you still get an instance of `Zend\Form\Form`. You can debug that object, get all properties, get all messages and so forth.

**Comment by IgorDePaula** [comment]
I think I found the solution: https://juriansluiman.nl/article/125/strategies-for-hydrators-a-practical-use-case. I'll test.

**Comment by adamlundrigan** [comment]
Can this be closed?

**Comment by IgorDePaula** [comment]
Yes, you can close, this is a workaround on source code.
