### ISSUE TITLE
[ZF3] InputFilter does not work well with NULL values

### ISSUE THREAD

**Issue by Thinkscape** [zendframework/zf2#7440]
The ZF2 `InputFilter` does not work well when trying to set null values.

For example, let's build InputFilter with 2 inputs which accept `null`:
````php
[
    'name'              => 'foo',
    'required'          => false,
    'allow_empty'       => true,
    'continue_if_empty' => true,
],
[
    'name'              => 'bar',
    'required'          => false,
    'allow_empty'       => true,
    'continue_if_empty' => true,
]
````
Now let's set the first one to `null`, without modifying the second:
````php
$inputFilter->setData([ 'foo' => null ]);
````

This has been implemented correctly in `BaseInputFilter::validateInputs()`:
````php
            // ------- LINE 254 --------
            // key exists, is null, input is not required; valid
            if ($dataExists
                && null === $data[$name]
                && $input instanceof InputInterface
                && !$input->isRequired()
            ) {
                $this->validInputs[$name] = $input;
                continue;
            }
````

... however, `getValues()` method breaks this logic and will give us both fields nullified:
````php
$inputFilter->isValid(); // === true
$newData = $inputFilter->getValues(); // == [ 'foo' => null, 'bar' => null ]
````

`isValid()` method is also fuzzy about that as it will pull those "implicit default" values before validating, which is incorrect.

This makes it hard to use it as a filter for REST PATCH method, for example.

**Comment by Thinkscape** [comment]
@bakura10 :-)

**Comment by bakura10** [comment]
Yep, there are some inconsistencies on ZF2 input filter, definitely. However this is impossible to change that now, but definitely in ZF3.

I think that this relate to this that I wrote long time ago: https://gist.github.com/bakura10/e35887640ef00942476c

**Comment by weierophinney** [comment]
Just a point of clarification: #7474 provided a number of changes to ensure consistency of how the three flags (required, allow_empty, continue_if_empty) work, and essentially ensure that you *can* have `null` values that are considered valid and required all at the same time. Not saying it's pretty, but the table in that PR shows all 8 combinations.

**Comment by Maks3w** [comment]
Since v2.6.0 auto inject NotEmpty (allow_empty and continue_if_empty) will be deprecated and removed on v4

**Comment by Maks3w** [comment]
InputFilter v2.5.5 now is able to discriminate when `null` means a real value or the default value using the flag hasValue

On v3 all the magic around guess empty values will be removed or disabled
