### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by BreiteSeite** [zendframework/zf2#7442]
Hi,

According to SemVer, if a release contains a BC break, a raise in the major version is the way to go. Unfortunately this is not the case at the moment. ZF 2.4 - for example - contained [16 documented BC breaks](http://framework.zend.com/blog/zend-framework-2-4-0-released.html) but resulted in an increment of the minor version number, which - according to SemVer - is wrong:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> **MAJOR version when you make incompatible API changes,**
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

[semver.org](http://semver.org/)

This makes managing ZF2 dependencies painful, as for example the constraint `~2.3` results in an update to ZF 2.4 which is incompatible with Apigility 1.0 (i guess thats the reason why an Apigility 1.1 release is mentioned in the releasenotes of ZF 2.4).

I understand that the major version has a huge meaning to the world, like books that are written for ZF2, exams/certs for ZF2... which actually mean "zendframework in version 2.X.X"

In my opinion, there are 2 options:
1. Rename `zendframework/zendframework` to `zendframework/zendframework2` and use independent version numbers which would enable SemVer (one day a zendframework2 in version 4.0.0 could exist). This would also sync the composer name to the reponame (`zendframework/zf2.git`).
2. Stay with the zendframework/zendframework name and start using semver (this would mean we theoretically already would have 3.* or greater). However, this would probably confuse many people.

My favorite is option 1.
I know changing the version numbering is a PITA in the first place, but it will prevent pain for many others in the future (especially libraries that depend on zf2).

Thank you.

**Comment by Ocramius** [comment]
@BreiteSeite we can't accommodate that due to the size of the FW: compromises have to be taken, and we rejected a large list of BC Breaks so far.

We are already following SemVer, and if you read through that list, those are all bugfixes are mostly affecting:

 - inheritance (which isn't really something covered by our BC policies anyway)
 - new exceptions on invalid values (instead of silent failures before - this makes your app crash instead of making it process invalid data, and that's actually good)
 - internal classes of the FW that shouldn't be used explicitly (factories, mainly)
 - fixes related to incompatibilities introduced by PHP itself (we can't do much about that, and we have to fix those even in patch releases - these are SemVer violations bubbling up from php-src/pecl to us)

16 BC breaks made it in, but I rejected at least an order of magnitude more issues due to BC breaks, so I can really assure you that we keep BC to heart.

Also: I don't care about the marketing side of the thing, we just won't bump a major version for fixes that still respect the LSP.

**Comment by BreiteSeite** [comment]
Hi @Ocramius and thanks for the fast response :)

> inheritance (which isn't really something covered by our BC policies anyway)

Well, i think this would warrant a new major version, because it changed a public function, which is totally valid to inherit from (even [apigility does that](https://github.com/zfcampus/zf-rest/blob/c933cf86a9ff3c9a43559ea978cc06df18772405/src/RestController.php#L44)). However, this is the case which let many tests fail (because of the PHP Warning about the method signature mismatch) so this is the point this issue is all about.

> new exceptions on invalid values (instead of silent failures before - this makes your app crash instead of making it process invalid data, and that's actually good)

I fully agree that this is actually a good thing, but it's also changing the contract of a method, because the caller now have to expect an exception.

> internal classes of the FW that shouldn't be used explicitly (factories, mainly)

100% agree that this isn't a BC break for the user.

> fixes related to incompatibilities introduced by PHP itself (we can't do much about that, and we have to fix those even in patch releases - these are SemVer violations bubbling up from php-src/pecl to us)

Well, i don't have a opinion about that one because i didn't had a look at it yet.

I fully respect your decision and your work on ZF2 and keeping BCs as minimal as possible, but in my opinion, BC break is BC break no matter for what reason it was introduced and should result in a new major version.

**Comment by Ocramius** [comment]
> BC break is BC break no matter for what reason it was introduced and should result in a new major version.

Agree, but as I said, we get to compromises.

This situation cannot be solved with the FW as-is, but only after 2.5, when we have split each component, and therefore made major versions of each component completely independent.

**Comment by BreiteSeite** [comment]
> split each component, and therefore made major versions of each component completely independent.

Okay.. so that means, that after the split the major versions are not coupled to the version "2" in the sense of zend framework "2" but we could have a zf2/servicemanager in version 5.9.2 (theoretically speaking)? Are there any further readings about the split of the components and especially their planned versioning scheme?

Thanks

**Comment by jbenoit2011** [comment]
Components splitting will happen in "ZF3", more info [here](http://framework.zend.com/blog/announcing-the-zend-framework-3-roadmap.html)
