### ISSUE TITLE
Form collection - PriorityList iterator remove elements bug in populateValues

### ISSUE THREAD

**Issue by Qronicle** [zendframework/zf2#7443]
When calling populateValues on a collection, the iterator loops over all current elements and checks whether they are still in the new data array. If not the element is removed from the collection. It seems however that removing the element causes problems with the iterator, as it might skip elements.

###### Example
A form is loaded with the collection having 3 fieldsets with names [6, 3, 4], but submitted is a new fieldset with name 7, with all other fieldsets removed. The resulting fieldset names after populateValues should be [7], but are [3, 7]

If I put a dump on the first line of the replaced/removed loop, It only gets in there two times for fieldsets 6 and 4. When I put the actual remove line in a comment, it gets in there for all fieldsets.

Tested in ZF 2.4.0. Probably related to the removal of the byName property.

Edit: Went a bit deeper and seems to be a problem with the Zend\Stdlib\PriorityList class, but can be fixed separately in the collection class by keeping a separate array with elements that need to be removed:

```php
        // Check to see if elements have been replaced or removed
        $removeElementNames = array();
        foreach ($this->iterator as $name => $elementOrFieldset) {
            if (isset($data[$name])) {
                continue;
            }
            if (!$this->allowRemove) {
                throw new Exception\DomainException(sprintf(
                    'Elements have been removed from the collection (%s) but the allow_remove option is not true.',
                    get_class($this)
                ));
            }
            $removeElementNames[] = $name;
        }
        foreach ($removeElementNames as $name) {
            $this->remove($name);
        }
```

**Comment by adamlundrigan** [comment]
Fixed in #7446
