### ISSUE TITLE
Http curl adapter timeouts

### ISSUE THREAD

**Issue by Ragazzo** [zendframework/zf2#7454]
Why only one timeout is used [here](https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Client/Adapter/Curl.php#L198) 

If i set options like this

```php
        $options = [
            'maxredirects' => ...,
            'timeout' => $this->recieveTimeout,
            'curloptions' => [
                CURLOPT_TIMEOUT => $this->connectionTimeout,
            ],
        ];
```

they will not be applied correctly, since i have two various connection timeouts, but in `connect()` method it is the same. Is that bug or done for what reason?

**Comment by AprilMedinger** [comment]
Hey Ragazzo, 

With ZF2 Client you shouldn't really need to use the Curl adapter. Especially if you are going to use any of the CURLOPT that are set as invalidOverwritableCurlOptions in the Curl Adapter constructor.

![curl](https://cloud.githubusercontent.com/assets/6540237/7232317/93468aec-e740-11e4-8253-b4c1654ec9dc.PNG)

Not sure why the restrictions were put on the CURLOPT other than to promote the use of the Client.

**Comment by Ragazzo** [comment]
yes, i know, i just want to use two different timeouts, one for connection and one for receiving data, is there any reason why this option is restricted?

**Comment by Martin-P** [comment]
In `Zend\Http\Client\Adapter\Curl::connect()` the same timeout is used for both settings. However when the actual call is made with `Zend\Http\Client\Adapter\Curl::write()` the additional parameters defined under the `curloptions` key are set before the cUrl request is executed (on [line 415](https://github.com/zendframework/zf2/blob/46d500ebeea2e4cc1cb8caef8e1fdb2e180aa2df/library/Zend/Http/Client/Adapter/Curl.php#L415)).
See: [`Zend\Http\Client\Adapter\Curl::write()` line 399 - 411](https://github.com/zendframework/zf2/blob/46d500ebeea2e4cc1cb8caef8e1fdb2e180aa2df/library/Zend/Http/Client/Adapter/Curl.php#L399-L411)

**Comment by Ragazzo** [comment]
@Martin-P sure, but as you can see above this curl connection timeout can not be overridden

**Comment by Martin-P** [comment]
> sure, but as you can see above this curl connection timeout can not be overridden

You can override that (and you are already doing that) using the `timeout` key. In `Zend\Client\Adapter\Curl::connect()` there is a check for this key and `CURLOPT_CONNECTTIMEOUT` is set accordingly. See: [line 198 - 203](https://github.com/zendframework/zf2/blob/46d500ebeea2e4cc1cb8caef8e1fdb2e180aa2df/library/Zend/Http/Client/Adapter/Curl.php#L198-L203)

So basically `CURLOPT_CONNECTTIMEOUT` is set in `connect()` and other options (like `CURLOPT_TIMEOUT`) are set in `write()`.

**Comment by Ragazzo** [comment]
@Martin-P the thing here is that i want two different timeouts for connection and receiving data

**Comment by Martin-P** [comment]
I understand you want to use different timeouts and that is exactly what is happening right now, you are already using different timeouts. In `connect()` the timeout is set on both `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT`, **but** `CURLOPT_TIMEOUT` is overridden again in `write()`.

Just for my understanding: did you actually experience a bug or did you just look at the code and thought there was a bug?

**Comment by Ragazzo** [comment]
@Martin-P i see, so each time in write it will be overridden once again , am i correct? Thanks for explanation, this implementation was not clear to me.

**Comment by Martin-P** [comment]
Yes, that is exactly what is happening here. It is a bit confusing indeed because of setting `CURLOPT_TIMEOUT` in `connect()`. I looked up when it was added, see this PR: #6526
