### ISSUE TITLE
Command Bus Pattern

### ISSUE THREAD

**Issue by aight8** [zendframework/zf2#7456]
What do you think of implementing the Command Bus Pattern to ZF3?
The reason is that ZF2 have with the PluginManager a really good Abstraction Layer Pattern, but the user have to create plain Services that manages that core business logic. With this pattern we could increase the service layer to the next level.
What you think? Hot or Not?

**Comment by danizord** [comment]
Hot! But I don't think it needs to be a framework component, a module fits well :)

**Comment by sandrokeil** [comment]
Definitely hot. A framework component sounds interesting, but [thephpleague](https://github.com/thephpleague/tactician) has already one.

**Comment by Ocramius** [comment]
Hot, but I would only want it as standalone component.

**Comment by sandrokeil** [comment]
Just found this [ZF2 module](https://github.com/prooph/ProophServiceBusModule).

**Comment by Xerkus** [comment]
Too complex for general use framework.

**Comment by bakura10** [comment]
It would be awesome to have a ZF2 module that would integrate with other modules like SlmQueue, for asynchronous event.

This Command bus/Event bus definitely sounds interesting, but after reading tons of tutorials/articles, I still can't understand it / why it's needed, having an integrated module with clear examples and that integrates natively with ZF2 would be awesome.

**Comment by mikemix** [comment]
@bakura10 This is CommandBus implementation from Ross Tuck, and my module to integrate it with ZF2:

http://tactician.thephpleague.com/
https://github.com/mikemix/TacticianModule

**Comment by weierophinney** [comment]
Closing. We can entertain a discrete module separately if anybody wants to write one and have it forked into the zendframework organization.

**Comment by codeliner** [comment]
Unfortunatly, I missed this thread until now. @weierophinney I'm interested in providing a module and it would be great to see it integrated in the zendframework organization. 

Some background: 
I'm working on CQRS and EventSourcing infrastructure for about 2 years now.
My components are heavily inspired by ZF2 components (event-driven, no annotations, no heavy serializers, etc.) and use for example the EventManager and ServiceManager behind the scences.
My components are stand alone, just like the new ZF2/ZF3 compents and can be integrated in a ZF2 application via [prooph/proophessor](http://prooph.github.io/proophessor/).
Currently I'm evaluating an alternative architecture to MVC and ADR for RPC style APIs composed of zend-diactoros + zend-stratigility + prooph/service-bus. No controllers, no action handlers, but instead separated command and query handlers and an API defined by commands and queries.
CQRS + ES is a great pattern, be it with or without async message processing. (D)DDD I'm looking at you.
So if Zend is really interested in providing CQRS and maybe also EventSourcing components I would be very interested to contribute. If you want we can also fork my components into zend organisation and see what we need to improve or change. Have some more people (exp from the ZF universe :-)) thinking about the topic would be great.

PS. Everybody who wants to discuss the concepts behind CQRS or have questions can reach me and other interested devs on the [DDDinPHP](https://groups.google.com/forum/#!forum/dddinphp) mailing list (I think at least @Ocramius knows the group already :-)).

**Comment by codeliner** [comment]
@bakura10 I have integration of SlmQueue and also [HumusAmqpModule](https://github.com/prolic/HumusAmqpModule) on my todo. Just need to find some time for it.
