### ISSUE TITLE
[Zend\Log] Add JSON Formatter to collect logs for different systems e.g. logstash

### ISSUE THREAD

**Issue by sandrokeil** [zendframework/zf2#7466]
I want to send logs from my PHP Docker container to stderr and analyze it with the ELK (elasticsearch, logstash, kibana) stack.

Currently there are different formatters e.g. XML, but a JSON formatter is missing. If we have a JSON Log formatter in ZF2, it gives us the possibility to write standardized plugins for different systems (logstash, fluentd).

Any thoughts or pitfalls for this?

**Comment by manuakasam** [comment]
No pitfalls aside the additional maintenance cost on potential bugs. It's a missing feature and requesting/suggesting is perfectly valid. I can see this being used by quite a few persons.

**Comment by spetz83** [comment]
I would like to work on this issue. Can we get it moved to the https://github.com/zendframework/zend-log project so that I can work off that? Thanks!

**Comment by sandrokeil** [comment]
@spetz83 Please open a new issue or pull request on the zend-log component. I will close this issue now. Thank you.
