### ISSUE TITLE
Using ComposedObject annotation with Required(false) fails with exception

### ISSUE THREAD

**Issue by mirfilip** [zendframework/zf2#7487]
First of all, what is the expected behaviour of having a field in dynamically built form, annotated like
```
/**
 * @Annotation\Required(false)
 * @Annotation\AllowEmpty()
 * @Annotation\ComposedObject("SomeObject")
 */
```
Should the field then be optional but `SomeObject` validated fully when present?

Second part is more of a bug I think. When you take above annotation and switch the order of `@Annotation` like
```
/**
 * @Annotation\ComposedObject("SomeObject")
 * @Annotation\Required(false)
 * @Annotation\AllowEmpty()
 */
```
then AnnotationBuilder fails to build the form with the exception:
`Zend\InputFilter\Factory::createInput expects an array or Traversable; received "boolean"`

I didn't find any in depth documentation / FAQ / tutorial about using `ComposedObject` with other annotations but it seems as if:
1. Form object that is built with `AnnotationBuilder` does not take `Required` and `AllowEmpty` into consideration when `ComposedObject` is present.
2. When using `AllowEmpty` /  `Required(false)` with `ComposedObject`, the composed object specified gets validated regardless if it's present (and obviously fails if it's not).
3. Switching order of annotations confuses `Zend\Form\Factory::createInputFilter()`.  `$inputFilterSpecification` argument contains the `SomeObject` definition but it also has `required = false` and `allow_empty = true` keys. Iterating `inputFilterSpecification` passes `$value = false`  to `Zend\Form\Factory::createInput($value)` which refuses to work with false value.

If my explaination is vague, maybe the example could be helpful [stackoverflow question](https://stackoverflow.com/questions/30033135/zf2-form-with-optional-composedobject-validation)

**Comment by Maks3w** [comment]
There was a bug where optional fields was validated even if data is not set preset https://github.com/zendframework/zend-inputfilter/pull/25. Update to v2.5.5.

Could you create a new issue about annotation order?

**Comment by mirfilip** [comment]
Sure, I will evaluate if error occurs with 2.5.5 and will split second error to another issue. Can you confirm that it _should_ work like I described above?

**Comment by Maks3w** [comment]
Here is the list of permutations and expected validations / error messages for each one

https://github.com/zendframework/zend-inputfilter/blob/master/test/InputTest.php#L633

**Comment by mirfilip** [comment]
My question is rather about `ComposedObject` + `Required` annotation. As `ComposedObject` is used as a fieldset annotation, I later realized it can be a fieldset limitation. I'm not sure if there is a concept of "optional fieldset" in ZF2. Correct me if I'm wrong, but you cannot mark a fieldset optional, you rather don't list them in `validationGroup`.

Again, this is as I remembered it when I dug into this in May. Correct me if I'm wrong.

**Comment by mirfilip** [comment]
@Maks3w Can you answer my question from the comment above? I'd like to finish up on the topic.
