### ISSUE TITLE
Extract Priority in prependValidator fails on HHVM.

### ISSUE THREAD

**Issue by iamtommetcalfe** [zendframework/zf2#7504]
When trying to extract the priority from the validators in prependValidator, the following code is ran -
```php
if (!$this->validators->isEmpty()) {
            $queue = $this->validators->getIterator();
            $queue->setExtractFlags(PriorityQueue::EXTR_PRIORITY);
            $extractedNode = $queue->extract();
            $priority = $extractedNode[0] + 1;
        }
```
If I dump out $extractedNode with HHVM turned OFF, I get the following output(which is as expected) -

```php
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(9223372036854775807)
}
```
But with HHVM turned on, I instead get the following - 
```php
array(2) {
  ["instance"]=>
  object(stdClass)#6288 (9) {
    ["__CLASS__"]=>
    string(20) "Zend\\Validator\\Regex"
    ["messageTemplates"]=>
    string(8) "Array(3)"
    ["messageVariables"]=>
    string(8) "Array(1)"
    ["pattern"]=>
    string(71) "/^[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$/"
    ["value"]=>
    NULL
    ["defaultTranslator"]=>
    NULL
    ["defaultTranslatorTextDomain"]=>
    string(7) "default"
    ["messageLength"]=>
    int(-1)
    ["abstractOptions"]=>
    string(8) "Array(7)"
  }
  ["breakChainOnFailure"]=>
  bool(false)
}
```
This gives an undefined index when trying to define the priority on line 162 in the ValidatorChain.php at $priority = $extractedNode[0] + 1;. Obviously because it hasn't resolved to the priority and appears to instead have just returned the validator?

Actually testing this outside of the ValidatorChain.php I can run the following code with absolutely no issues - 
```php
    $priority_queue = new SplPriorityQueue();

	$priority_queue->insert('item',1);
	$priority_queue->insert('item',2);
	$priority_queue->insert('item',3);
	$priority_queue->setExtractFlags(PriorityQueue::EXTR_DATA);
	var_export($priority_queue->extract()); echo "\n";

	$priority_queue->setExtractFlags(PriorityQueue::EXTR_PRIORITY);
	var_export($priority_queue->extract()); echo "\n";

	$priority_queue->setExtractFlags(PriorityQueue::EXTR_BOTH);
	var_export($priority_queue->extract()); echo "\n";

	die();
```
Which returns - 
```php
'item'
array (
  0 => 2,
  1 => 9223372036854775806,
)
array (
  'data' => 'item',
  'priority' => 
  array (
    0 => 1,
    1 => 9223372036854775807,
  ),
)
```

Unsure whether this needed to be submitted as a Zend Framework issue or a HHVM issue as i'm not 100% on what's actually going wrong in the ValidatorChain.

It's also worth noting that I get this error with any Validator that is used and not just the example I have given.

**Comment by rms230** [comment]
Whilst it's not a permanent fix, this is a workaround that will work on HHVM

    public function prependValidator(ValidatorInterface $validator, $breakChainOnFailure = false)
    {
        $priority = self::DEFAULT_PRIORITY;

        if (!$this->validators->isEmpty()) {
            $extractedNodes = $this->validators->toArray(PriorityQueue::EXTR_PRIORITY);
			rsort($extractedNodes, SORT_NUMERIC);
		    $priority = $extractedNodes[0] + 1;
        }

        $this->validators->insert(
            array(
                'instance'            => $validator,
                'breakChainOnFailure' => (bool) $breakChainOnFailure,
            ),
            $priority
        );
        return $this;
      }
