### ISSUE TITLE
Array to string conversion error caused by CSRF fix to Cookie

### ISSUE THREAD

**Issue by monkeyphp** [zendframework/zf2#7505]
It appears that the recent changes to Zend\Http\Header\*, particularly the HeaderValue::assertValid method causes an array to string conversion error if an array is stored in Cookie.

https://github.com/zendframework/zf2/commit/b5f24b34b1f51b106d35db8561052effab40c43e

The actual line that triggers the error is https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Header/HeaderValue.php#L73

AFIAK - it is perfectly valid to store an array of values in a cookie -http://php.net/manual/en/function.setcookie.php

I assume that on this line https://github.com/zendframework/zf2/blob/release-2.4.1/library/Zend/Http/Header/Cookie.php#L91 the supplied `$value` is the array of values stored in the cookie which are then passed to HeaderValue which fails to handle the parameter correctly.

**Comment by Maks3w** [comment]
About the reference to php manual. I don't see any argument which accept array types.

**Comment by nathanjosiah** [comment]
@Maks3w http://php.net/manual/en/function.setcookie.php#example-4916

**Comment by Maks3w** [comment]
For to close this point. The function never receives an array type argument. Always is string.

**Comment by nathanjosiah** [comment]
It doesn't accept an array but if the cookie contains that syntax then `_COOKIE` will contain arrays which is what causes this problem.

**Comment by Maks3w** [comment]
@monkeyphp Can you write a Gist with a working example on 2.4.0?

**Comment by weierophinney** [comment]
Those of you watching this issue: please do the following in your project root:

```console
$ composer require zendframework/zendframework:dev-master@dev
```

and then test. #7507 was just merged, which should fix the issue.

**Comment by monkeyphp** [comment]
This fix appears to have resolved the array to string conversion issue for me  - thank you
