### ISSUE TITLE
New Navigation Page Type - Category

### ISSUE THREAD

**Issue by kingharrison** [zendframework/zf2#7509]
Add a new navigation page type called 'category'. This would have no link itself but allow you to organize subpages in a navigation menu.

**Comment by sandrokeil** [comment]
Have you tried the visible option of the navigation page?

**Comment by kingharrison** [comment]
Doesn't that make it invisible? I do still want to see it. I just don't want it clickable. I want to hover over it then present submenus that are clickable. 

-King Harrison
Sent from iPhone




On Sat, May 9, 2015 at 2:40 PM -0700, "Sandro Keil" <notifications@github.com> wrote:












Have you tried the visible option of the navigation page?

**Comment by Martin-P** [comment]
A category page is the same as every other page in a tree structure. Different rendering does not make it a category. What you are looking for is a custom partial view for rendering your menu.

When you create a page you can set your own attributes on that page e.g. `category => true`. Next you create your own menu partial, check for the value of `category` and change the layout for that page.

See the manual: [Pages](http://framework.zend.com/manual/current/en/modules/zend.navigation.pages.html) and [View Helper - Menu](http://framework.zend.com/manual/current/en/modules/zend.navigation.view.helper.navigation.html)

**Comment by froschdesign** [comment]
**There is no need for a new page type.**

Use a custom property for pages and for rendering a partial script. (see @Martin-P)

**Comment by kingharrison** [comment]
Is there a way to not add the 'active' class tag to a list element? That was one of the things I was thinking a category could have.

**Comment by Martin-P** [comment]
See [`Zend\View\Helper\Navigation\Menu`](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/View/Helper/Navigation/Menu.php#L69). So with `liActiveClass` you can set the class name.

**Comment by froschdesign** [comment]
> Is there a way to not add the 'active' class tag to a list element? That was one of the things I was thinking a category could have.

It's **your** partial script – don't add the class:

```php
if (isset($page->category)) {
    echo '<li>' . $page->label . '</li>';
} else {
    echo ($page->isActive()) ? '<li class="active">' : '<li>';
    // …
}
```

**Comment by froschdesign** [comment]
@kingharrison 
Please close this issue.
