### ISSUE TITLE
\Zend\Ldap\Attribute::valueFromLdap catching wrong exception

### ISSUE THREAD

**Issue by Karl-Dawson** [zendframework/zf2#7512]
try {
            $return = Converter\Converter::fromLdap($value, Converter\Converter::STANDARD, false);
            if ($return instanceof DateTime) {
                return Converter\Converter::toLdapDateTime($return, false);
            } else {
                return $return;
            }
        } catch (Exception\InvalidArgumentException $e) {
            return $value;
        }

The above catches \Zend\Ldap\Exception\InvalidArgumentException, however, I believe it is supposed to be catching \Zend\Ldap\Converter\Exception\InvalidArgumentException. Following the code through the Converter class, the latter exceptions are thrown, not the former.

This causes an issue when a string date-time value is unable to be converted when using \Zend\Ldap\Node::getAttribute. For example, if the CN of the LDAP object is something like '39685111-Z', it cannot be converted and thus an uncaught exception is thrown; although as above, it seems like it is in fact supposed to be caught.

Could I get clarification on whether this is intended or if it is indeed a bug.

**Comment by Maks3w** [comment]
Yes, it should catch `Zend\Ldap\Converter\Exception\InvalidArgumentException`
