### ISSUE TITLE
BC break in 2.4.2 DB\Sql?

### ISSUE THREAD

**Issue by adear11** [zendframework/zf2#7520]
I have an Apigility based API that has been working like a champ on 2.3.7. I recently upgraded to Apigility 1.1 which brings in ZF 2.4.2 (at the time of update).

Now, a lot of my database queries are failing. 

The code that has been working in 2.3.7 is:

```PHP
    public function updateAnswer($id, $data)
    {
        $sql    = new Sql($this->adapter);
        $update = $sql->update('test_attempt_questions');
        $update->set(array('answer' => '?'))
             ->where(array('id=?'));

        $statement    = $sql->prepareStatementForSqlObject($update);
        $res          = $statement->execute(array($data->answer, $id));
    }
```

This code updates the required row in 2.3.7, however, in 2.4.2 it throws a SQL error:
`Statement could not be executed (HY093 -  - )`

Updating the code above so that I pass the parameter value in the `where` method and remove it from the `execute()` method call, the code works.

```PHP
    public function updateAnswer($id, $data)
    {
        $sql    = new Sql($this->adapter);
        $update = $sql->update('test_attempt_questions');
        $update->set(array('answer' => '?'))
             ->where(array('id=?' => $id)); //adding the bind value here instead of in execute works in 2.4

        $statement    = $sql->prepareStatementForSqlObject($update);
        $res          = $statement->execute(array($data->answer));
    }
```

Is this a BC break in 2.4 or am I missing something simple?

**Comment by weierophinney** [comment]
There were a ton of refactors going into 2.4, so I'm not entirely surprised to see some issues here and there.

In looking at your original, and even the revised version, the first thing that stands out is that you're using unnamed placeholders; this is a practice that is known to raise problems in many DBAL libraries. I'd recommend trying named parameters:

```php
$update->set(array('answer' => ':answer'))
    ->where(array('id = :id'));
// ...
$res = $statement->execute(array('answer' => $data->answer, 'id' => $id));
```

If you know the values when creating the SQL statement object, just provide them from the outset, as it's the safest way:

```php
$update->set(array('answer' => $data->answer)) // Note: no placeholder necessary!
    ->where(array('id' => $id)); // Note: no placeholder necessary!
// ...
$res = $statement->execute();
```

Essentially, I'm suggesting that while there may be a subtle BC break, there are changes you can make to your code that will make it more robust and which will avoid those breaks.

**Comment by adear11** [comment]
Thanks for the feedback, Matthew.

I've arrived at the same conclusion today after digging into this some more. I think there is a subtle BC break, but that break may be due to me using the component in a way that is not optimal or recommended. 

I've been working this afternoon to make my code work with 2.4, and I'll make the changes that you suggest.  I'll leave it to you decide if this needs to be closed, or if this is something that you guys want to try to address.

Thanks again!
