### ISSUE TITLE
Invalid header value detected

### ISSUE THREAD

**Issue by apoca** [zendframework/zf2#7524]
Anyone experiencing this issue?

`"zendframework/zendframework" : "@stable",`

> Fatal error: Uncaught exception 'Zend\Mail\Header\Exception\InvalidArgumentException' with message 'Invalid header value detected' in /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Header/GenericHeader.php:61 Stack trace: #0 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Header/GenericHeader.php(35): Zend\Mail\Header\GenericHeader::splitHeaderLine('Content-Type:mu...') #1 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(236): Zend\Mail\Header\GenericHeader::fromString('Content-Type:mu...') #2 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(195): Zend\Mail\Headers->addHeaderLine('Content-Type', 'multipart/alter...') #3 /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendf in /usr/local/zend/var/apps/http/esolidar.bewarket.setima.local/80/0.1/vendor/zendframework/zendframework/library/Zend/Mail/Header/GenericHeader.php on line 61

**Comment by Martin-P** [comment]
> Anyone experiencing this issue?

[Yes](https://github.com/zendframework/zf2/issues?utf8=%E2%9C%93&q=is%3Aissue+Invalid+header+value+detected). What is the exact ZF2 version you are using? The stable version of 5 days ago is another stable as today.

**Comment by Maks3w** [comment]
This is related with the zf2015-04 security patch.

What is the value when call `Zend\Mail\Header\GenericHeader::splitHeaderLine`?

**Comment by apoca** [comment]
This version: 2.4.2

I'm using another module to report errors... bitweb/zf2-error-reporting-module

Before updating the repository ZF2 was working ...

**Comment by apoca** [comment]
With Updating zendframework/zendframework (2.4.2 => 2.4.0) works fine...

**Comment by Maks3w** [comment]
@apoca Please provide the requested feedback

**Comment by apoca** [comment]
OK I'll but I need to search inside this module, this is a module from another user...

**Comment by Maks3w** [comment]
It's a bug in the developer module https://github.com/BitWeb/mail/blob/master/src/BitWeb/Mail/Service/MailService.php#L157

**Comment by stmaxvl** [comment]
Version 2.4.7 - has same problem

**Comment by lony** [comment]
I have this issue again. The problem seems to be the references as attached. For anonymity reasons I removed the TLD and replaced it with REMOVED.

**Version:**
"zendframework/zend-mail": "^2.5"

**Input:**
```
References: <CA+_RiCmfqeugQ_hU6xEdKW95yMRfZM3xB0E+vzyeje6uiBXsng@REMOVED>	>><035901d104d7$1797d040$46c770c0$@REMOVED> <CA+_RiCm2=1ejWqDLB=S0bqLe9tS9BDjT-PUXq27vCie=9+9hPQ@REMOVED>
```

**Result:**
```
Fatal error: Uncaught exception 'Zend\Mail\Header\Exception\InvalidArgumentException' with message 'Invalid header value detected' in C:\xampp\htdocs\IMAP\vendor\zendframework\zend-mail\src\Header\GenericHeader.php on line 61

Zend\Mail\Header\Exception\InvalidArgumentException: Invalid header value detected in C:\xampp\htdocs\IMAP\vendor\zendframework\zend-mail\src\Header\GenericHeader.php on line 61

Invalid header value detected:
#0 C:\xampp\htdocs\IMAP\vendor\zendframework\zend-mail\src\Header\GenericHeader.php(35): Zend\Mail\Header\GenericHeader::splitHeaderLine('References: addHeaderLine('References: __construct(Array)
#6 C:\xampp\htdocs\IMAP\vendor\zendframework\zend-mail\src\Storage\Imap.php(118): Zend\Mail\Storage\Message->__construct(Array)
#7 C:\xampp\htdocs\IMAP\zend.php(49): Zend\Mail\Storage\Imap->getMessage(20)
#8 {main}
```

**Comment by zzzloy777** [comment]
2.5 still there

**Comment by adamlundrigan** [comment]
@lony @zzzloy777 If this is still an issue could you please open a ticket against the Zend\Mail repository?  You're unlikely to get any traction here as components have been split out of this repository.

https://github.com/zendframework/zend-mail/issues

**Comment by Martin-P** [comment]
Ping @Maks3w @weierophinney 

It would be neat if the maintainers can take the effort to properly migrate the open issues to the matching repositories instead of just closing them.

**Comment by Maks3w** [comment]
@Martin-P There is nothing to migrate here. The issue was closed on May 14. Foreign people have hijacked the issue instead open a new one.

**Comment by Martin-P** [comment]
> Foreign people have hijacked the issue instead open a new one.

The first post after you closed the issue was:
> Version 2.4.7 - has same problem

That is not hijacking, but continuing the issue instead of opening a new exactly the same issue (which in that case probably would be marked as duplicate).

**Comment by Maks3w** [comment]
@Martin-P I won't continue the discussion. This issue was investigated in depth even third party code was review before resolve.

**Comment by adamlundrigan** [comment]
@lony I'm not too familiar with the inner workings of the mail headers classes but it looks to me like your References header is falling foul of [`HeaderValue::isValid`](https://github.com/zendframework/zend-mail/blob/7a75bb0464da0a40ed3de5aa6dc9ec8f59828662/src/Header/HeaderValue.php#L73), which requires that the header field body be "structured" according to RFC-2822's definition:  no non-printable ASCII characters except CR (13), and a CR must be followed immediately by 1x LF (10) and 1x WSP (32).
