### ISSUE TITLE
Digits Filter doesn't support floats

### ISSUE THREAD

**Issue by matiasiglesias** [zendframework/zf2#7528]
Digits Validator supposed to permit integers or floats but Digit Filter regex doesn't include ".", so 1234 is permitted but 1234.5 is not, despite isValid functions permit it:
```
public function isValid($value)
    {
        if (!is_string($value) && !is_int($value) && !is_float($value)) {
            $this->error(self::INVALID);
            return false;
        }
        //...
}
```

**Comment by svycka** [comment]
That's not true digits validator should not accept float values like 123.4 but float can be 123 so validator accepts floats also. At least tests shows that. I think you are looking for Float validator.

**Comment by matiasiglesias** [comment]
Yes. that's what I'm looking for: a floating validator. I thought I could use this validator from looking into the code
