### ISSUE TITLE
PHP CS Fixer - question

### ISSUE THREAD

**Issue by keradus** [zendframework/zf2#7535]
Hi!
If I get it right you split the repo into many, many components with separate repos, and PR should go there.
Also, we are using PHP CS Fixer here.
For now - we picking which fixers should be used. That will be tricky with so many repos to have same rules in every repo and synchronize it. What do you think about creating extra level on PHP CS Fixer that would contains PSR2 + some extra rules, like now?
I could help with that ;)

**Comment by Maks3w** [comment]
Seems interesting to centralize configuration but:

1) Goes against each repo to have his own life cycle and his own rules. i. e. some repo could use the short array syntax while others not

2) It's a problem for low activity comments. i. e After update central CS config each repo must to be checked if not PRs against the repo will fail for things unrelated to the PR

**Comment by DASPRiD** [comment]
Apart from that, we were considering switching to PHP-CS, as it has a much more complete set of PSR-2 rules. And if I remember correctly, we are not using any additional rules.

**Comment by keradus** [comment]
> i. e. some repo could use the short array syntax while others not

Yeah, idneed. FYI, one can set level to his own and then apply extra fixers in single configuration.


> Apart from that, we were considering switching to PHP-CS, as it has a much more complete set of PSR-2 rules. And if I remember correctly, we are not using any additional rules.

It's sad to hear that. One day it was strongly discussed here and PHP CS Fixer was choosen. It is not much different in PSR2 coverage, and if it miss any feel free to point that as new feature request to PHP CS Fixer!
Also, current ZF2's `.php_cs` has much more rules that extend PSR2.
After said that - it's great to use tool to keep CS clean, whatever tool it is ;)

**Comment by localheinz** [comment]
For reference, this is the PR where use of `phpcs` was proposed, but eventually turned down in favour of `php-cs-fixer`: https://github.com/zendframework/zf2/pull/6182.

**Comment by gianarb** [comment]
> 1) Goes against each repo to have his own life cycle and his own rules. i. e. some repo could use the short array syntax while others not

Are you sure that it's a good idea? I don't know.. Now every component has your life and it's very good.. But maintainers and "style's school" is the same for all.. Why we should change roles between components?

**Comment by RomainBastide** [comment]
> 1) Goes against each repo to have his own life cycle and his own rules. i. e. some repo could use the short array syntax while others not
The same rules should be applied for each components.

**Comment by keradus** [comment]
From closing I assume the ZF level directly on PHP CS Fixer is not what you want to have same rules for all component

**Comment by Maks3w** [comment]
New refactors are using CodeSniffer, so PHP-CS-Fixer is deprecated

**Comment by TomasVotruba** [comment]
In case anyone would like to use both to preven such arguments, there is inspiration: https://www.tomasvotruba.cz/blog/2017/05/03/combine-power-of-php-code-sniffer-and-php-cs-fixer-in-3-lines/
