### ISSUE TITLE
Mysql query is super slow, please optimize count function...

### ISSUE THREAD

**Issue by zuoRambo** [zendframework/zf2#7539]
ok! Zend/Paginator/Adapter/DbSelect.php has one function count(), it was used to count total rows for paginator. When i find the max time usage was occurred in this function , i try to find the question and use the following code to debug.
```
echo $countSelect->getSqlString(new \Zend\Db\Adapter\Platform\Mysql);
exit;
```
To follow a logical train of thought, i got the sql
```
SELECT COUNT(1) AS `c` FROM (
    SELECT `st_re_url`.*,
         `pr`.`product_name` AS `product_name`, 
         `br`.`brand_name` AS `brand_name`, 
         `ca`.`category_name` AS `category_name`,
         `sh`.`shop_name` AS `shop_name` 
   FROM `st_re_url` 
        INNER JOIN `st_enum_product` AS `pr` ON `pr`.`product_id` = `st_re_url`.`product_id` 
        INNER JOIN `st_brand` AS `br` ON `br`.`brand_id`=`st_re_url`.`brand_id` 
        INNER JOIN `st_category` AS `ca` ON `ca`.`category_id`=`st_re_url`.`category_id` 
        INNER JOIN `st_enum_shop` AS `sh` ON `sh`.`shop_id`=`st_re_url`.`shop_id`
   WHERE `status` = '99' 
       AND `br`.`brand_id` = '100' 
        AND `ca`.`category_id` = '100'
     ) AS `original_select`
```
replenish: zf2.2.4 mysql engine:innodb
thanks a lot!

**Comment by Martin-P** [comment]
The `count()` function uses your own query and merely wraps it in a `COUNT` function (see [`Zend\Paginator\Adapter\DbSelect` line 150](https://github.com/zendframework/zf2/blob/1afa0410b64685d81b0e861c36bc3d4595a4ad7a/library/Zend/Paginator/Adapter/DbSelect.php#L150)). If you provide a slow query to `Zend\Paginator\Adapter\DbSelect` that is your problem and you need to optimize your query. Looking at the query you can check if you actually need INNER JOIN or if a LEFT JOIN can also do the job. Next you can check if an index in the `status` column improves the query speed.

You can use `EXPLAIN` on your original select query for details.

**Comment by zuoRambo** [comment]
@Martin-P thanks a lot, you are right, i should optimize my sql, in fact left join is better than inner . It will use full table scan to select on table which engine type is innodb. i think this is the key of the problem.
