### ISSUE TITLE
Replace HydratorListener hard-coded reference

### ISSUE THREAD

**Issue by jbenoit2011** [zendframework/zf2#7540]
In [Zend\Stdlib\Hydrator\Aggregate\AggregateHydrator at line 37](https://github.com/zendframework/zf2/blob/b952b35a18d13e3645adcf5721440cbc446d923d/library/Zend/Stdlib/Hydrator/Aggregate/AggregateHydrator.php#L37), there is a hard-coded reference to the listener it uses.
```php
  public function add(HydratorInterface $hydrator, $priority = self::DEFAULT_PRIORITY)
  {
        $this->getEventManager()->attachAggregate(new HydratorListener($hydrator), $priority);
  }
```
If I want to inject a different listener, I have to override `AggregateHydrator::add`.
Could we use ServiceLocator instead of `new HydratorListener` ?
This way the HydratorListener overriding would be simplified. I would need to just declare the listener in config files.

**Comment by Martin-P** [comment]
If I am correct you can attach a listener with a higher priority and make that listener stop the propagation of the event using `$event->stopPropagation()`. That way the hard-coded listener won't be executed.

**Comment by jbenoit2011** [comment]
The listener attaching is made in `AggregateHydrator::add`, so I have no choice than override this method that's why I think you're wrong @Martin-P . Unless I misunderstood.

**Comment by adamlundrigan** [comment]
What's your use case for changing the implementation used here?  It's really the entire point of AggregateHydrator...if you're changing that listener behaviour you're likely stretching AggregateHydrator beyond what it's intended to do.

**Comment by jbenoit2011** [comment]
It makes a while I encountered this issue. After few months, I wonder If I have well understood the use of aggregate hydrator?
So I think it's best to close the issue for the moment. And reopen it later, if needed.

**Comment by adamlundrigan** [comment]
@jbenoit2011 thanks.  If you come back around to this and feel it's still an issue feel free to reopen it on [the Zend\Hydrator repository](https://github.com/zendframework/zend-hydrator)
