### ISSUE TITLE
"Sender" header causing fatal error when calling Zend\Mail\Message::fromString($emailString);

### ISSUE THREAD

**Issue by marcusjfloyd** [zendframework/zf2#7555]
I found this while testing an email pipe script I made using ZF 2.4.2.

Whenever an email comes in that has the "Sender" header, I get a fatal error when using the entire raw email to create a Zend\Mail\Message object using Zend\Mail\Message::fromString($emailString);

Here is the stack trace:

PHP Fatal error:  Uncaught exception 'Zend\Mail\Exception\InvalidArgumentException' with message 'Email must be a valid email address' in /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Address.php:32
Stack trace: #0 /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Header/Sender.php(123):
    Zend\Mail\Address->__construct('', '') #1
    /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Header/Sender.php(58):
    Zend\Mail\Header\Sender->setAddress('', '') #2
    /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(478):
    Zend\Mail\Header\Sender::fromString('Sender: myemail@...') #3
    /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(393):
    Zend\Mail\Headers->lazyLoadHeader(14) #4
    /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Headers.php(154):
    Zend\Mail\Headers->current() #5
    /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Message.php(86):
    Zend\Mail\Headers->setEncoding('ASCII') #6
    /home/mail/vendor/zendframework/zendframe in
    /home/mail/vendor/zendframework/zendframework/library/Zend/Mail/Address.php
    on line 32

In the meantime, I get around this by using try to catch the exception, and if this error is caught, then I remove the Sender header from the raw email using preg_replace('/Sender:.+\n/', '', $emailString);

I'm not sure if the domain name portion of the email address is actually being replaced by "..." or if it's just trying to shorten the call in the stack trace for brevity. It looks like it's not being parsed correctly.

I've quadruple checked the raw header and it is structured properly like "Sender: myemail@mydomain.com\n" I should also note that I'm sending the email from a Google Apps account with one of my domain names. I don't have this problem sending from Gmail because emails sent from Gmail do not include the Sender header.

I'll look at the ZF2 code to see if I can find some details to help out.

**Comment by gianarb** [comment]
Hi! Why you are `\n` into the email address?

**Comment by marcusjfloyd** [comment]
That's pretty standard. I'm not actually doing that. Each new header gets put on a new line. I'm just showing you that there is a new line there. That's how emails come in their raw format.

**Comment by Maks3w** [comment]
How are you getting the mail message? The EOL should be \r\n

**Comment by marcusjfloyd** [comment]
it's a pipe script so I'm getting the email message through stdin:

// read from stdin
$fd = fopen("php://stdin", "r");

while (!feof($fd)) {
        $line = fread($fd, 1024);
        $emailString .= $line;
}

fclose($fd);

All other headers are parsed correctly. So far it looks like Zend\Mail\Headers is parsing this header incorrectly... zf2/library/Zend/Mail/Headers.php line 478

**Comment by Maks3w** [comment]
Can you check if the input had \r\n? What software are you using as mail client?

**Comment by marcusjfloyd** [comment]
EOL is actually \r\n. The client I sent the email from is Google Apps in the browser with one of my domains... so Gmail for business. I send from there to a server running Postfix that I use to pipe the email to this script.

**Comment by stefanotorresi** [comment]
this has nothing to do with EOLs.
the problem is caused by [this regex in Zend\Mail\Header\Sender](https://github.com/zendframework/zf2/blob/master/library/Zend/Mail/Header/Sender.php#L50)

this

```php
Header\Sender::fromString('Sender: foo@bar');
```

will fail validation because the regex only matches `<email>` format, so `setAddress` is invoked with an empty value.

prior 2.4.2, the header address was not validated, but the following test would fail:

```php
public function testFromStringWithPlainEmail()
{
    $headerString = 'Sender: foo@bar';
    $header = Header\Sender::fromString($headerString);
    $this->assertSame($headerString, $header->toString());
}
```

with this result:

```
1) ZendTest\Mail\Header\SenderTest::testFromStringWithPlainEmail
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Sender: foo@bar
+Sender:
```

**Comment by stefanotorresi** [comment]
fyi i'm working on a fix, will issue a PR shortly.

**Comment by dendemann** [comment]
I ran into the same problem yesterday. The relevant ABNF from RFC5322 is:
sender          =   "Sender:" mailbox CRLF
mailbox         =   name-addr / addr-spec
addr-spec       =   local-part "@" domain
name-addr       =   [display-name] angle-addr

You can see that mailbox can be a plain email address as well. The regex check implemented in the original framework code is not sufficient.

**Comment by stefanotorresi** [comment]
yep, that's the spec I referred to while implementing the fix, which is ready to be reviewed. just be patient. ;)

**Comment by adamlundrigan** [comment]
What is the status of this?

**Comment by stefanotorresi** [comment]
see zendframework/zend-mail#9

**Comment by marcodevxxx** [comment]
I've just started to use Zend Framework and after 1 day spent to understand how to install it (very unfriendble description on the official website) I tried to code something and invoiking this "echo "message: " . $message->getContent() . "<br><br><br>";" I just got this:

Fatal error: Uncaught exception 'Zend\Mail\Exception\InvalidArgumentException' with message 'Email must be a valid email address' in... 

The email i'm trying to read is a simple mail sent from hotmail.it

I'm very worry to use Zendframework now...
