### ISSUE TITLE
Something wrong with travis build?

### ISSUE THREAD

**Issue by DaanBiesterbos** [zendframework/zf2#7566]
Hi all,

I created a pull request. The tests passed locally, and CS issues were fixed. I can't figure why the build failed, so I checked out some other builds. And I noticed that more builds were taking a long time to complete and failed. PHP 5.3, 5.4, 5.5 all passed, 5.6 failed after 17 minutes.  

Any ideas on the what is causing it, and how it can be solved?

Daan.

**Comment by Maks3w** [comment]
This repo is deprecated. Probably at the end of the day a new release will be with the official announcement.

Please reroute your PRs to the specific component repo `zendframework/zend-XXX`
