### ISSUE TITLE
The use statement with non-compound name 'Zend_View_Helper_FormElement' has no effect

### ISSUE THREAD

**Issue by lhorace** [zendframework/zf2#7567]
Hello,

CentOS7
PHP5.6.9 

I am reporting a bug against Zend Framework in regards to a IcingaWeb2 if a bug report hasn't been reported by Icinga folks. See below:

Server error: The use statement with non-compound name 'Zend_View_Helper_FormElement' has no effect

#0 /usr/share/icingaweb2/library/vendor/Zend/Loader/PluginLoader.php(397): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'The use stateme...', '/usr/share/icin...', 4, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Loader/PluginLoader.php(397): Zend_Loader_PluginLoader::load()
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(1168): Zend_Loader_PluginLoader->load('FormNumber')
#3 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(610): Zend_View_Abstract->_getPlugin('helper', 'formNumber')
#4 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/ViewHelper.php(240): Zend_View_Abstract->getHelper('formNumber')
#5 /usr/share/icingaweb2/library/vendor/Zend/Form/Element.php(2048): Zend_Form_Decorator_ViewHelper->render('')
#6 /usr/share/icingaweb2/library/vendor/Zend/Form/Decorator/FormElements.php(115): Zend_Form_Element->render()
#7 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_FormElements->render('\n<h1 class="hin...')
#8 /usr/share/php/Icinga/Web/Form.php(1132): Zend_Form->render(NULL)
#9 zend.view:///usr/share/icingaweb2/modules/setup/application/views/scripts/index/parts/wizard.phtml(1): Icinga\Web\Form->render()
#10 /usr/share/php/Icinga/Web/View.php(204): include('zend.view:///us...')
#11 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#12 zend.view:///usr/share/icingaweb2/modules/setup/application/views/scripts/index/index.phtml(135): Zend_View_Abstract->render('index/parts/wiz...')
#13 /usr/share/php/Icinga/Web/View.php(204): include('zend.view:///us...')
#14 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(893): Zend_View_Abstract->render('index/index.pht...')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(914): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/index.pht...', NULL)
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(953): Zend_Controller_Action_Helper_ViewRenderer->render()
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch('indexAction')
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/share/php/Icinga/Application/Web.php(154): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/share/php/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
#24 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#25 {main}

Regards.

**Comment by Maks3w** [comment]
You may want to open the issue in ZF1 project https://github.com/zendframework/zf1
