### ISSUE TITLE
Help on responding a Zend\Http\Response\Stream from a Strategy on EVENT_RESPONSE

### ISSUE THREAD

**Issue by berturion** [zendframework/zf2#7568]
I Created my own Model "FileStreamModel" with a strategy in charge of responding a Stream, according to FileStreamModel options (like the file path and other things).

My goal is to simplify the controller action in this way:

    public function viewPdfAction() {
        $fsm = new FileStreamModel();
        $fsm->setContentDisposition(FileStreamModel::CONTENT_DISPOSITION_INLINE);
        $fsm->setContentType('application/pdf');
        $fsm->setFilePath('chemin/vers/mon/fichier.pdf');
        return $fsm;
    }

My FileStreamModel looks like this:

    <?php
    namespace Users\View\Model;
    use Zend\View\Model\ViewModel;
    class FileStreamModel extends ViewModel
    {
        const CONTENT_DISPOSITION_INLINE = 'inline';
        const CONTENT_DISPOSITION_ATTACHMENT = 'attachment';
        const OPT_CONTENT_TYPE = 'content-type';
        const OPT_CONTENT_DISPOSITION = 'content-disposition';
        const OPT_FILE_PATH = 'filepath';
        protected $captureTo = null;
        protected $terminate = true;
        public function getContentType($default = null)
        {
            return $this->getOption(self::OPT_CONTENT_TYPE, $default);
        }
        public function setContentType($contentType)
        {
            return $this->setOption(self::OPT_CONTENT_TYPE, $contentType);
        }
        public function getContentDisposition($default = self::CONTENT_DISPOSITION_INLINE)
        {
            return $this->getOption(self::OPT_CONTENT_DISPOSITION, $default);
        }
        public function setContentDisposition($contentDisposition)
        {
            return $this->setOption(self::OPT_CONTENT_DISPOSITION, $contentDisposition);
        }
        public function getFilePath($default = null)
        {
            return $this->getOption(self::OPT_FILE_PATH, $default);
        }
        public function setFilePath($filename)
        {
            return $this->setOption(self::OPT_FILE_PATH, $filename);
        }
    }

I have a renderer, I'm not sure it is necessary because it does nothing, but here it is:

    <?php
    namespace Users\View\Renderer;
    use Zend\View\Renderer\RendererInterface as Renderer;
    use Zend\View\Resolver\ResolverInterface as Resolver;    
    class FileStreamRenderer implements Renderer
    {
        private $resolver = null;
        public function getEngine()
        {
            return null;
        }
        public function render($nameOrModel, $values = null)
        {
            return null;
        }
        public function setResolver(Resolver $resolver)
        {
            $this->resolver = $resolver;
            return $this;
        }
    }

The most important class is my Strategy. The response is processed on EVENT_RESPONSE when the model is a FileStreamModel. In that case, I set a new response with new headers in the ViewEvent. The response is of type `Zend\Http\Response\Stream`:

    <?php
    namespace Users\View\Strategy;
    use Zend\EventManager\EventManagerInterface;
    use Zend\EventManager\ListenerAggregateInterface;
    use Zend\View\ViewEvent;
    use Users\View\Model\FileStreamModel;
    use Zend\Http\Response\Stream;
    use Users\View\Renderer\FileStreamRenderer;
    use Zend\Http\Headers;
    class FileStreamStrategy implements ListenerAggregateInterface
    {
        protected $renderer;
        protected $listeners = array();
        public function __construct(FileStreamRenderer $fileStreamRenderer) {
            $this->renderer = $fileStreamRenderer;
        }
        public function attach(EventManagerInterface $events, $priority = 1)
        {
            $this->listeners[] = $events->attach(ViewEvent::EVENT_RENDERER, array($this, 'selectRenderer'), $priority);
            $this->listeners[] = $events->attach(ViewEvent::EVENT_RESPONSE, array($this, 'injectResponse'), $priority);
        }
        public function selectRenderer(ViewEvent $e)
        {
            $model = $e->getModel();
            if ($model instanceof FileStreamModel) {
                return $this->renderer;
            }
            return;
        }
        public function detach(EventManagerInterface $events)
        {
            foreach ($this->listeners as $index => $listener) {
                if ($events->detach($listener)) {
                    unset($this->listeners[$index]);
                }
            }
        }
        public function injectResponse(ViewEvent $e)
        {
            /* @var $model FileStreamModel */
            $model = $e->getModel();
            if (!($model instanceof FileStreamModel)) {
                return;
            }
            $filePath = $model->getFilePath();
            $contentDisposition = $model->getContentDisposition();
            $headers = new Headers();
            $headers->addHeaderLine('Content-Disposition', $contentDisposition.'; filename="' . basename($filePath).'"');
            $headers->addHeaderLine('Content-Type', $model->getContentType());
            $headers->addHeaderLine('Content-Length', filesize($filePath));
            $headers->addHeaderLine('Expires', '@0');
            $headers->addHeaderLine('Cache-Control', 'must-revalidate');
            $headers->addHeaderLine('Pragma', 'public');

            $response = new Stream();
            $response->setHeaders($headers);
            $response->setStatusCode(200);
            $response->setStreamName(basename($filePath));
            $response->setStream(fopen($filePath, 'r'));
            $e->setResponse($response);
        }
    }

Here are my factories:

    <?php
    namespace Users\Mvc\Service;
    use Zend\ServiceManager\FactoryInterface;
    use Zend\ServiceManager\ServiceLocatorInterface;
    use Users\View\Renderer\FileStreamRenderer;
    class ViewFileStreamRendererFactory implements FactoryInterface
    {
        public function createService(ServiceLocatorInterface $serviceLocator)
        {
            $viewManager = $serviceLocator->get('ViewManager');
            $fileStreamRenderer = new FileStreamRenderer();
            $fileStreamRenderer->setResolver($viewManager->getResolver());
            return $fileStreamRenderer;
        }
    }

    <?php
    namespace Users\Mvc\Service;
    use Zend\ServiceManager\FactoryInterface;
    use Zend\ServiceManager\ServiceLocatorInterface;
    use Users\View\Strategy\FileStreamStrategy;
    class ViewFileStreamStrategyFactory implements FactoryInterface
    {
        public function createService(ServiceLocatorInterface $serviceLocator)
        {
            $fsRenderer = $serviceLocator->get('ViewFileStreamRenderer');
            $fsStrategy = new FileStreamStrategy($fsRenderer);
            return $fsStrategy;
        }
    }

Declarations on `module.config.php`:

    'service_manager' => array(
        'factories' => array(
            'ViewFileStreamStrategy' => 'Users\Mvc\Service\ViewFileStreamStrategyFactory',
            'ViewFileStreamRenderer' => 'Users\Mvc\Service\ViewFileStreamRendererFactory'
        )
    ),
    'view_manager' => array(
        'strategies' => array(
            'ViewFileStreamStrategy'
        )
    )

While debugging, I see that the strategy is called and sets the response. But my result in the browser is a blank page with wrong headers, no content at all.

I obtained a 'better' result by getting the headers from the response (instead of setting new ones) and populating them. In that case, ma browser (Firefox) opens its PDF Reader and waits for a content that never comes.

I think it's because I set a new response from the ViewEvent instead of using the one in there. But I need the response to be a `Zend\Http\Response\Stream` object, so I don't know how to do differently.

I checked that my PDF exists. I use 'realpath' to get it. And I tested a 'classic' action by returning the Stream response from the Action, the PDF file is correctly displayed in that case.

Can someone show me the way to respond a Stream from the Strategy ?

**Comment by berturion** [comment]
I think the problem comes from the way I return the response.
In my code, I instantiate a new Response with new Headers instead of working with existing ones.
Am I correct ?
Someone can help me returning my Stream ?
Thanks.

**Comment by sasezaki** [comment]
I think prolic's [HumusStreamResponseSender](https://github.com/prolic/HumusStreamResponseSender) module is helpful, please try.

**Comment by berturion** [comment]
Thanks, I will try that. Although, I would like to understand what's happening with my code... Maybe I will get an answer looking at this Humus module.
