### ISSUE TITLE
The ldap extension is now mandatory to use zf 2.5

### ISSUE THREAD

**Issue by mpalourdio** [zendframework/zf2#7569]
From v2.5, the ldap extension has become mandatory because of the split 
See https://github.com/zendframework/zend-ldap/blob/master/composer.json#L17

I think it should be worth mentioning it somewhere, or maybe moving Zend\Ldap to suggested packages. For now, if the extension is not installed, composer sticks ZF2 to v2.4.* because of this requirement.

Installing an extension is quite easy, but some users may misunderstand why they can't upgrade.

The problem did not appear on travis because of ```--ignore-platform-reqs```, but I saw this yesterday while trying to upgrade DoctrineModule and DoctrineORMModule.

It's possible to make travis load the ldap extension btw. See this commit for example https://github.com/mpalourdio/DoctrineModule/commit/50e103f4b805f62f1ab6ddf8b17bcc647d52a0eb

Any suggestions ?

**Comment by Maks3w** [comment]
Travis works due --ignore-system-requirements

**Comment by mpalourdio** [comment]
My bad, i tought that require-dev only grabbed the packages in the requide-rev section, but you must be right, it doesn't make much sense.

**Comment by weierophinney** [comment]
I've also created #7571 to make zend-ldap optional going forward.

**Comment by weierophinney** [comment]
Fixed with #7571
