### ISSUE TITLE
onfocustout dosent work on input element attributes

### ISSUE THREAD

**Issue by faghihian71** [zendframework/zf2#7575]
$form->add(array(
            'type' => 'email',
            'name' => 'email',
              'attributes'=>array(
                  'placeholder'=>'email Address',

                  'data-is-email'=>'',
                  'onfocusout'=>'myTestFunction()',
                  'class'=>'form-control simple-input','dir'=>'ltr'),
            'options'=>array(
              'label'=>'email'  
            )
           

        ));

if i write onkeyup it works but it seems that onfocustout dosent recognize with zend2

**Comment by froschdesign** [comment]
`onfocusout` is not in the HTML standard and it doesn't work in Firefox.
`onblur` will help. (Note: The `onblur` event does not bubble.)

**Comment by Maks3w** [comment]
@faghihian71 Is onfocusout rendered in the page HTML?

**Comment by manuakasam** [comment]
Can't get rendered @Maks3w as it's not within the allowed attributes list

https://github.com/zendframework/zend-form/blob/master/src/View/Helper/AbstractHelper.php#L98

This is due to the reason that @froschdesign outlined
