### ISSUE TITLE
Please Remove YouTube Zend GData Page

### ISSUE THREAD

**Issue by iulukaya** [zendframework/zf2#7580]
YouTube GData API is turned down. (http://youtube-eng.blogspot.com/2015/04/bye-bye-youtube-data-api-v2.html)
http://framework.zend.com/manual/1.12/en/zend.gdata.youtube.html

**Comment by ltouro** [comment]
I think the correct repository is here https://github.com/zendframework/zf1

**Comment by iulukaya** [comment]
thanks.
