### ISSUE TITLE
zend an exception was raised while creating "Application\Model\ApiTable"; no instance returned

### ISSUE THREAD

**Issue by hardeepsharma90** [zendframework/zf2#7581]
I am using Zend 2.4.
When i try to connect using Sql server by SQLSRV driver and fetch api information from the Api Table then i got an error
'zend an exception was raised while creating "Application\Model\ApiTable"; no instance returned' 

This is my Module.php file

namespace Application;

use Zend\Mvc\ModuleRouteListener;
use Zend\Mvc\MvcEvent;

use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;

class Module
{
    public function onBootstrap(MvcEvent $e)
    {
        $eventManager        = $e->getApplication()->getEventManager();
        $moduleRouteListener = new ModuleRouteListener();
        $moduleRouteListener->attach($eventManager);
    }

    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                ),
            ),
        );
    }
	
	public function getServiceConfig() {
        return array(
            'factories' => array(
								
		   'Application\Model\ApiTable' => function($sm) {
                    $tableGateway = $sm->get('ApiTableGateway');
                    $table = new ApiTable($tableGateway);
                    $table->setServiceLocator($sm);
                    return $table;
                },
                'ApiTableGateway' => function ($sm) {
                    $dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
                    $resultSetPrototype = new ResultSet();
                    $resultSetPrototype->setArrayObjectPrototype(new Api());
                    return new TableGateway('apimaster', $dbAdapter, null, $resultSetPrototype);
                },
				
            ),
        );
	}
}

This is my Global.php file

return array(
   'db' => array(
        'driver' => 'SQLSRV',
	'servername' => '111.111.111.111',    
        'dbname' => 'demo',
    ),
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
        ),
    ),
);

This is my ApiTable.php in Model

namespace Application\Model;

use Zend\Db\TableGateway\TableGateway;
use Zend\Db\Sql\Select;
use Zend\Db\Sql\Expression;

class ApiTable
{
    protected $tableGateway;
    protected $serviceManager;

    public function __construct(TableGateway $tableGateway) {
        $this->tableGateway = $tableGateway;
    }

    public function setServiceLocator($sm) {
        $this->serviceManager = $sm;
    }

    public function getServiceLocator() {
        return $this->serviceManager;
    }

	public function fetchAll($status = null)
    {
		$resultSet = $this->tableGateway->select(function(Select $select) use ($status){
            if($status != 2) {
				$select->where(array('active'=>$status));
			}
        });		
        return $resultSet;
    }
}

**Comment by Bittarman** [comment]
Your missing a use statement for the table class in your module file, cause an exception to be raised when the code errors and there is no instance returned from your factory.

I'm closing this as its a support request, and not an issue with the framework itself, For support please feel free to use #zftalk on freenode irc, or the mailinglists.

**Comment by hardeepsharma90** [comment]
I add classes 
use Application\Model\Api;
use Application\Model\ApiTable;
in Module.php file
But Nothing happen
