### ISSUE TITLE
Zend\Form\Element\Text - required validation issue

### ISSUE THREAD

**Issue by dailiev** [zendframework/zf2#7582]
If in form we got Zend\Form\Element\Text element and there is required => false set for it. Validation error appears if there`s empty string in the field.

Lets say there is Text element with name test in the form. If we don`t add any inputFilter for it or we make it required => false with the following code it must not be required:

$this->filter->add($this->inputFactory->createInput(array(
	"name" => "test",
	"required" => false
)));

Now if we don not input anything in input test everything`s OK. But if we add one space in input test, validation message appears saying that "Field is required". So validation is OK with nothing in the field but empty string (one or several spaces) makes the field required which is very strange...

**Comment by Xerkus** [comment]
You might want to take a look at zendframework/zend-inputfilter#4

**Comment by Maks3w** [comment]
You can try to set `setContinueIfEmpty(false)`.

**Comment by Maks3w** [comment]
This was fixed by https://github.com/zendframework/zend-inputfilter/pull/25 and v2.5.5 has been released with the fix. Next week v2.4.8 will be released with the fix too.
