### ISSUE TITLE
While running ZF1 and ZF2 together,how to access ZF1 modules,models in library folder

### ISSUE THREAD

**Issue by sitaprajapati** [zendframework/zf2#7585]
While running ZF1 and ZF2 together,how to access ZF1 modules,models in library folder

**Comment by Maks3w** [comment]
This issue tracker is reserved for to discuss bugs and features. Please ask your integration questions in a Q&A site like stackoverflow.

PD: Try to register ZF1 autoloader in your ZF2 bootstrap. If you follow PSR-0/4 names then register the namespaces im composer. You can also use the autoload classmap feature of Composer for achieve the same.
