### ISSUE TITLE
Composer update no-dev loads dependencies from require-dev

### ISSUE THREAD

**Issue by googlle** [zendframework/zf2#7588]
Composer loads dependencies from require-dev:
doctrine/instantiator
phpdocumentor/reflection-docblock
phpspec/prophecy
symfony/yaml
phpunit/PHPUnit
sebastian/comparator
sebastian/diff
sebastian/environment
sebastian/exporter
sebastian/global-state
sebastian/version

**Comment by Bittarman** [comment]
Please could you expand on this somewhat? 
What command did you run? what composer version? 
On the face of it this sounds more like a composer / user error issue than a ZF one.

**Comment by svycka** [comment]
I think this is duplicate of https://github.com/zendframework/zf2/issues/7574

**Comment by Maks3w** [comment]
Duplicated #7574
