### ISSUE TITLE
Bootstrap sample class from official documentation not working with zf2 2.5

### ISSUE THREAD

**Issue by teseo** [zendframework/zf2#7592]
Hello,

The sample Bootstrap class in the [official documentation] (http://framework.zend.com/manual/current/en/tutorials/unittesting.html#bootstrapping-your-tests) is not working after the 2.5 version. 

I have updated my Bootstrap class in order to have my tests running with zf2 2.5. I can provide a diff if necessary.

May Thanks for your work!

**Comment by Martin-P** [comment]
This repository is for bugs in ZF2 itself. Please open an issue in the documentation repository: https://github.com/zendframework/zf2-documentation
