### ISSUE TITLE
routing by Hostname type for subdomains not work correctly 

### ISSUE THREAD

**Issue by faghihian71** [zendframework/zf2#7596]
i added a subdomain on my myhost.com like this reseller.myhost.com and i want it routing to Reseller module 
i read this question 
http://stackoverflow.com/questions/13070824/zend-framework-2-routing-subdomains-to-module

my reseller routing is this:

        'Reseller' => array(
            'type'    => 'Hostname',
            'options' => array(
                'route'    => 'reseller.myhost.com',
                'constraints' => array(

                ),
                'defaults' => array(
                    'controller' => 'Reseller\Controller\Reseller',
                    'action'     => 'index',
                ),
            ),
            'may_terminate' => true,

            'child_routes' => array(
                'login' => array(
                    'type' => 'Zend\Mvc\Router\Http\Literal',
                    'options' => array(
                        'route'    => '/login',
                        'defaults' => array(
                            'action'     => 'login',
                        ),
                    ),
                ),
                'createAd' => array(
                    'type' => 'Zend\Mvc\Router\Http\Literal',
                    'options' => array(
                        'route'    => '/createAd',
                        'defaults' => array(
                            'action'     => 'createAd',
                        ),
                    ),
                ),

            ),
        )

i except to it goes to reseller index action but it goes to application index action what should i do? and if i call url reseller.myhost.com/login every thing is ok but if i call reseller.myhost.com it goes to index of application module

after many searching i find a person have same problem 
he offer a way but it seems it has not standard way 

http://briangallagher.ie/2013/01/29/hostname-subdomain-routing-and-urls-using-zf2/

why it goes to index controller of application module and with this subdomain can route to base domain routes 

thank you

**Comment by DASPRiD** [comment]
First of, please not that the issue tracker is not meant for questions. Secondly, you are missing a path route for "/".

**Comment by faghihian71** [comment]
@DASPRiD  thank you and sry but where exaclty should i add / route in child routes?

**Comment by faghihian71** [comment]
@DASPRiD but one of  problems not solved yet by adding / route and its other routers from other modules works with this subdomain why?

**Comment by faghihian71** [comment]
@DASPRiD it is very important for me
