### ISSUE TITLE
[Suggestion] zend-cqrs

### ISSUE THREAD

**Issue by codeliner** [zendframework/zf2#7597]
I would like to reopen #7456 or continue with discussing the idea.
As I already commented in the linked issue I would like to start development of a message bus component that integrates in a ZF2 / ZF3 / zend-stratigility environment natively either by forking [prooph/service-bus](https://github.com/prooph/service-bus) to the zend organisation or by starting from scratch.

# Reasons
- CQRS is not only a hot topic but also a well known pattern for enterprise applications
- you can easily cover user intention with commands and publish changes via immutable (domain) events
- Separating your model into a write and read side enables you a new way of thinking about your system
- CQRS can be used to define a public API of your model that then can be used via HTTP, ESB, CLI or other ports to integrate external applications / services with your system
- After adding middleware to zend components for me the only missing piece in the zend-toolbox is a message bus component with support for CQRS and maybe an event store component, but this is another story
- CQRS enables you to handle commands and events asynchronous
- CQRS works great for distributed systems

Note: I'm not suggesting an architectural change of the zend ecosystem. I just would like to add a new component to have it in place for those who want to use it. With LTS provided by Zend.

What do you think?

**Comment by codeliner** [comment]
Btw here is a link to an experimental repo using zend-diactoros + zend-stratigility + prooph/service-bus: https://github.com/prooph/no-mvc

Some thoughts about it can be found here: 
https://groups.google.com/forum/#!topic/dddinphp/r_vwFvW9rN4

**Comment by codeliner** [comment]
not the expected answer, but ok :smile:

**Comment by hopsey** [comment]
How did it end? No plans on introducing CQRS package at all?

**Comment by Ocramius** [comment]
@codeliner and @prolic have been doing amazing work on @prooph, so I don't think that we should make it a ZendFramework project, since their expertise is much more advanced than what the ZendFramework devs have.

**Comment by codeliner** [comment]
thx @Ocramius . That is a great praise

@hopsey btw. @prooph ships w/ service manager compatible factories. so it can be seamlessly integrated with ZF2 and zend expressive

**Comment by hopsey** [comment]
Thank you for answer. I'll give it a try.
Are there any working implementations of prooph under ZF2/3? 
I would like to trigger events (ie with zend-eventmanager) form inside of particular command handler to make usage of commands more extendable, and can't find anything middleware-like functionality in PSB docs. Or am I getting a wrong approach?

**Comment by Ocramius** [comment]
@hopsey https://github.com/prooph/proophessor-do is a zend-expressive app that provides example implementation of integration between zf and prooph.
