### ISSUE TITLE
fromQuery returns empty value

### ISSUE THREAD

**Issue by danitome24** [zendframework/zf2#7606]
Hi,

I'm trying to get my query params from url like : `api?name=something` with `$this->params()->fromQuery();` but it returns empty value when I have parameters set. 

My route looks like: 
```
'api' => array(
                'type' => 'Zend\Mvc\Router\Http\Segment',
                'options' => array(
                    'route'    => '/api',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Extranet\Controller',
                        'controller' => 'api',
                        'action' => 'index',
                    ),
                ),
            ),
```

**Comment by adamlundrigan** [comment]
You'll need to provide more detail about your setup and issue, preferably a reproducible test case.  I use this functionality widely in my ZF2 applications and have not encountered a case where the query parameters don't make it through to the plugin.

**Comment by joacub** [comment]
tengo el mismo problema

**Comment by danitome24** [comment]
Buenas, yo el problema que tuve es que desde el module.php (concretamente desde el método onBoostrap) hacia un redirect y por lo tanto perdía los parámetros que me pasaban por get. Mira si en algun sitio haces algo así.

Saludos

**Comment by joacub** [comment]
bueno creo que puede ser algo que ver con fastcgi fallback por que uso hhvm y al parecer me esta haciendo un fallback y no esta relleno el _GET por alguna razón

**Comment by joacub** [comment]
yes the error is for in fallback or nginx not pass the query string to the backend
