### ISSUE TITLE
Wrong syntax

### ISSUE THREAD

**Issue by danilomrgouvea** [zendframework/zf2#7609]
The file Version\Version.php of 2.4.4 release has a wrong declaration of constants, wich broke the entire aplication.

The line 23 of this file shoud be something like this:
const VERSION = '2.4.4'

Thank you!

**Comment by Bittarman** [comment]
https://github.com/zendframework/zend-version/blob/release-2.4.4/src/Version.php#L23
Looks fine.

**Comment by danilomrgouvea** [comment]
Whoa, I looked just a few minutes ago... oO

Well, thanks anyway!

**Comment by danilomrgouvea** [comment]
Hey Bittarman, look at this link, see the problem I've talked about:

https://github.com/zendframework/zf2/blob/release-2.4.4/library/Zend/Version/Version.php

Thanks
