### ISSUE TITLE
Wrong syntax (hook from #7609)

### ISSUE THREAD

**Issue by danilomrgouvea** [zendframework/zf2#7610]
The issue in the subject was closed by Bittarman but the evidence showed points to anoter repository.

The file Version\Version.php of 2.4.4 release has a wrong declaration of constants, wich broke the entire aplication.

The line 23 of this file shoud be something like this:
const VERSION = '2.4.4'

Look at https://github.com/zendframework/zf2/blob/release-2.4.4/library/Zend/Version/Version.php to see the problem.

Thanks.

**Comment by Maks3w** [comment]
Confirm

**Comment by weierophinney** [comment]
Fixed, and replaced the release-2.4.4 tag with the fixed version.

**Comment by danilomrgouvea** [comment]
Thanks guys! :D
