### ISSUE TITLE
Remove /index.php from default routing to avoid duplicate URL's

### ISSUE THREAD

**Issue by alvsystems** [zendframework/zf2#7613]
I've noticed that by default the ZF2 router allows URL's prefixed with index.php i.e. http://mysite.com/index.php/my-page. I would expect this URL to return a 404 as the correct URL should be http://mysite.com/my-page but instead it allows both.

This behaviour happens when served via both Nginx and Apache and doesn't seem like a server issue but rather an application routing problem.

I'm not sure if this is a configuration problem on my end or a problem in the router itself but currently it allows two different URL's to serve duplicate content. From a SEO perspective this is apparently bad.

**Comment by DASPRiD** [comment]
It's actually not part of the router, but a fallback in the PhpEnvironment\Request class, to allow access to such applications without mod_rewrite or similar.

**Comment by alvsystems** [comment]
Thanks for the reply.
Is there any configuration to disable this behaviour?

**Comment by alvsystems** [comment]
Did some routing around myself and I realise I can modify the request's base url via $e->getRequest()->setBaseUrl('/') to avoid the detectBaseUrl method.

I'll test this to make sure I'm not breaking anything critical but it's a good start. Thanks for the info.

**Comment by DASPRiD** [comment]
Yep, setting the base URL manually disables that behaviour for good.
