### ISSUE TITLE
Zend\Db\Sql\Select getSqlString() output doesn't match the SQL generated

### ISSUE THREAD

**Issue by codemagician** [zendframework/zf2#7615]
Using the following query (although I suspect any query may produce the same result)

        $select = $sql->select(array(
            'R2' => 'reservations'
        ))->quantifier(Select::QUANTIFIER_DISTINCT);

        echo $select->getSqlString();

The echo shows quotation marks around each component of the query:

    SELECT DISTINCT "R2".* FROM "reservations" AS "R2"

Whereas the actual mysql logs show the backtick chatacter:

    SELECT DISTINCT `R2`.* FROM `reservations` AS `R2` ORDER BY `reservation_id` DESC LIMIT 2 OFFSET

The echoed output unfortunately doesn't contain the backtick character so whilst developing one cannot cut and paste the output to the mysql command-line client.  The quoted version is considered produces syntax error in mysql.

**Comment by Bittarman** [comment]
This looks like the result of not having the platform set in the sql\select. when you run the sql via the adapter the platform is then set and the platform specific changes can be made.

When you created the $sql object, did you pass the adapter?

**Comment by Bittarman** [comment]
@codemagician ?

**Comment by codemagician** [comment]
Sorry for the delay.  The adapter object is passed.  The object var_dump shows (is that useful?):
    // inside the mapper code layer

    $sql = new Sql($this->adapter);
    var_dump($this->adapter);

    object(Zend\Db\Adapter\Adapter)[429]
      protected 'driver' => 
        object(Zend\Db\Adapter\Driver\Pdo\Pdo)[431]
          protected 'connection' => 
            object(Zend\Db\Adapter\Driver\Pdo\Connection)[432]
              protected 'driver' => 
                &object(Zend\Db\Adapter\Driver\Pdo\Pdo)[431]
              protected 'profiler' => null
              protected 'driverName' => string 'mysql' (length=5)
              protected 'connectionParameters' => 
                array (size=5)
                  ...
              protected 'resource' => 
                object(PDO)[497]
                  ...
              protected 'inTransaction' => boolean false
              protected 'dsn' => string 'mysql:dbname=aspen-nuc-local' (length=28)
          protected 'statementPrototype' => 
            object(Zend\Db\Adapter\Driver\Pdo\Statement)[433]
              protected 'pdo' => null
              protected 'profiler' => null
              protected 'driver' => 
                &object(Zend\Db\Adapter\Driver\Pdo\Pdo)[431]
              protected 'sql' => string '' (length=0)
              protected 'isQuery' => null
              protected 'parameterContainer' => null
              protected 'parametersBound' => boolean false
              protected 'resource' => null
              protected 'isPrepared' => boolean false
          protected 'resultPrototype' => 
            object(Zend\Db\Adapter\Driver\Pdo\Result)[434]
              protected 'statementMode' => string 'forward' (length=7)
              protected 'resource' => null
              protected 'options' => null
              protected 'currentComplete' => boolean false
              protected 'currentData' => null
              protected 'position' => int -1
              protected 'generatedValue' => null
              protected 'rowCount' => null
          protected 'features' => 
            array (size=0)
              empty
      protected 'platform' => 
        object(Zend\Db\Adapter\Platform\Mysql)[435]
          protected 'resource' => 
            object(Zend\Db\Adapter\Driver\Pdo\Pdo)[431]
              protected 'connection' => 
                object(Zend\Db\Adapter\Driver\Pdo\Connection)[432]
                  ...
              protected 'statementPrototype' => 
                object(Zend\Db\Adapter\Driver\Pdo\Statement)[433]
                  ...
             protected 'resultPrototype' => 
                object(Zend\Db\Adapter\Driver\Pdo\Result)[434]
                  ...
              protected 'features' => 
                array (size=0)
                  ...
      protected 'profiler' => null
      protected 'queryResultSetPrototype' => 
        object(Zend\Db\ResultSet\ResultSet)[436]
          protected 'allowedReturnTypes' => 
            array (size=2)
              0 => string 'arrayobject' (length=11)
              1 => string 'array' (length=5)
          protected 'arrayObjectPrototype' => 
            object(ArrayObject)[437]
          protected 'returnType' => string 'arrayobject' (length=11)
          protected 'buffer' => null
          protected 'count' => null
          protected 'dataSource' => null
          protected 'fieldCount' => null
          protected 'position' => int 0
      protected 'lastPreparedStatement' => null

**Comment by Bittarman** [comment]
You'll need to pass the platform to getSqlString($adapter->getPlatform()). apologies, I forgot which way around it gets the platform.

For Reference:
http://framework.zend.com/manual/current/en/modules/zend.db.sql.html#zend-db-sql-s-select-insert-update-and-delete
