### ISSUE TITLE
ZF2 wants truncated controller name when rendering template

### ISSUE THREAD

**Issue by JVerstry** [zendframework/zf2#7616]
I have first reported this issue on StackOverflow (see some description there):  http://stackoverflow.com/questions/32141414/zf2-wants-truncated-controller-name-when-rendering-template-why?noredirect=1#comment52173892_32141414.

Although I declare 'MyCtrl', Zend 2 wants me to use 'my' when rendering a template.

// Mapping controller names to controller files
'controllers' => array(
     'invokables' => array(
         'Template\Controller\MyCtrl' => 'Template\Controller\MyController'
     )
 ),

**Comment by pauloelr** [comment]
You can use `controller_map` to more fine control over the name of a rendering template

See: https://github.com/zendframework/zf2/pull/5670

**Comment by Xerkus** [comment]
Not a bug. Controller class is used to resolve template name, not controller manager keys.
