### ISSUE TITLE
PhpRenderer not working on HHVM

### ISSUE THREAD

**Issue by rubenve** [zendframework/zf2#7617]
I'm trying to run the ZendSkeletonApplication on HHVM 3.10, but it fails on the PhpRenderer class.
In the hhvm error log I'm getting this error:

Fatal error: (hhvm.hack.disallow_dynamic_var_env_funcs=error) extract should not be called dynamically in /var/www/vhosts/example.com/hhvm.example.com/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php on line 487

This is the offending code:
       // extract all assigned vars (pre-escaped), but not 'this'.

        // assigns to a double-underscored variable, to prevent naming collisions
        $__vars = $this->vars()->getArrayCopy();
        if (array_key_exists('this', $__vars)) {
            unset($__vars['this']);
        }
        extract($__vars); // <--------- problematic call
        unset($__vars); // remove $__vars from local scope

This is used to make variables accessible directly in the view using $varname instead of $this->varname. Since HHVM considers dynamic variable assignment bad practice it's not supported, but it could be easily fixed by replacing the extract call with a foreach loop, i.e.:
    
        foreach ($__vars as $key => $val) {
            $$key = $val;
        }

I've tested it and HHVM does accept this instead.

**Comment by rubenve** [comment]
I just realized I should probably post this in the zend-view repository. Please let me know if that's the case. I have two more zend-view issues that break ZF2 apps on HHVM.

**Comment by Maks3w** [comment]
Yes it should be open in open in zend-view.  Even you can create a pull request with the fixes

**Comment by Ocramius** [comment]
> hhvm.hack.disallow_dynamic_var_env_funcs=error

This... is a hack issue, not an HHVM issue. You should really just allow that or mark the directory as "unsafe hack code"

**Comment by rubenve** [comment]
@Ocramius Thanks for the feedback. Pardon my ignorance, but I'm not sure what you mean by that. I'm trying to run a PHP app using HHVM as a FastCGI proxy, I'm not trying to run Hack code. Also how would I mark the directory as unsafe hack code?
