### ISSUE TITLE
IsRequired validation returns an array instead of an object

### ISSUE THREAD

**Issue by wenkepaul** [zendframework/zf2#7620]
If a form element is omitted from the the POST body, and is required by the form, an array with the message "Value is required" is returned.  To be consistent with other validation errors, should it be changed to return an object with a key of isRequired?

{"zip":["Value is required"]}
to
{"zip":{"isRequired":"Value is required"}}

**Comment by Maks3w** [comment]
This is an issue of inputfilter. Duplicate https://github.com/zendframework/zend-inputfilter/issues/28
