### ISSUE TITLE
Please release 2.6 tag

### ISSUE THREAD

**Issue by prolic** [zendframework/zf2#7622]
The Service Manager is already available in 2.6 and cannot get installed with the framework currently.

**Comment by grizzm0** [comment]
As of 2.5 all components are now maintained in their own repositories and versioned by themselfs. This repo is more or less just a "meta package". 

I would recommend you to only add the component you need in your own composer.json which will give you better control over each component version from here on.

**Comment by prolic** [comment]
@grizzm0 This doesn't work, as lot of open source zf2 modules out there require this package and not the needed components only. I would have to make PR's to a dozent repos.

**Comment by sandrokeil** [comment]
@prolic Maybe we need a ZF campaign "Only require needed components". That's really a bad practice of these libraries to use the whole framework.

**Comment by prolic** [comment]
@sandrokeil Agree. But the current situation is: I am working on a very big project for work and we require ~20 open source zf2 modules, I cannot submit PR's to all of them and expect them being merged very soon.

**Comment by Maks3w** [comment]
As workaround you can use https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

**Comment by sandrokeil** [comment]
@prolic Alright. You can also try https://getcomposer.org/doc/04-schema.md#replace /cc @Maks3w

**Comment by Maks3w** [comment]
I'll close this. I think next feature release will be v3
