### ISSUE TITLE
make lts version ( ~2.4.0 ) use php >=5.4

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zf2#7628]
as we maintain ~.2.4.0 with may be the changes applied to ~2.5 before, we `may` have to rollback long array to short array when backporting changes. So, I think in next version of ~2.4.0, we can use php 5.4. 

Thoughts?

**Comment by Ocramius** [comment]
@samsonasik not really possible, as bugfix releases should not lead to any sort of requirement change on the user side (unless it's required for the bugfix itself)

**Comment by Maks3w** [comment]
No, PHP 5.4 is LTS and the requirements must be the same.

**Comment by froschdesign** [comment]
@Maks3w 
PHP 5.4 and LTS? There is no LTS! (http://php.net/supported-versions.php)

ZF 2.4 is LTS!

**Comment by Maks3w** [comment]
Yes, sorry. I was mean 2.4 LTS. Thx @froschdesign
