### ISSUE TITLE
\Zend\Form\Element\Radio: error message not translated

### ISSUE THREAD

**Issue by fr00x** [zendframework/zf2#7630]
Hi,

I have the following form element and filter active:

            $this->add(array(
            'type' => 'Radio',
            'name' => 'foobar',
            'options' => array(
                'label'        => _('Foo*'),
                'label_attributes'   => array(
                    'class' => 'unused',
                ),

                'value_options' => array(
                    '1' => _('Yes'),
                    '0' => _('No'),
                ),
            ),
        ));

            $inputFilter->add(array(
                'name'     => 'foobar',
                'required' => true,
                'filters'  => array(
                    array('name' => 'StripTags'),
                    array('name' => 'StringTrim'),
                ),
                'validators' => array(
                    array(
                        'name'    => 'Digits',
                    ),
                ),
            ));

I have form error messages translation enabled, working well in the whole project, except on a radio element. The default english value is displayed: "Value is required". 

ZF Version: 2.4.7
\Zend\InputFilter\BaseFilter:254 seems to be the line where the error message is injected.

I tried setting custom error messages, but that didn't resolve the issue. What could I do to improve this?

Regards
fr00x

**Comment by Maks3w** [comment]
Duplicate https://github.com/zendframework/zend-inputfilter/issues/71
