### ISSUE TITLE
Getting strange header errors when fetching mail headers

### ISSUE THREAD

**Issue by ekr3peeK** [zendframework/zf2#7631]
Fatal error: Uncaught exception 'Zend\Mail\Exception\RuntimeException' with message 'Malformed header detected' in /var/www/html/plugins/ZendFramework/ZendFramework-2.4.7/library/Zend/Mail/Headers.php on line 88

This is the error message that I get when I try use the Zend\Mail\Storage\Imap::getMessage() function. If I comment out the line, where the error is thrown(to be more precise I have to comment out both lines where this same error is thrown from the same function), I am able to read the subject of the message, but later on on some e-mails I get a:

     Fatal error: Uncaught exception 'Zend\Mail\Header\Exception\InvalidArgumentException' with message 'Invalid header value detected' in /var/www/html/plugins/ZendFramework/ZendFramework-2.4.7/library/Zend/Mail/Header/GenericHeader.php on line 61

As I was testing the plugin, I didn't use any other extension or plugin while I got these errors, only the xDebug php extension, for debugging purposes. Here's my whole code:

    try {
	$mail = new Zend\Mail\Storage\Imap(array('host'     => 'my.mail.host',
                                         'user'     => 'mymail@mymail.com',
                                         'password' => 'xxxxxxxxx'));
    }
    catch (Zend\Mail\Exception $e) {
	print_r($e);
    }

    $undecodable=array();
    $mail->selectFolder('INBOX');

    $list=array(1,2,3,4);

    foreach ($list as $mid) {
	$message=$mail->getMessage($mid);
	$content=array(
		'html'	=> array(
			'part'		=>	null,
			'content'	=>	null
		),
		'plain'	=>	array(
			'part'		=>	null,
			'content'	=>	null
		)
	);
	foreach (new RecursiveIteratorIterator($message) as $part) {
		try {
			$strtok=strtok($part->contentType, ';');
			if (($strtok == 'text/html') || ($strtok == 'text/plain')) {
				switch ($part->contentTransferEncoding) {
					case 'base64':
						$contentDecoded = base64_decode($part->getContent());
						break;
					case 'quoted-printable':
						$contentDecoded = quoted_printable_decode($part->getContent());
						break;
					case 'default':
						$contentDecoded='undecodable';
						$undecodable[]=$part->contentTransferEncoding;
						break;
				}
				$strtok=explode("/",$strtok);
				$strtok=$strtok[1];
				$content[$strtok]['part']=$part;
				$content[$strtok]['content']=$contentDecoded;
			}
		} catch (Zend\Mail\Exception $e) {
			// ignore
		}
	}
	echo "Message: " . $message->subject."<BR>";
	if (!empty($content['html']['content'])) echo "HTML part found! ";
	if (!empty($content['plain']['content'])) echo "Plain part found! ";
	echo "<BR><BR>Next message";
    }
    exit;

**NOTE:** The message id's are correct, I can fetch all of the by telneting the mail server, they all exist

**Comment by Maks3w** [comment]
Please provide an example mail message.

**Comment by Maks3w** [comment]
Related https://github.com/zendframework/zend-mail/pull/19

**Comment by Maks3w** [comment]
Closed due inactivity

**Comment by Voyteck0** [comment]
This error is still valid - see http://www.linkedphpers.org/2016/04/zend-framework-2-zendmailmessagefromstr.html article which is very much connected with this issue...
