### ISSUE TITLE
Using git subtree manage source code may faster than composer update vendor

### ISSUE THREAD

**Issue by netroby** [zendframework/zf2#7636]
Zend Framework 2.5+ now using composer to manage submodule of ZF2. 
But the composer update progress will be very slow , due to it run git clone one by one for sub module.
It will take lots of time , and will execute the limit of github's resource limit.
Why not using git subtree to manage submodule of zend framework.
while checkout the main zf2 repository. then it will checkout the all in one repo.
And this change will not affect who using composer with zend framework submodule.
Because the git subtree can push and pull to dedicated git repo as well.

**Comment by Ocramius** [comment]
@netroby we actually went there multiple times: the path is MUCH more painful than it looks like, and for very little benefit.

**Comment by Ocramius** [comment]
Also, ZF2 is too large for subtree to work effectively

**Comment by macnibblet** [comment]
Setup your composer a github token for public repos, it will allow you to download the dist versions that are later cached by composer. Or setup https://toranproxy.com/ locally.
