### ISSUE TITLE
installed on mac, development mode

### ISSUE THREAD

**Issue by BardiaAfshin** [zendframework/zf2#7640]
After installing the Zend Server 6.2 on El Captian, I get this error when I run `zf` from command line

```bash
Error: I cannot find the autoloader of the application.
Check if /Users/me contains a valid ZF2 application.
```

**Comment by adamlundrigan** [comment]
For assistance on how to use the Zend Framework integration of Zend Server please use [the official Zend forum](http://forums.zend.com/viewforum.php?f=8&sid=d623fca2c7d767010d426126bc2cd043) or post a question on StackOverflow.
