### ISSUE TITLE
InputFilter - Input fallback_value doens't merge 

### ISSUE THREAD

**Issue by deny** [zendframework/zf2#7643]
Short story: 
Using fallback_value with Zend\InputFilter\InputFilterProviderInterface doesn't work, because Input merge method doesn't merge this value.

Long story: 
I upgrade zf2 from 2.4.2 to 2.4.8 and my Forms with MultiCheckbox stops working properly. I found that there is a change in 'required' flag.

In version 2.4.2 when I set 'required => false' then I always get array from this field and I can send form without checked option.

In version 2.4.8 when I set 'required => true', then I always get array from this field, but I cannot send form without checked option. If I set 'required => false', then I can send form without checked option, but i get null when no option is checked.

After reading a doc I want to use combination 'required => true, fallback_value => []', which doesn't work.

**Comment by Maks3w** [comment]
Duplicate https://github.com/zendframework/zend-inputfilter/issues/35
