### ISSUE TITLE
Move the bin scripts to their own module

### ISSUE THREAD

**Issue by larsnystrom** [zendframework/zf2#7644]
I like to use the `classmap_generator.php` to generate classmaps for my modules. It would be nice if it was possible to put it in the `require-dev` part of my composer.json.

If I do that right now, this package will in turn install all other zf2 modules, which is not what I wanted.

It would be really nice if the scripts in the bin directory was available as their own module, such as `Zend\Dev` or similar.

**Comment by Maks3w** [comment]
Duplicate https://github.com/zendframework/zf2/issues/7587
