### ISSUE TITLE
View rendered dispited SharedManager attach redirect 

### ISSUE THREAD

**Issue by Tiega91** [zendframework/zf2#7649]
I have a simple ACL

    if (!$e->getViewModel()->acl->hasResource($route) || !$e->getViewModel()->acl->isAllowed($role, $route)) {
            //Naughty trying to get somewhere they shouldn't (Clear there identity force them to login again)
            $response = $e->getResponse();
            //location to page or what ever
            if($request->isPost())
            {
                $response->setStatusCode(401);
                return $response;
            }
            else
            {
                return $e->getTarget()->getEventManager()->getSharedManager()->attach('Zend\Mvc\Controller\AbstractActionController', 'dispatch', function($e)  {
                    $controller = $e->getTarget();
                    $controller->redirect()->toRoute('auth');
                }, 1000);
            }
        }

after i added a sql-query that need the userID the redirect gets interrupted on my dev-server and shows the notice that no userID is defined.

On the prod-server the redirect works but i still get a error_log entry that the userID is not defined. That means that the redirect is executed AFTER the Action is called.

In my understanding it should redirect before everything else in DISPATCH.

**Comment by Xerkus** [comment]
Didn't read, some issue in posted code: `return $controller->redirect()->toRoute('auth');`

**Comment by Tiega91** [comment]
ah i understand, to interrupt the code i have to return the redirect...
sry can be closed
