### ISSUE TITLE
is zend-ldap required in suggestion, it is in zend-authentication already

### ISSUE THREAD

**Issue by svycka** [zendframework/zf2#7661]
for now I see this when install this meta package:
```
zendframework/zend-authentication suggests installing zendframework/zend-ldap (Zend\Ldap component)
zendframework/zendframework suggests installing zendframework/zend-ldap (zend-ldap component ~2.5.0, if you need LDAP features)
```

**Comment by Maks3w** [comment]
The first one is at scope level, the second is for advise to people before <2.5 where the component was shipped by default.

**Comment by svycka** [comment]
@Maks3w I know this, but removing it in this package you will still see one suggestion so why we need two? I see only one advantage here it is in composer.json :D unless composer.json works as documentation here

**Comment by Maks3w** [comment]
The real problem is with composer and should be asked to them. 

- Don't print suggestions for indirect dependencies.
- Print a single suggestion for the same package.
