### ISSUE TITLE
[REDACTED]

### ISSUE THREAD

**Issue by ravigupta112** [zendframework/zf2#7662]
[REDACTED]

**Comment by Ocramius** [comment]
@ravigupta112 please refer to http://framework.zend.com/security/ if you think that you found a security issue. Security issues should NOT be discussed in public channels.

**Comment by ravigupta112** [comment]
okay, I have emailed this issue at zf-security@zend.com

**Comment by Ocramius** [comment]
@ravigupta112 thanks!

**Comment by GeeH** [comment]
@Ocramius can this be closed please?
