### ISSUE TITLE
Upgrade through composer (~2.5) to 2.5.3 (?) breaks zend-session ValidatorChain class

### ISSUE THREAD

**Issue by YonmaNBehalf** [zendframework/zf2#7676]
After composer update error log shows:
PHP Fatal error:  Zend\\Session\\Validator\\ValidatorChainEM2 has colliding constructor definitions coming from traits in /srv/www/behalf_api/releases/20160223162224/vendor/zendframework/zend-session/src/Validator/ValidatorChainEM2.php on line 32

**Comment by weierophinney** [comment]
Can you provide a bit more detail, please?

- output of `composer info -i`
- what version of PHP are you using?

**Comment by weierophinney** [comment]
If you do a `composer update zendframework/zend-session`, the issue should now be resolved.
