### ISSUE TITLE
[ZF2] Statement could not be executed with paginator and view

### ISSUE THREAD

**Issue by Payalba** [zendframework/zf2#7679]
Hi,

When i use a view with a paginator the where->like with sql\expression doesn't work with the message :
      
Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIKE '%aa%') AS `original_select`' at line 1)

The code :
`$select->where->like(new \Zend\Db\Sql\Predicate\Expression("concat(nom,' ',prenom)"), '%' . $value . "%");`

Actually to solve this pb, i do the concatenation in my view.

Regards,

PYT

**Comment by samsonasik** [comment]
please report against https://github.com/zendframework/zend-db/issues instead.

**Comment by adamlundrigan** [comment]
Moved to https://github.com/zendframework/zend-db/issues/90
