### ISSUE TITLE
Zend\Mvc\Controller\AbstractController\getServiceLocator Now Triggers Error

### ISSUE THREAD

**Issue by tomshaw** [zendframework/zf2#7680]
I have two questions. First when did getServiceLocator start triggering a dependency injection error. Second where can I find documentation how to correctly inject dependencies into controllers. Normally I register them using Modules.php:

```
    public function getServiceConfig()
    {
        return array(
            'factories' => array(
                'Application\Model\User' => function ($sm) {
                    $dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
                    $resultSetPrototype = new ResultSet();
                    $resultSetPrototype->setArrayObjectPrototype(new User());
                    return new TableGateway('user', $dbAdapter, null, $resultSetPrototype);
                },
                'Application\Model\UserTable' => function ($sm) {
                    $tableGateway = $sm->get('Application\Model\User');
                    $table = new UserTable($tableGateway);
                    return $table;
                }
            )
        );
    }
```
UserController.php

```
    protected $userTable;
	
    public function getUserTable()
    {
        if (!$this->userTable) {
            $sm = $this->getServiceLocator();
            $this->userTable = $sm->get('Application\Model\UserTable');
        }
        return $this->userTable;
    }
```

This is a massive compatibility change and major difference how the original ZF2 documentation explained how thing worked and will have H/Yuge ramifications on production systems for existing clients. I'm currently working on an Apigility application when I noticed the change this morning. I'm afraid to look at our other ZF2 clients production systems and will warn them not to run compser update until a viable solution is tested.

**Comment by froschdesign** [comment]
Please read here: https://github.com/zendframework/zend-mvc/issues/89

**Comment by tomshaw** [comment]
@froschdesign Thank you for closing the issue immediately/within 10 minutes and failing to answer either question whatsoever. 

- When did getServiceLocator start triggering a dependency injection error. 
- Second where can I find documentation how to correctly inject dependencies into controllers. 

Currently 03/03/1016 the official Zend documentation explains how to register/inject dependencies the way I've described. 

[http://framework.zend.com/manual/current/en/user-guide/database-and-models.html](http://framework.zend.com/manual/current/en/user-guide/database-and-models.html)

**Comment by froschdesign** [comment]
@tomshaw 
You can find the explanation behind the link which I have added in my previous comment.

In the ["In-depth tutorial for beginners"](http://framework.zend.com/manual/current/en/in-depth-guide/services-and-servicemanager.html) you can find code examples for this topic.
