### ISSUE TITLE
Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer

### ISSUE THREAD

**Issue by waney** [zendframework/zf2#7682]
_____________________________________________________
Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your class User\Service\Invokable\User to remove the implementation, and start injecting your dependencies via factory instead. in vendor\zendframework\zend-mvc\src\Service\ServiceManagerConfig.php on line 147

UPDATES IN 2.5.2
Help!Help!Help!...

**Comment by Ocramius** [comment]
That deprecationis intentional. See https://github.com/zendframework/zend-mvc/issues/89#issuecomment-191404454

**Comment by waney** [comment]
How to change my code?

**Comment by zf2timo** [comment]
As the deprecation Message says, you have to create a Factory for your `User\Service\Invokable\User` and inject the dependencies there.

**Comment by froschdesign** [comment]
@waney 
In your current application version or on your production system you can hide these error messages with [`error_reporting`](http://php.net/manual/en/function.error-reporting.php).
In future versions of your application you should use factories. You can find a tutorial in the documentation: "In-depth tutorial for beginners: [Introducing Services and the ServiceManager](http://framework.zend.com/manual/current/en/in-depth-guide/services-and-servicemanager.html)".

**Comment by waney** [comment]
@froschdesign @zf2timo 
Ths.
