### ISSUE TITLE
Event like distruct method

### ISSUE THREAD

**Issue by ravigupta112** [zendframework/zf2#7691]
Hi,

I have created new module, in there i want to unset all variables after completion of all operations.
I can do it if i add unset code under all actions of all controllers and all actions has same code instead of this is there any way where i can add unset code at one function / contoller so we have to not wright same code on all actions. 

i am using below code to unset all variable of current action/function

$allVar = array_keys(get_defined_vars());
        foreach ($allVar as $var) {
            unset($$var);
        }
        unset($allVar, $var);

**Comment by Thinkscape** [comment]
Why would you do that, ever?
If you want to run a piece of code after each method, after rendering or after the app has finished dispatching, you can add a listener.
Here's a list of MVC events: http://framework.zend.com/manual/current/en/modules/zend.mvc.mvc-event.html#order-of-events

Or this list, easier to read: https://akrabat.com/a-list-of-zf2-events/

Here's an example for how to attach listeners to MVC events:
http://lab.empirio.no/how-to-attach-mvc-events-in-zf2.html

**Comment by ravigupta112** [comment]
thanks Thinkscape

**Comment by sasezaki** [comment]
can be closing this issue ?
