### ISSUE TITLE
Session Management through database

### ISSUE THREAD

**Issue by ravigupta112** [zendframework/zf2#7693]
Can any one let me know how to manage session in database in zf2

**Comment by jeandormehl** [comment]
Hi Ravi

Take a look at this repo: https://github.com/hrevert/HtSession
You could either use it or get ideas from there.

**Comment by Thinkscape** [comment]
Use `Zend\Session`.

It's covered in docs and there's several tutorial articles on the Internet:
* http://framework.zend.com/manual/current/en/modules/zend.session.save-handler.html#dbtablegateway
* https://pavlakis.info/php/12-database-sessions-with-zf2

**Comment by sandrokeil** [comment]
[Zend Session](https://github.com/zendframework/zend-session/blob/master/doc/book/zend.session.save-handler.md) provides multiple Session Save Handler. @ravigupta112 Please close this issue.

**Comment by ravigupta112** [comment]
hi sandrokeil ,

I have tried this but it is not working.

**Comment by Ocramius** [comment]
Closing, as no actual issue was raised here.
