### ISSUE TITLE
How to let zend-form support vue.js element attributes,

### ISSUE THREAD

**Issue by waney** [zendframework/zf2#7694]
How to let zend-form support vue.js element attributes,
for example:<input v-mode="abc" ...

**Comment by vitorbarros** [comment]
@waney vue js is similar with angular js that is possible to integrate with zf, so in this case you can use a html file with your form and send a request to zf with inputs and use zend form to help you validate the sent data. If you want i can show you how to do that.

**Comment by waney** [comment]
@vitorbarros https://github.com/zendframework/zend-form/issues/50, Thank you.

**Comment by froschdesign** [comment]
Duplicate
